### ISSUE TITLE
org.eclipse.kura.linux.net.ConnectionInfoImpl is IPv4 only

### ISSUE THREAD

**Issue by wnagele** [eclipse/kura#104]
Throws ClassCastExceptions if you are on a network with IPv6 capabilities - see example below. Even worse - can never work on IPv6 only network. :(

`java.lang.ClassCastException: org.eclipse.kura.net.IP6Address cannot be cast to org.eclipse.kura.net.IP4Address
    at org.eclipse.kura.linux.net.ConnectionInfoImpl.getDnsServers(ConnectionInfoImpl.java:123)
    at org.eclipse.kura.linux.net.NetworkServiceImpl.getNetInterfaceAddresses(NetworkServiceImpl.java:872)
    at org.eclipse.kura.linux.net.NetworkServiceImpl.getNetworkInterface(NetworkServiceImpl.java:518)
    at org.eclipse.kura.linux.net.NetworkServiceImpl.getNetworkInterfaces(NetworkServiceImpl.java:370)
    at org.eclipse.kura.net.admin.NetworkConfigurationServiceImpl.getNetworkConfiguration(NetworkConfigurationServiceImpl.java:277)
    at org.eclipse.kura.net.admin.NetworkAdminServiceImpl.getNetworkInterfaceConfigs(NetworkAdminServiceImpl.java:192)
    at org.eclipse.kura.web.server.GwtNetworkServiceImpl.privateFindNetInterfaceConfigurations(GwtNetworkServiceImpl.java:150)
    at org.eclipse.kura.web.server.GwtNetworkServiceImpl.findNetInterfaceConfigurations(GwtNetworkServiceImpl.java:107)`

**Comment by cdealti** [comment]
@wnagele Kura does not support IPv6 (yet).
Can you please attach to the issue the latest configuration snapshot?
Assuming you are using the Kura version with the Web UI you can download the latest configuration snapshot from **Settings**.

Can you also describe your setup:
* Platform (e.g. Raspberry PI 2)
* Network configuration of the interface attached to you IPv6 LAN
* Kura version/installer used. With or without the Web UI?
* How the network has been configured on the platform

**Comment by wnagele** [comment]
Well if there is no IPv6 support yet that's a shame. :) I would still recommend to perform a instanceof check in there to ensure that only actual IPv4 addresses are trying to be cast. This will at least ensure that Kura works on a dualstack network.

**Comment by kartben** [comment]
+1 to @wnagele's suggestion

**Comment by cdealti** [comment]
We made changes to the Kura networking that might have fixed the bug (but no IPv6 support yet - sorry).
@wnagele can you try a build from the ``develop`` branch?

**Comment by MMaiero** [comment]
@wnagele Have you got any feedback on this bug? Is the exception solved?

**Comment by cdealti** [comment]
No feedback from the user. Postponed to Kura 2.1.0.

**Comment by dwoodard1** [comment]
@cdealti Should we close this or leave it open to track the need for IPv6 support?

**Comment by cdealti** [comment]
I'd close it.

**Comment by dwoodard1** [comment]
We are closing this until we have a proper solution for implementing IPv6.
