### ISSUE TITLE
[Kura 3.0.0 M1 QA] de.dentrassi.kura.addons.milo regression

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1117]
Test case CAMEL-CCS-003 describes configuration of de.dentrassi.kura.addons.milo DP 0.1.0. This version installs and configures as the test case specifies without issues.

A new version, 0.2.1, is available on Eclipse Marketplace. Installation works. When configured only with Router XML, it still works. When init script is configured, this exception is shown in console log:
```
...
javax.script.ScriptException: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.apache.camel.component.milo.server.MiloServerComponent
        at org.eclipse.kura.camel.runner.ScriptRunner.runWithClassLoader(ScriptRunner.java:162)
        at org.eclipse.kura.camel.runner.ScriptRunner$EvalScriptRunner.run(ScriptRunner.java:62)
        at org.eclipse.kura.camel.utils.CamelContexts.scriptInitCamelContext(CamelContexts.java:64)
        at org.eclipse.kura.camel.cloud.factory.internal.XmlCamelCloudService.callInitCode(XmlCamelCloudService.java:132)
        at org.eclipse.kura.camel.cloud.factory.internal.XmlCamelCloudService.start(XmlCamelCloudService.java:82)
        at org.eclipse.kura.camel.cloud.factory.internal.CamelFactory.createService(CamelFactory.java:86)
        at org.eclipse.kura.camel.cloud.factory.internal.CamelFactory.setFromProperties(CamelFactory.java:47)
        at org.eclipse.kura.camel.cloud.factory.internal.CamelFactory.modified(CamelFactory.java:37)
...
```

RPi3, Kura 3.0.0-SNAPSHOT, build 940.

@ctron, could you please take a look at this?

**Comment by ctron** [comment]
This should be solved with a new version 0.2.2 of the DP. When it is synced to Maven Central it will appear here: [1]

[1] https://repo1.maven.org/maven2/de/dentrassi/kura/addons/de.dentrassi.kura.addons.milo/0.2.2/

**Comment by ctron** [comment]
It's been synced.

**Comment by markoer** [comment]
Verified on Kura 3.0.0 M1 build 945 and DP ver. 0.2.2.
Closing the issue.
