### ISSUE TITLE
java.lang.IllegalStateException: Invalid MQTT client configuration 

### ISSUE THREAD

**Issue by ghost** [eclipse/kura#1366]
hello ,

i am trying work on sample hello world example ,i followed the step which is there in the Kura web site https://eclipse.github.io/kura/doc/hello-example.html
but when i try to test in and emulator i got following 
17:09:13,854 [Component Resolve Thread] ERROR MqttDataTransport:774  - Invalid configuration
17:09:13,855 [Component Resolve Thread] ERROR MqttDataTransport:197  - Invalid client configuration. Service will not be able to connect until the configuration is updated
java.lang.IllegalStateException: Invalid MQTT client configuration
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.buildConfiguration(MqttDataTransport.java:775)
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.activate(MqttDataTransport.java:194)

[pool-13-thread-1] ERROR DbDataStore:280  - Store capacity exceeded
16:48:02,866 [] ERROR Heater:275  - Cannot publish topic: data
org.eclipse.kura.KuraStoreCapacityReachedException: "Error performing operation on store. Store capacity exceeded"
	at org.eclipse.kura.core.data.store.DbDataStore.store(DbDataStore.java:281)
	at org.eclipse.kura.core.data.DataServiceImpl.publish(DataServiceImpl.java:443)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:107)
	at org.eclipse.kura.demo.heater.Heater.doPublish(Heater.java:272)
	at org.eclipse.kura.demo.heater.Heater.access$0(Heater.java:229)
	at org.eclipse.kura.demo.heater.Heater$1.run(Heater.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
16:48:02,875 [pool-13-thread-1] ERROR ExamplePublisher:277  - Cannot publish topic: data/metrics
org.eclipse.kura.KuraStoreCapacityReachedException: "Error performing operation on store. Store capacity exceeded"

COULD you please helps me in resolving this issue ,where i am going wrong
it would of great help
i am using latest version of kura running on Ubuntu 16  
Thanks in Advance

**Comment by cdealti** [comment]
Hello,
  This usually happens on Linux if the link on you Ethernet port is down (no cable or other end of the cable not connected to switch/router).
Either provide link to the Ethernet port **or** manually configure the **client-id** property from the Kura Web UI @locahost:8080.
The **client-id** is available under **Cloud Services**. Select the connection in the table and click on the **MqttDataTransport** tab.
Set the value of **client-id** to whatever you like, for example your name.

**Comment by MMaiero** [comment]
Hi @Roopa-Siddaveerappa, can this be closed?
Thanks
