### ISSUE TITLE
[Wires] DB store primary key

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1378]
DbWireRecordStore creates the table to store data in using `CREATE TABLE IF NOT EXISTS {0} (TIMESTAMP BIGINT NOT NULL PRIMARY KEY)`. 

insertDataRecord() in line 462 calls the following:
```java
stmt = prepareStatement(connection, tableName, wireRecordProperties, new Date().getTime());
```
where TIMESTAMP column is set to the current system time.

Now, if the insertions would happen to be performed more than once per ms, the following error would occur:

```
org.eclipse.kura.internal.wire.store.DbWireRecordStore store
SEVERE: Insertion failed. Reconciling Table and Columns...
java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; SYS_PK_10096 table: "STORE_TEST"
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
	at org.eclipse.kura.internal.wire.store.DbWireRecordStore.insertDataRecord(DbWireRecordStore.java:463)
	at org.eclipse.kura.internal.wire.store.DbWireRecordStore.store(DbWireRecordStore.java:309)
	at org.eclipse.kura.internal.wire.store.DbWireRecordStore.onWireReceive(DbWireRecordStore.java:288)
	at org.eclipse.kura.internal.wire.store.test.DbWireRecordStoreTest.testCleanupSequence(DbWireRecordStoreTest.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	...
Caused by: org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; SYS_PK_10096 table: "STORE_TEST"
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Constraint.getException(Unknown Source)
	at org.hsqldb.index.IndexAVLMemory.insert(Unknown Source)
	at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
	at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
	at org.hsqldb.Session.addInsertAction(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 49 more
```

I realize it's unlikely for that to happen due to gateways not being as fast as development machines and timer interval is 1 ms. Except maybe in an event where 2 wires stores fill the same table.

Timestamp may be useful, so my proposal is to add a different ID:
`CREATE TABLE IF NOT EXISTS {0} (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, TIMESTAMP BIGINT);`

In this case the only incompatiibility with the existing DB is the ID, which would not be generated for the existing tables. Most of the code would not need to be changed.

Encountered on the current develop branch.

**Comment by MMaiero** [comment]
Closing as PR #1380 has been merged. @markoer Ok for you?

**Comment by markoer** [comment]
OK
