### ISSUE TITLE
SCR exception running Kura Wires in Karaf

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1414]
An attempt to use Kura Wires in Karaf result in the following SCR exception:

```
 2017-05-26 12:47:15,741 [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.eclipse.kura.wire.DbWireRecordStore.35db9b19-a49f-42e0-9193-f8c99eada53e)] ERROR o.e.k.w.c.provider - [org.eclipse.kura.wire.DbWireRecordStore(36)] Circular reference detected, getService returning null

2017-05-26 12:47:16,134 [Framework Event Dispatcher: Equinox Container: 404f1cd3-0f42-0017-1c40-c947b046bf35] WARN  o.e.k.w.c.provider - FrameworkEvent WARNING - org.eclipse.kura.wire.component.provider

org.osgi.framework.ServiceException: org.apache.felix.scr.impl.manager.SingleComponentManager.getService() returned a null service object

at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:232)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:619)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.kura.internal.wire.helper.WireHelperServiceImpl.getServicePid(WireHelperServiceImpl.java:112)

at org.eclipse.kura.internal.wire.helper.WireSupportImpl.<init>(WireSupportImpl.java:76)

at org.eclipse.kura.internal.wire.helper.WireHelperServiceImpl.newWireSupport(WireHelperServiceImpl.java:164)

at org.eclipse.kura.internal.wire.store.DbWireRecordStore.activate(DbWireRecordStore.java:161)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_51]

at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)[:1.8.0_51]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)[:1.8.0_51]

at java.lang.reflect.Method.invoke(Unknown Source)[:1.8.0_51]

at org.apache.felix.scr.impl.helper.BaseMethod.invokeMethod(BaseMethod.java:222)

at org.apache.felix.scr.impl.helper.BaseMethod.access$500(BaseMethod.java:37)

at org.apache.felix.scr.impl.helper.BaseMethod$Resolved.invoke(BaseMethod.java:615)

at org.apache.felix.scr.impl.helper.BaseMethod.invoke(BaseMethod.java:499)

at org.apache.felix.scr.impl.helper.ActivateMethod.invoke(ActivateMethod.java:295)

at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:302)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:113)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:866)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:833)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:774)[18:org.apache.felix.scr:2.0.2]

at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)

at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_51]

at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:619)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.osgi.util.tracker.ServiceTracker.addingService(ServiceTracker.java:414)[org.osgi.core-6.0.0.jar:]

at org.eclipse.kura.core.configuration.ConfigurationServiceImpl$3.addingService(ConfigurationServiceImpl.java:258)[126:org.eclipse.kura.core.configuration:1.1.0]

at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)[org.osgi.core-6.0.0.jar:]

at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)[org.osgi.core-6.0.0.jar:]

at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)[org.osgi.core-6.0.0.jar:]

at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)[org.osgi.core-6.0.0.jar:]

at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)[org.osgi.core-6.0.0.jar:]

at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:914)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:869)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:857)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:915)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:715)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:399)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.scr.impl.config.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:424)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.scr.impl.config.ConfigurationSupport.configurationEvent(ConfigurationSupport.java:315)[18:org.apache.felix.scr:2.0.2]

at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:2046)[7:org.apache.felix.configadmin:1.8.8]

at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:2014)[7:org.apache.felix.configadmin:1.8.8]

at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]

at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]

at java.lang.Thread.run(Unknown Source)[:1.8.0_51]
```

**Comment by cdealti** [comment]
@MMaiero should we move this to Backlog?

**Comment by cdealti** [comment]
Closing. Karaf will not be further developed.

**Comment by kartben** [comment]
This is more than a Karaf issue and is an actual bug, that just happens to be ignored by Equinox and only gets picked up when using Felix which I guess is more strict. 

As part of their activate code, Kura WireComponents typically do something like "wireHelperService.newWireSupport(this)", however the way newWireSupport is implemented triggers a getService() on the very component that is already in the process of being created, resulting in the error.
The proper fix would be to get newWireSupport() to just take a ServiceReference as a parameter in the first place, but another way to fix it is by making sure that newWireSupport() does not perform an unecessary getService, since all it needs in the end can be found in the properties of the ServiceReference


I will provide a fix.
