### ISSUE TITLE
H2 DB: invalid service configuration not indicated

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1501]
Configuring H2 DB service as `db.connector.url=jdbc:h2:mem:` (unsupported configuration) reports no error in the web UI. The exception is properly thrown by the H2DbService(Impl) as seen from the log:

```
2017-07-10 12:24:30,041 [Component Resolve Thread (Bundle 7)] WARN  o.e.k.c.d.H2DbServiceImpl - Database initialization failed
java.lang.IllegalArgumentException: Anonymous in-memory databases instances are not supported
        at org.eclipse.kura.core.db.H2DbServiceImpl.updated(H2DbServiceImpl.java:114)
```

My issue with it is that if I don't check the logs, I won't know that there's something wrong with my setup until e.g. Wires H2 DB store will fail. Also, ERROR log level might be justified here as it has wider repercussions e.g.:

```
2017-07-10 12:27:08,487 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.h.s.H2DbWireRecordStore - H2DbService instance found
2017-07-10 12:27:08,512 [Component Resolve Thread (Bundle 7)] ERROR o.e.k.i.w.h.s.H2DbWireRecordStore - Error while storing Wire Records...
java.sql.SQLException: Database instance not initialized
        at org.eclipse.kura.core.db.H2DbServiceImpl.getConnection(H2DbServiceImpl.java:172)
        at org.eclipse.kura.internal.wire.h2db.common.H2DbServiceHelper.getConnection(H2DbServiceHelper.java:145)
```

Kura 3.1.0-SNAPSHOT, build 1121, RPi 3

**Comment by cdealti** [comment]
The same issue applies to all the Configurable Components. The Meta Type only supports basic type validation and the component implementation is (asynchronously) responsible for further validation.

**Comment by cdealti** [comment]
@nicolatimeus can you please fix the log level only? 
There's no need to create PR for this, just push to develop.

Unfortunately the main issue cannot be easily fixed.
