### ISSUE TITLE
Problem in constructing  the Kura Development Environment

### ISSUE THREAD

**Issue by OrangeAlex** [eclipse/kura#1601]
Hi,
     i am try to building Kura via the Oomph installer under the Linux (Ubuntu14.04), after finishing downloading the Eclispse IDE , the IDE(Neno 3) start, and build the project , when the IDE download the Kura resource code from the git , it have some error , the information as fellows :

Performing Git Clone https://github.com/eclipse/kura.git  (develop)
Cloning Git repo https://github.com/eclipse/kura.git to /home/iot/iot-kura-develop/git/kura
java.lang.Exception: java.lang.RuntimeException: java.lang.NullPointerException
  at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.perform(GitCloneTaskImpl.java:881)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3324)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4494)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4488)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4486)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3258)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3233)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3133)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:567)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:693)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1488)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
  at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3018)
  at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
  at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:99)
  at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:202)
  at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:504)
  at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:326)
  at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
  at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
  at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1236)
  at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:234)
  at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:293)
  at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:190)
  at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.cloneRepository(GitCloneTaskImpl.java:942)
  at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.perform(GitCloneTaskImpl.java:805)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3324)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4494)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4488)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4486)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3258)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3233)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3133)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:567)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:693)
the screen image as the attachment
Any ideas how to fix it? thanks
Best regards, Alex.wang

**Comment by dwoodard1** [comment]
@OrangeAlex Did you change any of the settings during installation? If so, can you please provide the changes you made?

**Comment by OrangeAlex** [comment]
@dwoodard1  hi,dwoodard1 , i have not changed the settings during the installation, i list my setting here 
Developer Type : developer
JRE 1.8 Location: /usr/lib/jvm/jdk1.8.0_144
Eclipse Kura Git clone location:/home/iot/iot-kura-develop/git/kura
Eclipse Kura Git repository: https://github.com/eclipse/kura.git
By the way , i also summit the error issus at the Kura official Forums, the link: https://www.eclipse.org/forums/index.php/t/1088236/
I have the screenshot pic with the attachment
Thank you

**Comment by markoer** [comment]
@OrangeAlex I suppose you already solved this error since you reported the issue #1605 which occurs later during the installation. Was the problem a failing network connection?

**Comment by OrangeAlex** [comment]
@mrkoer  ,  actually to say , i have not solved the problem,  i download the Zip package of the project resource code from kura official github website . and then unzip it , and copy the project resource code to the path /kura/kura/git, and then i  rebuild the project , there is no mistake like before i met , so i can continue to bulid the project , but duiring donwloading the maven package, i have new problem which i descripe it in this isusse report ^_^, so i still don not the where the problem is clearly

**Comment by OrangeAlex** [comment]
@mrkoer , actually to say , i have not solved the problem, i download the Zip package of the project resource code from kura official github website . and then unzip it , and copy the project resource code to the path /kura/kura/git, and then i rebuild the project , there is no mistake like before i met , so i can continue to bulid the project , but duiring donwloading the maven package, i have new problem which i descripe it in the isusse #1605 report ^_^, so i still don not the where the problem is clearly

**Comment by MMaiero** [comment]
@OrangeAlex Can this be closed?

**Comment by OrangeAlex** [comment]
@MMaiero  i have install kura on the Raspberry Pi , so you can close this issue
