### ISSUE TITLE
[Artemis] MQTT clients fail to reconnect after the broker is restarted

### ISSUE THREAD

**Issue by nicolatimeus** [eclipse/kura#1644]
Stopping and restarting embedded Artemis broker instances might cause a previously connected client to fail to reconnect.
Steps to reproduce:
1. Enable the **Simple Artemis MQTT Broker** or the **ActiveMQ Artemis Broker**.
2. Connect a Kura Cloud Service instance to the broker.
3. Stop and restart the broker.
4. Try to reconnect the client.

After repeating steps 3 and 4 a couple of times the cloud service might fail to reconnect.
The Kura log reports this exception:
```
org.eclipse.kura.KuraConnectException: "Connection failed. Cannot connect"
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.connect(MqttDataTransport.java:333)
	at org.eclipse.kura.core.data.DataServiceImpl$2.run(DataServiceImpl.java:609)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: Invalid client ID (2)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:990)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:118)
	... 1 more
```
The client Id of the CloudService is valid since it has been previously accepted by the broker.
This seems to be caused by the fact that in the [MQTTConnectionManager](https://github.com/apache/activemq-artemis/blob/c8982d775b55849836ae20739a9e82f7eaf1d650/artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTConnectionManager.java#L43) class there is a static set that contains a list of the connected client ids, a new connection is not accepted by the broker if the client ID is already present in this set.
It seems like this set is not properly cleared, during my tests it always contains the client id of the CloudService that fails to connect even after that the broker is disabled.

The fact that the broker does not accept a connection if there is a client already connected with the same clientId violates the MQTT spec, according to [MQTT-3.1.4-2](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349768) the broker should disconnect the existing client and accept the new connection.

The existence of this static set also introduces some coupling between the **Simple Artemis MQTT Broker** and **ActiveMQ Artemis Broker** services: it is not possible to connect to one of the two instances if there is a client already connected to the other with the same clientId.

**Comment by ctron** [comment]
The first issue already was tracked: https://issues.apache.org/jira/browse/ARTEMIS-1218
The second issue is now tracked at: https://issues.apache.org/jira/browse/ARTEMIS-1391

**Comment by ctron** [comment]
The fix for both issues is currently tracked in apache/activemq-artemis#1539

**Comment by MMaiero** [comment]
The issue seems to be closed in the official Artemis repo.
We should try to see if there is a possibility to move a newest version of Artemis in order to close this issue.
