### ISSUE TITLE
[Kura 3.1.0 QA] TiSensorTag driver - exception reading values

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1704]
Exception occurs during reading of channel data in DRIVERS-BLE-002 test:

```
ERROR o.e.k.i.d.b.s.TiSensorTag - Luxometer read failed
org.eclipse.kura.KuraBluetoothIOException: Error during BLE IO activity.
        at org.eclipse.kura.internal.ble.BluetoothLeGattCharacteristicImpl.readValue(BluetoothLeGattCharacteristicImpl.java:71)
        at org.eclipse.kura.internal.driver.ble.sensortag.TiSensorTag.readLight(TiSensorTag.java:1230)
        at org.eclipse.kura.internal.driver.ble.sensortag.SensorTagDriver.runReadRequest(SensorTagDriver.java:299)
        at org.eclipse.kura.internal.driver.ble.sensortag.SensorTagDriver.access$2(SensorTagDriver.java:256)
        at org.eclipse.kura.internal.driver.ble.sensortag.SensorTagDriver$SensorTagPreparedRead.execute(SensorTagDriver.java:483)
        at org.eclipse.kura.asset.provider.BaseAsset.readAllChannels(BaseAsset.java:492)
        at org.eclipse.kura.internal.rest.asset.AssetRestService.read(AssetRestService.java:85)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)
        at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1221)
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:132)
        at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:100)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:310)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
Caused by: tinyb.BluetoothException: GDBus.Error:org.bluez.Error.Failed: Not connected
        at tinyb.BluetoothGattCharacteristic.readValue(Native Method)
        at org.eclipse.kura.internal.ble.BluetoothLeGattCharacteristicImpl.readValue(BluetoothLeGattCharacteristicImpl.java:69)
        ... 61 more
```

Setup:

![image](https://user-images.githubusercontent.com/22816717/30958540-ced23c8e-a43d-11e7-9e18-0875268d6759.png)

org.eclipse.kura.example.ble.tisensortag.tinyb, in contrast, works.

Kura 3.1.0 RC b40 on RPi3

**Comment by cdealti** [comment]
@pierantoniomerlino can you please take a look

**Comment by MMaiero** [comment]
I've tried to replicate in my environment but everything worked:

<img width="1000" alt="schermata 2017-10-02 alle 11 07 19" src="https://user-images.githubusercontent.com/10448126/31070802-fdc7d022-a761-11e7-949f-30ea5e1e7004.png">
<img width="771" alt="schermata 2017-10-02 alle 11 08 37" src="https://user-images.githubusercontent.com/10448126/31070816-0b873c84-a762-11e7-9a6b-6305bbe70c89.png">

Maybe the sensortag firmware version can cause the issue?

**Comment by markoer** [comment]
Looks like 1.20 is installed.

**Comment by markoer** [comment]
I upgraded to 1.40 and now it works. But the 'old' BLE example doesn't seem to work properly - it only prints out a few values, and even those are constant.
I could try with some other versions, too, if you have the firmware files somewhere. It might be interesting to know the version in which it starts/stops working.

**Comment by pierantoniomerlino** [comment]
Hi Marko,

yes, the old BLE example doesn’t work with new the firmware. The old example reads the values using the “handles” instead UUIDs and these changed in the new firmware. The Tinyb example, instead, uses only UUIDs and they are constant. I suppose that the old example works with <=1.2.0 firmware version.

Thank you.
Pier

On 04 Oct 2017, at 11:10, markoer <notifications@github.com<mailto:notifications@github.com>> wrote:


I upgraded to 1.40 and now it works. But the 'old' BLE example doesn't seem to work properly - it only prints out a few values, and even those are constant.
I could try with some other versions, too, if you have the firmware files somewhere. It might be interesting to know the version in which it starts/stops working.

**Comment by markoer** [comment]
OK. Then the issue is resolved, IMO.
Closing.
