### ISSUE TITLE
[Kura 3.1.0 QA] SensorTagDriver NPE if wrong address

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1720]
SensorTagDriver throws NPE that propagates to REST service in case channel's `sensortag.address` is incorrect:

```
Caused by: java.lang.NullPointerException
        at org.eclipse.kura.internal.driver.ble.sensortag.SensorTagDriver.getSensorTag(SensorTagDriver.java:330)
        at org.eclipse.kura.internal.driver.ble.sensortag.SensorTagDriver.runReadRequest(SensorTagDriver.java:258)
        at org.eclipse.kura.internal.driver.ble.sensortag.SensorTagDriver.access$2(SensorTagDriver.java:257)
        at org.eclipse.kura.internal.driver.ble.sensortag.SensorTagDriver$SensorTagPreparedRead.execute(SensorTagDriver.java:474)
        at org.eclipse.kura.asset.provider.BaseAsset.readAllChannels(BaseAsset.java:492)
        at org.eclipse.kura.internal.rest.asset.AssetRestService.read(AssetRestService.java:85)
```

So the result is a rather uninformative
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /services/assets/stass/_read. Reason:
<pre>    javax.servlet.ServletException: java.lang.NullPointerException</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.9.v20160517</a><hr/>
</body>
</html>
```

I recommend to maybe hide this exception and suggest to check e.g. the MAC.

Kura 3.1.0 RC b41 on RPi3

**Comment by markoer** [comment]
Verified in 3.1.0 RC b42.
