### ISSUE TITLE
[Test] Position service test failure in Travis

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1742]
It happens that a position service test fails in Travis causing the build to fail. If the rebuild is restarted it is likely that the build succeeds.
Following the test log:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.kura.linux.position.GpsDeviceTest
Oct 18, 2017 1:41:47 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate parseNmeaSentence
SEVERE: NMEA checksum not valid
Oct 18, 2017 1:41:47 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate parseNmeaSentence
WARNING: Invalid NMEA sentence: $HNINV,invalid,*26

Oct 18, 2017 1:41:47 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate task cancelled? = true
Oct 18, 2017 1:41:47 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate Thread terminated? - true
Oct 18, 2017 1:41:47 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate doPollWork
SEVERE: Exception in gps read - {}
java.io.IOException: test
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate.doPollWork(GpsDevice.java:309)
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate$1.run(GpsDevice.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Oct 18, 2017 1:41:48 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate$1 run
INFO: The doPollWork() method returned 'false' - disconnecting ...
Oct 18, 2017 1:41:48 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate task cancelled? = true
Oct 18, 2017 1:41:48 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
WARNING: Interrupted - {}
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1475)
	at java.util.concurrent.Executors$DelegatedExecutorService.awaitTermination(Executors.java:675)
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate.disconnect(GpsDevice.java:270)
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate$1.run(GpsDevice.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Oct 18, 2017 1:41:48 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate Thread terminated? - false
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate task cancelled? = true
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate Thread terminated? - true
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.117 sec
Running org.eclipse.kura.linux.position.NMEAParserTest
Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec
Running org.eclipse.kura.linux.position.PositionServiceTest
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.PositionServiceImpl updated
INFO: Updating... Done.
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.PositionServiceImpl activate
INFO: Activating... Done.
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate task cancelled? = true
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate Thread terminated? - true
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.PositionServiceImpl deactivate
INFO: PositionServiceImpl Thread terminated? - true
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.PositionServiceImpl deactivate
INFO: Deactivating... Done.
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.PositionServiceImpl updated
INFO: Updating... Done.
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.PositionServiceImpl activate
INFO: Activating... Done.
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.PositionServiceImpl configureGpsDevice
INFO: configureGpsDevice() :: disconnecting GPS device ...
Oct 18, 2017 1:41:50 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate task cancelled? = true
Oct 18, 2017 1:41:51 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate Thread terminated? - false
Oct 18, 2017 1:41:51 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate doPollWork
SEVERE: Exception in gps read - {}
java.lang.NullPointerException
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate.doPollWork(GpsDevice.java:309)
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate$1.run(GpsDevice.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Oct 18, 2017 1:41:51 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate doPollWork
WARNING: Interrupted - {}
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate.doPollWork(GpsDevice.java:313)
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate$1.run(GpsDevice.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Oct 18, 2017 1:41:51 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate$1 run
INFO: The doPollWork() method returned 'false' - disconnecting ...
Oct 18, 2017 1:41:51 PM org.eclipse.kura.linux.position.PositionServiceImpl configureGpsDevice
WARNING: GPS device is not present - waiting for it to be ready
Oct 18, 2017 1:41:51 PM org.eclipse.kura.linux.position.PositionServiceImpl deactivate
INFO: PositionServiceImpl Thread terminated? - true
Oct 18, 2017 1:41:51 PM org.eclipse.kura.linux.position.PositionServiceImpl deactivate
INFO: Deactivating... Done.
Oct 18, 2017 1:41:51 PM org.eclipse.kura.linux.position.PositionServiceImpl updated
INFO: Updating... Done.
Oct 18, 2017 1:41:51 PM org.eclipse.kura.linux.position.PositionServiceImpl activate
INFO: Activating... Done.
Oct 18, 2017 1:41:52 PM org.eclipse.kura.linux.position.PositionServiceImpl updated
INFO: Updating... Done.
Oct 18, 2017 1:41:52 PM org.eclipse.kura.linux.position.PositionServiceImpl activate
INFO: Activating... Done.
Oct 18, 2017 1:41:52 PM org.eclipse.kura.linux.position.PositionServiceImpl configureGpsDevice
INFO: configureGpsDevice() :: disconnecting GPS device ...
Oct 18, 2017 1:41:52 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate task cancelled? = true
Oct 18, 2017 1:41:52 PM org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate disconnect
INFO: disconnect() :: GpsSerialCommunicate Thread terminated? - true
Oct 18, 2017 1:41:52 PM org.eclipse.kura.linux.position.PositionServiceImpl configureGpsDevice
WARNING: GPS device is not present - waiting for it to be ready
Oct 18, 2017 1:41:52 PM org.eclipse.kura.linux.position.PositionServiceImpl updated
INFO: Updating... Done.
Oct 18, 2017 1:41:52 PM org.eclipse.kura.linux.position.PositionServiceImpl updated
INFO: Updating... Done.
Oct 18, 2017 1:41:52 PM org.eclipse.kura.linux.position.PositionServiceImpl activate
INFO: Activating... Done.
Oct 18, 2017 1:41:52 PM org.eclipse.kura.linux.position.PositionServiceImpl deactivate
INFO: PositionServiceImpl Thread terminated? - true
Oct 18, 2017 1:41:52 PM org.eclipse.kura.linux.position.PositionServiceImpl deactivate
INFO: Deactivating... Done.
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.3 sec <<< FAILURE!

Results :

Failed tests: 
  testActivateDeactivate(org.eclipse.kura.linux.position.PositionServiceTest): 
Wanted but not invoked:
eventAdmin.postEvent(<any>);
-> at org.eclipse.kura.linux.position.PositionServiceTest.testActivateDeactivate(PositionServiceTest.java:190)
Actually, there were zero interactions with this mock.

Tests run: 29, Failures: 1, Errors: 0, Skipped: 0

**Comment by MMaiero** [comment]
I believe we need to revamp this issue since it's few build in develop that are failing in travis for the same issue.

**Comment by MMaiero** [comment]
@markoer I'm closing this since the fix seems to work well
