### ISSUE TITLE
[GPS] position service: code review

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#181]
`org.eclipse.kura.linux.position.PositionServiceImpl` has become messy.
Its configuration suggests an exclusive access to a serial port (UART, USB-to-serial) providing the NMEA sentences. This works well with standalone GPS receivers (for example an Ublox GPS receiver).

In the course of time we had to support NMEA sentences provided by Telit modems which combine a modem and a GPS receiver in the same module.

In Kura modems are managed by the net admin bundle and the modem configuration and initialization happens there. Moreover the net admin may reset the modem if it stops responding or hangs.
Also, on some modems the same serial port is used for sending AT commands (by the net admin) and receiving the NMEA sentences (by the position service).

To cope with this some workarounds have been added to the position service implementation.
These are based on various OSGi events resulting in a messy design and unreliable operation.

P1: check reliable operation when GPS is provided by the modem and:
- The modem is reset by net admin
- Kura is restarted

Postponed:
- When Kura is restarted and GPS service was enabled, the network service can't communicate with the modem and reset it
- How to manage USB and built-in modem GPS device
- Modify GPS enable AT command
- Filter USB events
- Check the configuration passed to the bundle

**Comment by pierantoniomerlino** [comment]
P1: check reliable operation when GPS is provided by the modem and:

- [ ] The modem is reset by net admin
- [ ] Kura is restarted
Postponed:

- [ ] When Kura is restarted and GPS service was enabled, the network service can't communicate with the modem and reset it
- [ ] How to manage USB and built-in modem GPS device
- [ ] Modify GPS enable AT command
- [ ] Filter USB events
- [ ] Check the configuration passed to the bundle

**Comment by pierantoniomerlino** [comment]
Partially solved in #224

**Comment by pierantoniomerlino** [comment]
The configuration provided by the configurable component is relative to the USB GPS. When a modem GPS is enabled, the latter is used. When the modem GPS is disabled, the USB is used.

**Comment by cdealti** [comment]
@ibinshtok can you please review?

**Comment by ibinshtok** [comment]
@pierantoniomerlino , I am getting these exceptions when switching from modem GPS back to onboard GPS. This is on HE910 modem.
2016-06-08 14:31:24,336 [GpsSerialCommunicate] ERROR o.e.k.l.p.GpsDevice - Exception in gps read - {}
java.lang.NullPointerException
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate.doPollWork(GpsDevice.java:325)
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate$1.run(GpsDevice.java:261)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
2016-06-08 14:31:24,338 [GpsSerialCommunicate] WARN  o.e.k.l.p.GpsDevice - Interrupted - {}
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate.sleep(GpsDevice.java:361)
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate.doPollWork(GpsDevice.java:328)
	at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate$1.run(GpsDevice.java:261)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)

and swich doesn't work unless I reboot the unit.

**Comment by pierantoniomerlino** [comment]
Ok. I'll take a look at this. On which device did you see this exception?

**Comment by ibinshtok** [comment]
On HE910

**Comment by cdealti** [comment]
@ibinshtok any chance to review the PR and retest? I see potential benefits in having this merged.

**Comment by ibinshtok** [comment]
@cdealti, @pierantoniomerlino  sure, I'll review this. Is this a PR ##224, kura_gps branch?

**Comment by pierantoniomerlino** [comment]
@ibinshtok Yes!

**Comment by MMaiero** [comment]
@ibinshtok @pierantoniomerlino What we should do for this issue? Do you have a PR that solves it? Or we move it to 2.2.0?

**Comment by ibinshtok** [comment]
@MMaiero @pierantoniomerlino I think we should probably move it to 2.2.0

**Comment by pierantoniomerlino** [comment]
@ibinshtok @MMaiero I agree on postponing the issue.

**Comment by MMaiero** [comment]
Thank you guys, postponed to 2.2.0

**Comment by nicolatimeus** [comment]
A position service refactor has been performed in #2074.
#2086, #2088 and #2090 should improve situation for modem resets with GPS enabled.
If Kura is restarted with the modem GPS enabled, the modem will still be reset during startup. This should bring it back to a consistent state.

**Comment by nicolatimeus** [comment]
Closing, we can reopen if needed.
