### ISSUE TITLE
Failure to submit Wifi configuration when wifi password (PSK) ends with the $. 

### ISSUE THREAD

**Issue by ibinshtok** [eclipse/kura#1823]
WpaSupplicantConfigWriter.writeConfig fails when submitted PSK ends with the $.
Exception is below:
org.eclipse.kura.KuraException: An internal error occurred. 
        at org.eclipse.kura.KuraException.internalError(KuraException.java:120)
        at org.eclipse.kura.net.admin.visitor.linux.WpaSupplicantConfigWriter.writeAndMoveFile(WpaSupplicantConfigWriter.java:231)
        at org.eclipse.kura.net.admin.visitor.linux.WpaSupplicantConfigWriter.writeConfig(WpaSupplicantConfigWriter.java:168)
        at org.eclipse.kura.net.admin.visitor.linux.WpaSupplicantConfigWriter.visit(WpaSupplicantConfigWriter.java:81)
        at org.eclipse.kura.net.admin.visitor.linux.WifiConfigWriter.visit(WifiConfigWriter.java:64)
        at org.eclipse.kura.net.admin.visitor.linux.LinuxWriteVisitor.visit(LinuxWriteVisitor.java:47)
        at org.eclipse.kura.core.net.NetworkConfiguration.accept(NetworkConfiguration.java:154)
        at org.eclipse.kura.net.admin.NetworkConfigurationServiceImpl.updated(NetworkConfigurationServiceImpl.java:241)
        at org.eclipse.kura.net.admin.NetworkConfigurationServiceImpl.setNetworkConfiguration(NetworkConfigurationServiceImpl.java:206)
        at org.eclipse.kura.net.admin.NetworkAdminServiceImpl.submitNetworkConfiguration(NetworkAdminServiceImpl.java:1504)
        at org.eclipse.kura.net.admin.NetworkAdminServiceImpl.updateWifiInterfaceConfig(NetworkAdminServiceImpl.java:742)
        at org.eclipse.kura.web.server.GwtNetworkServiceImpl.updateNetInterfaceConfigurations(GwtNetworkServiceImpl.java:870)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.service(OsgiRemoteServiceServlet.java:41)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1221)
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:132)
        at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:100)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:310)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Illegal group reference: group index is missing
        at java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.util.regex.Matcher.replaceFirst(Unknown Source)
        at java.lang.String.replaceFirst(Unknown Source)
        at org.eclipse.kura.net.admin.visitor.linux.WpaSupplicantConfigWriter.updateWPA(WpaSupplicantConfigWriter.java:325)
        at org.eclipse.kura.net.admin.visitor.linux.WpaSupplicantConfigWriter.generateWpaSupplicantConf(WpaSupplicantConfigWriter.java:266)
        at org.eclipse.kura.net.admin.visitor.linux.WpaSupplicantConfigWriter.writeAndMoveFile(WpaSupplicantConfigWriter.java:226)
        ... 50 more

**Comment by MMaiero** [comment]
Closed as #1828 is now merged
