### ISSUE TITLE
[Test] Kura tests exception when executed with Java 8

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#183]
It seems that the tycho-surefire-plugin in version 0.20
fails to run when invoked with Java 8. Following the stack trace resulting when running the tests with Maven (3.0.5)

[INFO] --- tycho-surefire-plugin:0.20.0:test (default-test) @ org.eclipse.kura.core.test ---
[INFO] Expected eclipse log file: /Users/matteo.maiero/git_eclipse/kura/kura/org.eclipse.kura.core.test/target/work/data/.metadata/.log
[INFO] Command line:
	[/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=macosx, -Dosgi.ws=cocoa, -Dosgi.arch=x86_64, -javaagent:/Users/matteo.maiero/.m2/repository/org/jacoco/org.jacoco.agent/0.6.4.201312101107/org.jacoco.agent-0.6.4.201312101107-runtime.jar=destfile=/Users/matteo.maiero/git_eclipse/kura/kura/org.eclipse.kura.core.test/target/jacoco.exec, -DbuildingWithTycho=true, -Dosgi.locking=none, -Dequinox.ds.print=true, -Djava.io.tmpdir=/tmp, -Dorg.osgi.framework.storage=/tmp/osgi/framework_storage, -Dosgi.clean=true, -Dorg.eclipse.kura.mode=emulator, -Dkura.configuration=file:/Users/matteo.maiero/git_eclipse/kura/kura/org.eclipse.kura.core.test/../emulator/org.eclipse.kura.emulator/src/main/resources/kura.properties, -Ddpa.configuration=/tmp/kura/dpa.properties, -Dlog4j.configuration=file:/Users/matteo.maiero/git_eclipse/kura/kura/org.eclipse.kura.core.test/../emulator/org.eclipse.kura.emulator/src/main/resources/log4j.properties, -Dosgi.clean=true, -jar, /Users/matteo.maiero/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.3.0.v20120522-1813/org.eclipse.equinox.launcher-1.3.0.v20120522-1813.jar, -data, /Users/matteo.maiero/git_eclipse/kura/kura/org.eclipse.kura.core.test/target/work/data, -install, /Users/matteo.maiero/git_eclipse/kura/kura/org.eclipse.kura.core.test/target/work, -configuration, /Users/matteo.maiero/git_eclipse/kura/kura/org.eclipse.kura.core.test/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.headlesstest, -testproperties, /Users/matteo.maiero/git_eclipse/kura/kura/org.eclipse.kura.core.test/target/surefire.properties]
objc[65023]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_6effb9e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
	at org.jacoco.agent.rt.internal_6effb9e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:99)
	at org.jacoco.agent.rt.internal_6effb9e.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_6effb9e.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.lang.Class.getField(Class.java:1703)
	at org.jacoco.agent.rt.internal_6effb9e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:136)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed

**Comment by amitjoy** [comment]
#336 solves this issue.
