### ISSUE TITLE
SensorTagDriver sometimes fails to connect to the SensorTag

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#1853]
The SensorTag Driver sometimes fails to connect to the SensorTag causing the device to be lock by the connection attempts. The kura.log file is filled by Timeout exception during connection. 
This issue is partially fixed by #1852, but it needs more investigation.

To reproduce the issue, create a Wire graph with a Timer, an Asset binded to the SensorTagDriver and a Logger. Start it and check the logs.

**Comment by pierantoniomerlino** [comment]
The issue seems to be caused by an error during disconnection. If the device is not properly disconnected, bluez/tinyb keep it connected. So, further attempts to connection fail. A simple workaround is to manually disconnect it:

`bluetoothctl`
`disconnect <address>`
`exit`

**Comment by pierantoniomerlino** [comment]
Both the SensorTag example and Driver had been updated here [1]. The modifications increase the reliability of the code, but there are still some connection problems.

Using the ```org.eclipse.kura.example.ble.sensortag.tinyb```, there is a recurring error on kura.log:

```
2018-04-03 14:23:10,154 [pool-27-thread-1] INFO  o.e.k.e.b.t.t.BluetoothLe - Connecting to TiSensorTag B0:B4:48:BD:0D:03...
2018-04-03 14:23:16,496 [pool-27-thread-1] ERROR o.e.k.e.b.t.t.TiSensorTag - Failed to get GATT service
org.eclipse.kura.KuraBluetoothResourceNotFoundException: BLE resource not found.
	at org.eclipse.kura.internal.ble.BluetoothLeDeviceImpl.findService(BluetoothLeDeviceImpl.java:46)
	at org.eclipse.kura.example.ble.tisensortag.tinyb.TiSensorTag.getGattResources(TiSensorTag.java:1442)
	at org.eclipse.kura.example.ble.tisensortag.tinyb.TiSensorTag.init(TiSensorTag.java:94)
	at org.eclipse.kura.example.ble.tisensortag.tinyb.BluetoothLe.readSensorTags(BluetoothLe.java:261)
	at org.eclipse.kura.example.ble.tisensortag.tinyb.BluetoothLe.performScan(BluetoothLe.java:196)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-03 14:23:19,129 [pool-27-thread-1] ERROR o.e.k.e.b.t.t.BluetoothLe - Cannot connect/disconnect to TI SensorTag B0:B4:48:BD:0D:03.
```

It seems that the device successfully connect with SensorTag, but it fails to retrieve the exposed GATT Services and it is forced to disconnect. However, after several attempts the example can get the services and the errors disappear also after reboots.
This is due to the fact that Bluez keep a cache containing info about connected devices. When the example re-connects, Bluez fetches the information from the cache. To reproduce the issue, it is sufficient to delete the ```<device_address>``` folder under ```/var/lib/bluetooth/<adapter_address>``` and reboot.

[1] https://github.com/eclipse/kura/commit/56b081d548fd5bc7e473047265d805227ddf76b7#diff-69ff6e137d85850038cdbe97888402db

**Comment by pierantoniomerlino** [comment]
A possible solution is to increase the timeout for retrieving GATT resources from a BLE device or make it configurable (but a change on the API is needed). In the current implementation of ```BluetoothLeAdapterImpl```, ```BluetoothLeDeviceImpl```, ```BluetoothLeGattCharacteristicImpl``` and ```BluetoothLeGattServiceImpl```, a fixed timeout of 5 seconds is set. Increase it to 30 seconds will improve the reliability:

```
private static final Duration TIMEOUT = Duration.ofSeconds(30);
```

A better solution is to make the timeout configurable, i.e.:

```
public BluetoothLeGattService findService(UUID uuid, Duration duration) throws KuraBluetoothResourceNotFoundException {
```

**Comment by pierantoniomerlino** [comment]
The #2030 introduces the modifications suggested in these comments. However, there are still some problems related to connection that can cause in some situation a JVM crash or a disconnection error.
It should be investigated if they are caused by the type of device (SensorTag) or by the underlying library (TinyB) or something else.

**Comment by MMaiero** [comment]
@pierantoniomerlino Maybe we can close this, since it seems mitigated now and open another issue for the JVM crash?

**Comment by pierantoniomerlino** [comment]
Ok. The JVM crash issue should be investigated anyway...
