### ISSUE TITLE
A generic unrecoverable error happened. Please refer to the device log. -- when open System->Status

### ISSUE THREAD

**Issue by hyperion-thou** [eclipse/kura#1855]
2017-12-25 20:52:36,567 [qtp12354839-72] WARN  o.e.k.w.s.GwtNetworkServiceImpl - Get network status failed
org.eclipse.kura.web.shared.GwtKuraException: An internal error occurred. {0}
	at org.eclipse.kura.web.shared.GwtKuraException.internalError(GwtKuraException.java:99)
	at org.eclipse.kura.web.server.util.KuraExceptionHandler.handle(KuraExceptionHandler.java:27)
	at org.eclipse.kura.web.server.GwtNetworkServiceImpl.privateFindNetInterfaceConfigurations(GwtNetworkServiceImpl.java:696)
	at org.eclipse.kura.web.server.GwtNetworkServiceImpl.findNetInterfaceConfigurations(GwtNetworkServiceImpl.java:111)
	at org.eclipse.kura.web.server.GwtStatusServiceImpl.getNetworkStatus(GwtStatusServiceImpl.java:224)
	at org.eclipse.kura.web.server.GwtStatusServiceImpl.getDeviceConfig(GwtStatusServiceImpl.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.service(OsgiRemoteServiceServlet.java:41)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1221)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:132)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:100)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:310)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.kura.KuraException: An internal error occurred. {0}
	at org.eclipse.kura.net.admin.NetworkAdminServiceImpl.getNetworkInterfaceConfigs(NetworkAdminServiceImpl.java:222)
	at org.eclipse.kura.web.server.GwtNetworkServiceImpl.privateFindNetInterfaceConfigurations(GwtNetworkServiceImpl.java:163)
	... 43 more
**Caused by: org.eclipse.kura.KuraException: An internal error occurred. malformatted config file: /etc/network/interfaces must contain NETMASK and/or PREFIX**
	at org.eclipse.kura.net.admin.visitor.linux.IfcfgConfigReader.getConfig(IfcfgConfigReader.java:220)
	at org.eclipse.kura.net.admin.visitor.linux.IfcfgConfigReader.visit(IfcfgConfigReader.java:74)
	at org.eclipse.kura.net.admin.visitor.linux.LinuxReadVisitor.visit(LinuxReadVisitor.java:47)
	at org.eclipse.kura.core.net.NetworkConfiguration.accept(NetworkConfiguration.java:154)
	at org.eclipse.kura.net.admin.NetworkConfigurationServiceImpl.getNetworkConfiguration(NetworkConfigurationServiceImpl.java:362)
	at org.eclipse.kura.net.admin.NetworkAdminServiceImpl.getNetworkInterfaceConfigs(NetworkAdminServiceImpl.java:220)
	... 44 more

my /etc/network/interfaces like this:
# /etc/network/interfaces -- configuration file for ifup(8), ifdown(8)

# The loopback interface
auto lo
iface lo inet loopback

auto eth0
iface etho inet dhcp

# Wired or wireless interfaces
allow-hotplug wlan0
auto wlan0
iface wlan0 inet dhcp
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

which based on RaspberryPi 3.
please check and confirm, thanks all of you.

**Comment by MMaiero** [comment]
@markoer Could you please do a triage of this issue?

**Comment by markoer** [comment]
At first sight it's hard to see, but a typo is the reason for this:
```
auto eth0
iface etho inet dhcp
```
should be 
```
auto eth0
iface eth0 inet dhcp
```

Note the change from 'o' to '0' on line 2. Just update that and you're good to go.

**Comment by MMaiero** [comment]
@qinghaibo Any update on this? Can this be closed?
