### ISSUE TITLE
Package unistall error

### ISSUE THREAD

**Issue by darionct** [eclipse/kura#1886]
If package is installed form the EC web console, when "uninstall" is attempted from Kura, error message pops up and the following exception is logged:
2018-01-31 09:18:22,495 [DeploymentAgent:Uninstall] ERROR o.e.k.d.a.i.DeploymentAgent - Exception uninstalling package org.eclipse.kura.demo.heater
```
java.net.MalformedURLException
	at java.net.URL.<init>(URL.java:627)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.uninstaller(DeploymentAgent.java:342)
	at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.lambda$1(DeploymentAgent.java:169)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:532)
	... 9 more
2018-01-31 09:18:22,502 [DeploymentAgent:Uninstall] INFO  o.e.k.d.a.i.DeploymentAgent - Posting 
UNINSTALLED event for package org.eclipse.kura.demo.heater: unsuccessful
```

**Comment by MMaiero** [comment]
@darionct Could you please verify if it works for you?

**Comment by darionct** [comment]
Verified and confirmed on Raspberry Pi and BeagleBone black.
