### ISSUE TITLE
Search Domains Are Not Supported

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1993]
While testing NET-ETH0-003 on Fedora I ran into the follow error when applying the configuration:

![image](https://user-images.githubusercontent.com/202474/38080865-e86adcf2-3342-11e8-8a8f-74e3aa119375.png)

Looking at the exception I do think that the search domain field validation is broken:

~~~
2018-03-29 11:16:51,185 [qtp23807444-83] WARN  o.e.k.w.s.GwtNetworkServiceImpl - Failed
java.net.UnknownHostException: muc.redhat.com: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at java.net.InetAddress.getByName(InetAddress.java:1076)
        at org.eclipse.kura.net.IPAddress.parseHostAddress(IPAddress.java:81)
        at org.eclipse.kura.web.server.GwtNetworkServiceImpl.updateNetInterfaceConfigurations(GwtNetworkServiceImpl.java:803)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.service(OsgiRemoteServiceServlet.java:41)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1223)
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:148)
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:131)
        at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:74)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:284)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)

~~~

The entered information is actually part of hostname, not a hostname itself and thus cannot necessarily be looked up.

**Comment by MMaiero** [comment]
@ibinshtok Could you please triage this?

**Comment by ibinshtok** [comment]
@MMaiero yes, I recreated this exception if "Search Domain" is a name that can't be resolved (i.e. google, instead of google.com or IP address).

**Comment by cdealti** [comment]
Please note that search domains were broken, see #923.
NET-ETH0-003 does not specify to set Search Domains.

Should we just disable or remove the field from the Web UI?

**Comment by ctron** [comment]
> NET-ETH0-003 does not specify to set Search Domains.

Well the tests asks you to add set all other kinds of settings from your local settings. This is one of them. So maybe adding that field to the test explicitly makes sense.

> Should we just disable or remove the field from the Web UI?

I think fixing the issue would be the appropriate action.

**Comment by cdealti** [comment]
@ibinshtok are you confident in a proper fix to this issue and to #923?
I personally think this is not so critical (never had customers complaining about it) and can be postponed.
However I'll let @dwoodard1 decide.

**Comment by cdealti** [comment]
As agreed in the weekly call, let's start removing the `Search Domains` field from the Admin UI.
@ibinshtok can you do that?

**Comment by MMaiero** [comment]
Temporary covered by PR #2023.

Let's keep this issue open in order to provide a proper fix in one of the next releases.
