### ISSUE TITLE
DEN-DEPLOY-005 failed

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2002]
Undeploying the DP does remove the package and the created service. But it doesn't stop the publishing:

![image](https://user-images.githubusercontent.com/202474/38246456-26f6408a-3742-11e8-975f-b151970dbae0.png)

The log is flooded with the following message:

~~~
2018-04-03 13:24:23,238 [pool-12-thread-1] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic :#account-name/#client-id/EXAMPLE_PUBLISHER/data/metrics, priority: 5
2018-04-03 13:24:23,239 [pool-12-thread-1] ERROR o.e.k.c.d.s.DbDataStore - Store capacity exceeded
2018-04-03 13:24:23,239 [pool-12-thread-1] ERROR o.e.k.e.p.ExamplePublisher - Cannot publish topic: data/metrics
org.eclipse.kura.KuraStoreCapacityReachedException: "Error performing operation on store. Store capacity exceeded"
	at org.eclipse.kura.core.data.store.DbDataStore.store(DbDataStore.java:257)
	at org.eclipse.kura.core.data.DataServiceImpl.publish(DataServiceImpl.java:533)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:139)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:125)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:111)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:105)
	at org.eclipse.kura.example.publisher.ExamplePublisher.doPublish(ExamplePublisher.java:317)
	at org.eclipse.kura.example.publisher.ExamplePublisher.access$5(ExamplePublisher.java:276)
	at org.eclipse.kura.example.publisher.ExamplePublisher$1.run(ExamplePublisher.java:268)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
~~~

The full Kura logs are here: [kura-logs-20180403-130413.tar.gz](https://github.com/eclipse/kura/files/1871275/kura-logs-20180403-130413.tar.gz)

**Comment by cdealti** [comment]
I believe @markoer observed this behavior but it's not mentioned in the QA spreadsheet of the RPI 3 on Raspian.

I also think that this started after `ExamplePublisher` has been converted to a factory DS.

@markoer can you confirm?

**Comment by markoer** [comment]
I suppose #2025 should take care of this issue, too. There should be no rogue ExamplePublisher threads running after that PR is applied.
