### ISSUE TITLE
Something seems odd with the internal database/buffer

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2006]
While testing Kura 3.2 RC, I saw a strange behavior of the internal Kura buffer. May that is "as designed", but it still seems odd to me.

Using the example publisher and having a successful connection to "iot.eclipse.org" the message buffer was full at some point. Messages got published successfully and I could see them in the MQTT tool I was using. Also were those the most recent messages, not some old messages. Changes from the UI were reflected in the received messages seconds after. However at some point the messages just stopped and the log filled with messages of a full buffer. Until the "house keeper" job ran and then messages started flowing again:

~~~
2018-04-03 14:15:00,837 [pool-24-thread-1] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic :#account-name/#client-id/EXAMPLE_PUBLISHER/data/metrics, priority: 5
2018-04-03 14:15:00,838 [pool-24-thread-1] ERROR o.e.k.c.d.s.DbDataStore - Store capacity exceeded
2018-04-03 14:15:00,839 [pool-24-thread-1] ERROR o.e.k.e.p.ExamplePublisher - Cannot publish topic: data/metrics
org.eclipse.kura.KuraStoreCapacityReachedException: "Error performing operation on store. Store capacity exceeded"
	at org.eclipse.kura.core.data.store.DbDataStore.store(DbDataStore.java:257)
	at org.eclipse.kura.core.data.DataServiceImpl.publish(DataServiceImpl.java:533)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:139)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:125)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:111)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:105)
	at org.eclipse.kura.example.publisher.ExamplePublisher.doPublish(ExamplePublisher.java:317)
	at org.eclipse.kura.example.publisher.ExamplePublisher.access$5(ExamplePublisher.java:276)
	at org.eclipse.kura.example.publisher.ExamplePublisher$1.run(ExamplePublisher.java:268)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-04-03 14:15:01,191 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask started.
2018-04-03 14:15:01,192 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask: Delete confirmed messages...
2018-04-03 14:15:02,254 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask ended.
2018-04-03 14:15:02,337 [pool-24-thread-1] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic :#account-name/#client-id/EXAMPLE_PUBLISHER/data/metrics, priority: 5
2018-04-03 14:15:02,346 [pool-24-thread-1] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic :#account-name/#client-id/EXAMPLE_PUBLISHER/data/metrics, priority: 5
2018-04-03 14:15:02,347 [pool-24-thread-1] INFO  o.e.k.e.p.ExamplePublisher - Published to data/metrics message: org.eclipse.kura.message.KuraPayload@127ecbb with ID: 1577
2018-04-03 14:15:02,358 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: account-name/B8:27:EB:97:D8:D5/EXAMPLE_PUBLISHER/data/metrics with QoS: 0

~~~

**Comment by cdealti** [comment]
> While testing Kura 3.2 RC, I saw a strange behavior of the internal Kura buffer. May that is "as designed", but it still seems odd to me.

What you describe is the expected behavior and how it has worked since the beginning.

Messages are not deleted from the message store as soon as they have been sent or delivered to the broker, based on the publish QoS, but only when the house keeper task runs.

The store message capacity, the house keeper interval and the message purge age can be tuned from the configuration of the DataService.

I believe that people involved in QA, and in general those working daily with Kura, know how to prevent this from happening ;)

**Comment by ctron** [comment]
It is "works as designed".
