### ISSUE TITLE
[PositionService] Investigate NMEA sentence parsing errors

### ISSUE THREAD

**Issue by nicolatimeus** [eclipse/kura#2165]
Using Kura 3.2.0 PositionService with the U-Blox NEO-M8U GPS device, sometimes parsing errors like this occur while parsing NMEA sentences:

```
2018-06-21 23:51:53,738 [GpsSerialCommunicate] ERROR o.e.k.l.p.GpsDevice - Exception in parseNmeaSentence - {}
java.lang.NumberFormatException: For input string: "47$GPGSV,3,2,12,21,27,252,27,25,50,200,30,26,20,317,41,29,73,326,41*75"
                at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
                at java.lang.Integer.parseInt(Integer.java:580)
                at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate.NmeaCksum(GpsDevice.java:480)
                at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate.parseNmeaSentence(GpsDevice.java:358)
                at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate.doPollWork(GpsDevice.java:331)
                at org.eclipse.kura.linux.position.GpsDevice$SerialCommunicate$1.run(GpsDevice.java:243)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
```

Moreover, enabling debug for GPS device, it appears that the parser sometimes encounters lines like the following:

```
GPS RAW: $GPGSV,3,1,12,02,28,063,38,04,,,40,05,52,080,28,12,18,166,20*47$GPGSV,3,2,12,21,27,252,27,25,50,200,30,26,20,317,41,29,73,326,41*75
```

which seem to contain two NMEA sentences on the same line.

The parsing errors happen occasionally, and do not compromise PositionService operation.
It should be investigated whether this is a GPS device fw issue or if it is caused by a Kura bug in parsing/reading serial port.

**Comment by cdealti** [comment]
The issue happens also at the system level and is not related to Kura.
