### ISSUE TITLE
Azure IOT connection from KURA_3.1.0

### ISSUE THREAD

**Issue by Amar82** [eclipse/kura#2170]
I went through the cases...seems 
I am not able to create the key store 
 /opt/eclipse/kura/security/cacerts.ks

how to get this... who will issue.. how to generate the .ks file ?

=====
I m connecting to Azure IOT

**Comment by Amar82** [comment]
I have created the keystore using keytool command, 
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 3 entries

**ssl-azurecert, Jul 29, 2018, trustedCertEntry, 
Certificate fingerprint (SHA1): 95:B4:61:DF:90:D9:D7:1D:15:22:D8:DB:2E:F1:7D:BC:F4:BB:41:D2**
mykey, Jul 29, 2018, PrivateKeyEntry, 
Certificate fingerprint (SHA1): 7D:D6:1C:77:AA:3F:55:FD:4A:1B:29:D3:D1:79:91:3E:2E:E7:89:36
ca-11591687389060913796532298097930387285, Jul 29, 2018, trustedCertEntry, 
Certificate fingerprint (SHA1): 41:7E:22:50:37:FB:FA:A4:F9:57:61:D5:AE:72:9E:1A:EA:7E:3A:42

but still Kura is not getting connecting. 

can you please interprete the logs, please help ,,thank you in advance....

here is the Log from Kura.log:
<<<<
2018-07-29 22:39:34,778 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - Creating a new client instance
2018-07-29 22:39:34,778 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - Using memory persistence for in-flight messages
2018-07-29 22:39:34,779 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - # ------------------------------------------------------------
2018-07-29 22:39:34,780 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connection Properties
2018-07-29 22:39:34,780 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  broker    = ssl://IOTHub-Amar.azure-devices.net:8883
2018-07-29 22:39:34,781 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  clientId  = AmarDevice
2018-07-29 22:39:34,781 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  username  = IOTHub-Amar.azure-devices.net/AmarDevice
2018-07-29 22:39:34,781 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  password  = XXXXXXXXXXXXXX
2018-07-29 22:39:34,782 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  keepAlive = 30
2018-07-29 22:39:34,782 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  timeout   = 10
2018-07-29 22:39:34,782 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  cleanSession    = true
2018-07-29 22:39:34,782 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  MQTT version    = 3.1.1
2018-07-29 22:39:34,783 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willDestination = devices/AmarDevice/messages/events/LWT
2018-07-29 22:39:34,784 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willMessage     = 
2018-07-29 22:39:34,784 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #
2018-07-29 22:39:34,785 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connecting...
2018-07-29 22:39:34,785 [pool-11-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED fast blinking
2018-07-29 22:39:38,962 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2018-07-29 22:39:38,963 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (658)
2018-07-29 22:39:38,964 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2018-07-29 22:39:38,965 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (659)
2018-07-29 22:39:38,966 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2018-07-29 22:39:38,966 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (660)
2018-07-29 22:39:38,967 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2018-07-29 22:39:38,968 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (661)
2018-07-29 22:39:38,969 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2018-07-29 22:39:43,940 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (662)
2018-07-29 22:39:43,941 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2018-07-29 22:39:48,940 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (663)
2018-07-29 22:39:48,949 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2018-07-29 22:39:53,940 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (664)
2018-07-29 22:39:54,809 [MQTT Con: AmarDevice] INFO  o.e.k.c.s.SSLSocketFactoryWrapper - SSL Endpoint Identification enabled.
2018-07-29 22:39:54,812 [qtp28068530-295] WARN  o.e.k.c.d.t.m.MqttDataTransport - xxxxx  Connect failed. Forcing disconnect. xxxxx {}
MqttException (0) - java.net.UnknownHostException: IOTHub-Amar.azure-devices.net
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: IOTHub-Amar.azure-devices.net
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	... 1 more
2018-07-29 22:39:54,817 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - Closing client...
2018-07-29 22:39:54,818 [qtp28068530-295] INFO  o.e.k.c.d.t.m.MqttDataTransport - Closed
2018-07-29 22:39:54,818 [pool-11-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED off
2018-07-29 22:39:54,819 [qtp28068530-295] WARN  o.e.k.w.s.GwtNetworkServiceImpl - Error connecting
org.eclipse.kura.KuraConnectException: "Connection failed. Cannot connect"
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.connect(MqttDataTransport.java:333)
	at org.eclipse.kura.core.data.DataServiceImpl.connect(DataServiceImpl.java:493)
	at org.eclipse.kura.web.server.GwtStatusServiceImpl.connectDataService(GwtStatusServiceImpl.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.service(OsgiRemoteServiceServlet.java:41)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1221)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:132)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:100)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:310)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: MqttException (0) - java.net.UnknownHostException: IOTHub-Amar.azure-devices.net
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
	... 1 more
Caused by: java.net.UnknownHostException: IOTHub-Amar.azure-devices.net
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	... 1 more

**Comment by MMaiero** [comment]
Hi, I believe that the most meaningful part of the exception is this:
`MqttException (0) - java.net.UnknownHostException: IOTHub-Amar.azure-devices.net`

Are you able, from your device, to ping outside your network?

Best regards,
Matteo

**Comment by Amar82** [comment]
Matteo : Are you able, from your device, to ping outside your network? 
Me : NO... :( i checked after u told .. 
ping -c 1 google.com
ping: unknown host google.com
pi@raspberrypi:~ $ sudo wget https://github.com/Azure-Samples/azure-iot-samples-node/archive/master.zip
converted 'https://github.com/Azure-Samples/azure-iot-samples-node/archive/master.zip' (ANSI_X3.4-1968) -> 'https://github.com/Azure-Samples/azure-iot-samples-node/archive/master.zip' (UTF-8)
--2018-07-31 08:52:37--  https://github.com/Azure-Samples/azure-iot-samples-node/archive/master.zip
Resolving github.com (github.com)... failed: Name or service not known.
wget: unable to resolve host address 'github.com'.
======
But why ??
here are my Kura settings : 
wlan0:-  
Subnet Mask:    
 Mode: LAN   
 IP Acquisition: DHCP   
 Router Mode:     Wireless Mode:Access Point   
 SSID: kura_gateway_B8:27:EB:52:3D:F6
-- | --
eth0 : 192.168.0.8    
Subnet Mask: 255.255.255.0  
  Mode: WAN   
 IP Acquisition: DHCP   
 Router Mode:
-- | --

is this correct ?/

**Comment by MMaiero** [comment]
Hi,
the configuration seems correct but I don't know the details of your setup. From what I see from the configuration, you are expecting to access internet using the eth0 port.

**Comment by Amar82** [comment]
Yes ,true !

And WiFi as access point...

But the device is not connecting to Internet....The ethernet is connected
to router as well

But don't know why it's not connecting to Internet.
Regards
Amar

**Comment by MMaiero** [comment]
Did you solve your networking issues?
Can this issue be closed now?

Thanks.
Best regards,
Matteo

**Comment by Amar82** [comment]
No,
I am still working on this...
Please allow me this weekend.
Regards
Amar

**Comment by Amar82** [comment]
Hi Matteo,

even while connecting to eclipse mqtt sandbox, it is failing to connect;;; same unknown host. My network is connecting to internet...( as I am updating this issue web page )...here is the kura log:

======
Caused by: MqttException (0) - java.net.UnknownHostException: iot.eclipse.org
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
	... 1 more
Caused by: java.net.UnknownHostException: iot.eclipse.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	... 1 more
2018-08-07 07:47:50,508 [WifiMonitor Thread] INFO  o.e.k.l.n.w.HostapdManager - starting hostapd for the wlan0 interface --> hostapd -B /etc/hostapd-wlan0.conf
2018-08-07 07:47:50,508 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: hostapd -B /etc/hostapd-wlan0.conf
2018-08-07 07:47:50,720 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - hostapd -B /etc/hostapd-wlan0.conf returned with exit value:0
2018-08-07 07:47:51,721 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: dhclient -r wlan0

2018-08-07 07:47:51,860 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - dhclient -r wlan0
 returned with exit value:0
2018-08-07 07:47:51,927 [WifiMonitor Thread] INFO  o.e.k.l.n.d.DhcpClientManager - enable() :: disabling DHCP client for wlan0
2018-08-07 07:47:51,994 [WifiMonitor Thread] INFO  o.e.k.l.n.d.DhcpClientManager - disable() :: killing DHCP client for wlan0
2018-08-07 07:47:52,033 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - attempting to kill -9 pid 11221
2018-08-07 07:47:52,034 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: kill -9 11221
2018-08-07 07:47:52,040 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - kill -9 11221 returned with exit value:0
2018-08-07 07:47:52,040 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - successfully killed pid 11221
2018-08-07 07:47:52,041 [WifiMonitor Thread] INFO  o.e.k.l.n.d.DhcpClientManager - enable() :: Starting DHCP client for wlan0
2018-08-07 07:47:52,041 [WifiMonitor Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: dhclient -nw -lf /var/lib/dhclient/dhclient.wlan0.leases -pf /var/run/dhclient.wlan0.pid wlan0

=====

**Comment by Amar82** [comment]
here is the screen error 
![screen shot 2018-08-07 at 8 27 12 am](https://user-images.githubusercontent.com/22346098/43751790-fa2d4d9a-9a1b-11e8-9004-24a7eda5cd99.png)

====

Unknown.Pg(denali-0.js)
--
Unknown.Xg(denali-0.js)
Unknown.new Drc(denali-0.js)
Unknown.Irc(denali-0.js)
Unknown.qgb(denali-0.js)
Unknown.mgb(denali-0.js)
Unknown.Keb(denali-0.js)
Unknown.rfb(denali-0.js)
Unknown.Pr(denali-0.js)
Unknown.as(denali-0.js)
Unknown.eval(denali-0.js)
Unknown.Yh(denali-0.js)
Unknown._h(denali-0.js)
Unknown.eval(denali-0.js)

**Comment by MMaiero** [comment]
Hi,
the real fact is that you seem not to be able to reach internet also directly from linux.
This means that the gateway network configuration is not correct.
I would suggest to check the DNS server configuration and see if able to ping an ip first and than try to see if dns resolution works.
If all succeeds, than Kura should be able to connect to the selected endpoint.

Best regards,
Matteo

**Comment by Amar82** [comment]
Hi Matteo, 
Thank you for your input; it really helped.
"I would suggest to check the DNS server configuration and see if able to ping an ip first and than try to see if dns resolution works."

I changed the DNS setting , as it was for the router, and it worked.

I am closing the case.
