### ISSUE TITLE
Adding new cloud connection does not work

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2371]
**Describe the bug**
Creating a new cloud connection doesn't work. There also seems to be no more default connection.

**To Reproduce**
1. Click on "New connection"
1. Enter valid data
1. Press "Save"
1. Table reloads, nothing is in there
1. Manually reloading still shows an empty table

**Expected behavior**
The connection appears and can be configured.

**Logs**

~~~
2019-02-05T13:09:36,618 [ConfigurationListener Event Queue] ERROR o.e.k.c.d.t.m.MqttDataTransport - Invalid configuration
2019-02-05T13:09:36,618 [ConfigurationListener Event Queue] ERROR o.e.k.c.d.t.m.MqttDataTransport - Invalid client configuration. Service will not be able to connect until the configuration is updated
java.lang.IllegalStateException: Invalid MQTT client configuration
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.buildConfiguration(MqttDataTransport.java:806) ~[org.eclipse.kura.core_1.0.400.jar:?]
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.activate(MqttDataTransport.java:195) [org.eclipse.kura.core_1.0.400.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.apache.felix.scr.impl.inject.BaseMethod.invokeMethod(BaseMethod.java:229) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.inject.BaseMethod.access$500(BaseMethod.java:39) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.inject.BaseMethod$Resolved.invoke(BaseMethod.java:650) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.inject.BaseMethod.invoke(BaseMethod.java:506) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.inject.ActivateMethod.invoke(ActivateMethod.java:307) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.inject.ActivateMethod.invoke(ActivateMethod.java:299) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:298) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:109) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:906) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:879) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:508) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:624) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.osgi.util.tracker.ServiceTracker.addingService(ServiceTracker.java:414) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:920) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) [org.eclipse.osgi_3.12.50.v20170928-1321.jar:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:887) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:874) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:941) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:675) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:430) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:431) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:284) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$1.configurationEvent(RegionConfigurationSupport.java:89) [org.apache.felix.scr_2.0.10.v20170501-2007.jar:?]
	at org.eclipse.equinox.internal.cm.EventDispatcher$1.run(EventDispatcher.java:89) [org.eclipse.equinox.cm_1.2.0.v20170105-1446.jar:?]
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) [org.eclipse.equinox.cm_1.2.0.v20170105-1446.jar:?]
Caused by: org.eclipse.kura.KuraException: The configuration attribute clientId is required and no value has been specified.
	at org.eclipse.kura.core.util.ValidationUtil.notEmptyOrNull(ValidationUtil.java:34) ~[org.eclipse.kura.core_1.0.400.jar:?]
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.buildConfiguration(MqttDataTransport.java:727) ~[?:?]
... 51 more
~~~

**Target Environment (please complete the following information):**
 - Profile: `intel-up2-centos-7-nn`
 - OS version: `Linux kura-instance-0 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by MMaiero** [comment]
Are you working with Kura 4.0 or 4.1-SNAPSHOT?

In theory there are, at the moment, no changes in cloud services that would affect the default connection.
What I believe is the fact that Kura is unable to get the MAC address of your host and, in this way, it is not able to have the MQTT data transport working due to a missing client id.
Maybe something has changed in your base image.

**Comment by ctron** [comment]
I think it should be. It is built from f9f969231892769a269876b23f19fa0e8173e3df ... 

The base image didn't change, with a pre-4.0 commit it does work, with 4.0 it doesn't. I also did change the primary ethernet interface, so that it could find a mac address. But no connections get listed in the UI. And the bundle doesn't export any service.

I simple stick to my pre-4.0 image.

**Comment by MMaiero** [comment]
Tested today the docker build with Kura 4.1.0-SNAPSHOT and everything seems to be working.
