### ISSUE TITLE
Could not register mbeans javax.management.InstanceAlreadyExistsException

### ISSUE THREAD

**Issue by miricy** [eclipse/kura#2475]
**Describe the bug**
This exception only in this version ,No problem with previous versions
# ./start_kura_debug.sh 
Listening for transport dt_socket at address: 8000
2019-07-02 07:42:27,392 ConfigurationListener Event Queue ERROR Could not register mbeans javax.management.InstanceAlreadyExistsException: org.apache.logging.log4j2:type=org.eclipse.kura.linux.net
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:556)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:122)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at org.eclipse.kura.cloud.app.command.CommandCloudApp.<clinit>(CommandCloudApp.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:237)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:109)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:906)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:879)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:508)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:624)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:920)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:887)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:874)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:941)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:675)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:430)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:431)
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:284)
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$1.configurationEvent(RegionConfigurationSupport.java:89)
	at org.eclipse.equinox.internal.cm.EventDispatcher$1.run(EventDispatcher.java:89)
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)

[  502.496735@1] "java" (3536) uses deprecated CP15 Barrier instruction at 0xd1f78550
[  502.498866@1] "java" (3536) uses deprecated CP15 Barrier instruction at 0xd1fb287c
[  502.506239@1] "java" (3536) uses deprecated CP15 Barrier instruction at 0xd1fb2884
2019-07-02 07:42:29,469 ConfigurationListener Event Queue ERROR Could not register mbeans javax.management.InstanceAlreadyExistsException: org.apache.logging.log4j2:type=org.eclipse.kura.linux.usb
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:556)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:122)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at org.eclipse.kura.broker.artemis.simple.mqtt.ServiceComponent.<clinit>(ServiceComponent.java:43)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:237)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:109)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:906)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:879)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:508)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:624)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:920)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:887)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:874)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:941)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:675)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:430)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:431)
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:284)
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$1.configurationEvent(RegionConfigurationSupport.java:89)
	at org.eclipse.equinox.internal.cm.EventDispatcher$1.run(EventDispatcher.java:89)
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)

osgi> ss
"Framework is launched."

id	State       Bundle
0	ACTIVE      org.eclipse.osgi_3.12.50.v20170928-1321
	            Fragments=2
1	ACTIVE      org.eclipse.equinox.cm_1.2.0.v20170105-1446
2	RESOLVED    org.eclipse.kura.sun.misc_1.0.400
	            Master=0
3	ACTIVE      org.eclipse.equinox.common_3.9.0.v20170207-1454
4	ACTIVE      org.eclipse.equinox.registry_3.7.0.v20170222-1344
5	ACTIVE      org.eclipse.equinox.http.registry_1.1.400.v20150715-1528
6	ACTIVE      org.eclipse.equinox.console_1.1.300.v20170512-2111
7	ACTIVE      org.eclipse.equinox.ds_1.5.0.v20170307-1429
8	ACTIVE      org.eclipse.equinox.event_1.4.0.v20170105-1446
9	ACTIVE      org.eclipse.equinox.io_1.1.100.v20150430-1834
10	ACTIVE      org.eclipse.equinox.metatype_1.4.300.v20170105-1446
11	ACTIVE      org.eclipse.equinox.util_1.0.500.v20130404-1337
12	ACTIVE      org.eclipse.osgi.services_3.6.0.v20170228-1906
13	ACTIVE      org.eclipse.osgi.util_3.4.0.v20170111-1608
14	ACTIVE      org.apache.felix.scr_2.0.10.v20170501-2007
15	ACTIVE      org.apache.felix.gogo.command_0.10.0.v201209301215
16	ACTIVE      org.apache.felix.gogo.runtime_0.10.0.v201209301036
17	ACTIVE      org.apache.felix.gogo.shell_0.10.0.v201212101605
18	ACTIVE      org.knowhowlab.osgi.monitoradmin_1.0.2
19	ACTIVE      org.apache.felix.dependencymanager_3.0.0
20	ACTIVE      org.apache.felix.deploymentadmin_0.9.5
21	ACTIVE      org.eclipse.equinox.wireadmin_1.0.800.v20180827-1235
22	STARTING    org.eclipse.equinox.http.jetty_3.4.0.v20170503-2025
	            Fragments=23
23	RESOLVED    org.eclipse.kura.jetty.customizer_1.0.200.SNAPSHOT
	            Master=22
24	ACTIVE      org.eclipse.equinox.http.servlet_1.4.0.v20170524-1452
25	ACTIVE      org.eclipse.jetty.continuation_9.4.12.v20180830
26	ACTIVE      org.eclipse.jetty.http_9.4.12.v20180830
27	ACTIVE      org.eclipse.jetty.io_9.4.12.v20180830
28	ACTIVE      org.eclipse.jetty.security_9.4.12.v20180830
29	ACTIVE      org.eclipse.jetty.server_9.4.12.v20180830
30	ACTIVE      org.eclipse.jetty.servlet_9.4.12.v20180830
31	ACTIVE      org.eclipse.jetty.util_9.4.12.v20180830
32	ACTIVE      javax.servlet_3.1.0.v201410161800
33	ACTIVE      org.apache.commons.fileupload_1.3.3
34	ACTIVE      org.apache.commons.io_2.4.0
35	ACTIVE      slf4j.api_1.7.25
36	ACTIVE      jcl.over.slf4j_1.7.25
37	RESOLVED    org.apache.log4j2-api-config_1.0.0
	            Master=38
38	ACTIVE      org.apache.logging.log4j.api_2.8.2
	            Fragments=37
39	ACTIVE      org.apache.logging.log4j.core_2.8.2
40	ACTIVE      org.apache.logging.log4j.slf4j-impl_2.8.2
41	RESOLVED    minimal-json_0.9.4
42	ACTIVE      org.h2_1.4.192
43	RESOLVED    com.codeminders.hidapi.armv6hf_1.1.500
	            Master=44
44	ACTIVE      com.codeminders.hidapi_1.1.500
	            Fragments=43
45	RESOLVED    org.eclipse.soda.dk.comm.armv6hf_1.2.500
	            Master=46
46	ACTIVE      org.eclipse.soda.dk.comm_1.2.500
	            Fragments=45
47	ACTIVE      org.apache.commons.lang3_3.4.0
48	ACTIVE      org.usb4java_1.2.500
49	ACTIVE      usb4java-javax_1.2.500
50	RESOLVED    jdk.dio.armv6hf_1.0.500
	            Master=51
51	RESOLVED    jdk.dio_1.0.500
	            Fragments=50
52	RESOLVED    tinyb.armv6hf_1.0.300
	            Master=53
53	ACTIVE      tinyb_1.0.300
	            Fragments=52
54	ACTIVE      org.apache.commons.net_3.1.0.v201205071737
55	RESOLVED    org.apache.commons.exec_1.3.0
56	ACTIVE      com.eclipsesource.jaxrs.jersey-min_2.22.2
57	ACTIVE      com.eclipsesource.jaxrs.publisher_5.3.1.201602281253
58	ACTIVE      com.eclipsesource.jaxrs.provider.gson_2.3.0.201602281253
59	ACTIVE      com.eclipsesource.jaxrs.provider.security_2.2.0.201602281253
60	RESOLVED    com.google.gson_2.7.0.v20170129-0911
61	RESOLVED    org.apache.commons.csv_1.4.0
62	ACTIVE      org.eclipse.kura.api_2.1.0
63	ACTIVE      org.eclipse.kura.core_1.0.600.201907020635
64	ACTIVE      org.eclipse.kura.core.certificates_1.0.500
65	ACTIVE      org.eclipse.kura.core.cloud_1.1.500.201907020035
66	ACTIVE      org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider_1.0.100
67	ACTIVE      org.eclipse.kura.cloudconnection.raw.mqtt.provider_1.0.0.201907020035
68	ACTIVE      org.eclipse.kura.core.comm_1.0.500
69	ACTIVE      org.eclipse.kura.core.configuration_2.0.200
70	ACTIVE      org.eclipse.kura.core.crypto_1.0.600.201907020035
71	ACTIVE      org.eclipse.kura.core.deployment_1.1.500
72	ACTIVE      org.eclipse.kura.core.net_1.0.500
73	ACTIVE      org.eclipse.kura.core.status_1.0.500
74	ACTIVE      org.eclipse.kura.deployment.agent_1.0.500
75	ACTIVE      org.eclipse.kura.linux.clock_1.0.500
76	ACTIVE      org.eclipse.kura.linux.command_1.0.400
77	ACTIVE      org.eclipse.kura.linux.position_1.0.500
78	RESOLVED    org.eclipse.kura.linux.usb.armv6hf_1.0.500
	            Master=79
79	ACTIVE      org.eclipse.kura.linux.usb_1.0.500
	            Fragments=78
80	ACTIVE      org.eclipse.kura.linux.bluetooth_1.0.500
81	ACTIVE      org.eclipse.kura.ble.provider_1.0.400.201907020035
82	ACTIVE      org.eclipse.kura.ble.ibeacon.provider_1.0.300
83	ACTIVE      org.eclipse.kura.ble.eddystone.provider_1.0.300
84	ACTIVE      org.eclipse.kura.linux.watchdog_1.0.500
85	RESOLVED    org.eclipse.kura.camel.sun.misc_1.0.400
	            Master=87
86	ACTIVE      org.apache.camel.camel-amqp_2.21.1
87	ACTIVE      org.apache.camel.camel-core_2.21.1
	            Fragments=85
88	ACTIVE      org.apache.camel.camel-core-osgi_2.21.1
89	ACTIVE      org.apache.camel.camel-jms_2.21.1
90	ACTIVE      org.apache.camel.camel-script_2.21.1
91	ACTIVE      org.apache.camel.camel-stream_2.21.1
92	ACTIVE      org.eclipse.kura.camel_1.3.100
93	ACTIVE      org.eclipse.kura.camel.cloud.factory_1.1.400
94	ACTIVE      org.eclipse.kura.camel.xml_1.1.100
95	ACTIVE      org.eclipse.kura.wire.camel_1.0.100
96	ACTIVE      org.apache.qpid.jms.client_0.31.0
97	ACTIVE      org.apache.qpid.proton-j_0.26.0
98	ACTIVE      org.apache.servicemix.bundles.spring-beans_4.3.14.RELEASE_1
99	ACTIVE      org.apache.servicemix.bundles.spring-context_4.3.14.RELEASE_1
100	ACTIVE      org.apache.servicemix.bundles.spring-core_4.3.14.RELEASE_1
101	ACTIVE      org.apache.servicemix.bundles.spring-expression_4.3.14.RELEASE_1
102	ACTIVE      org.apache.servicemix.bundles.spring-jms_4.3.14.RELEASE_1
103	ACTIVE      org.apache.servicemix.bundles.spring-tx_4.3.14.RELEASE_1
104	ACTIVE      org.eclipse.kura.rest.provider_1.1.0.201907020035
105	ACTIVE      org.eclipse.kura.asset.provider_2.0.200
106	ACTIVE      org.eclipse.kura.asset.cloudlet.provider_1.0.400
107	ACTIVE      org.eclipse.kura.asset.helper.provider_1.0.400
108	ACTIVE      org.eclipse.kura.rest.asset.provider_1.0.400.201907020035
109	RESOLVED    com.google.guava_25.0.0.jre
110	RESOLVED    io.netty.buffer_4.1.34.Final
111	RESOLVED    io.netty.codec_4.1.34.Final
112	RESOLVED    io.netty.codec-http_4.1.34.Final
113	RESOLVED    io.netty.codec-mqtt_4.1.34.Final
114	RESOLVED    io.netty.common_4.1.34.Final
115	RESOLVED    io.netty.handler_4.1.34.Final
116	RESOLVED    io.netty.resolver_4.1.34.Final
117	RESOLVED    io.netty.transport_4.1.34.Final
118	RESOLVED    io.netty.transport-native-epoll_4.1.34.Final
119	RESOLVED    io.netty.transport-native-kqueue_4.1.34.Final
120	RESOLVED    io.netty.transport-native-unix-common_4.1.34.Final
121	ACTIVE      org.apache.activemq.artemis-mqtt-protocol_2.6.4
122	RESOLVED    org.apache.activemq.artemis-native_2.6.4
123	RESOLVED    org.apache.commons.beanutils_1.9.3
124	RESOLVED    org.apache.commons.collections_3.2.2
125	RESOLVED    org.apache.geronimo.specs.geronimo-jms_2.0_spec_1.0.0.alpha-2
126	RESOLVED    org.apache.geronimo.specs.geronimo-json_1.0_spec_1.0.0.alpha-1
127	RESOLVED    org.apache.geronimo.specs.geronimo-jta_1.1_spec_1.1.1
128	RESOLVED    org.jboss.logging.jboss-logging_3.3.2.Final
129	RESOLVED    org.apache.activemq.artemis_2.6.0
130	ACTIVE      org.eclipse.kura.broker.artemis.core_1.1.100
131	ACTIVE      org.eclipse.kura.broker.artemis.simple.mqtt_1.0.300
132	ACTIVE      org.eclipse.kura.broker.artemis.xml_1.0.300
133	ACTIVE      org.eclipse.kura.hook.file.move.provider_1.0.300
134	ACTIVE      org.eclipse.kura.json.marshaller.unmarshaller.provider_1.0.200
135	ACTIVE      org.eclipse.kura.xml.marshaller.unmarshaller.provider_1.0.200
136	ACTIVE      org.eclipse.kura.driver.helper.provider_1.0.400
137	ACTIVE      org.eclipse.kura.localization_1.0.400
	            Fragments=138
138	RESOLVED    org.eclipse.kura.localization.resources_1.0.400
	            Master=137
139	ACTIVE      org.eclipse.kura.util_1.1.100
140	ACTIVE      org.eclipse.kura.wire.h2db.component.provider_1.0.300
141	ACTIVE      org.eclipse.kura.wire.component.provider_1.0.500.201907020035
142	ACTIVE      org.eclipse.kura.wire.helper.provider_1.0.400
143	ACTIVE      org.eclipse.kura.wire.provider_1.0.400
144	ACTIVE      org.eclipse.kura.wire.component.conditional.provider_1.0.200
145	ACTIVE      org.eclipse.kura.wire.component.join.provider_1.0.200
146	ACTIVE      org.eclipse.kura.misc.cloudcat_1.0.300
147	RESOLVED    com.gwt.user_1.1.100
148	ACTIVE      org.eclipse.kura.web2_2.0.600.201907020106
149	ACTIVE      org.eclipse.kura.http.server.manager_1.0.0.201907020035
150	ACTIVE      org.eclipse.kura.linux.gpio_1.0.500
151	ACTIVE      org.eclipse.kura.linux.net_1.0.600.201907020035
152	ACTIVE      org.eclipse.kura.net.admin_1.0.500
153	ACTIVE      org.eclipse.kura.linux.sysv.provider_1.0.100
154	ACTIVE      org.eclipse.kura.linux.debian.provider_1.0.100
155	ACTIVE      org.tigris.mtoolkit.iagent.rpc_3.0.0.20110411-0918

**Comment by MMaiero** [comment]
Hi,
this exception seems to be related to the new logging system.
We reviewed that, but it does not seem to affect the framework or the functionalities provided.

Best regards,
Matteo

**Comment by miricy** [comment]
Hi @MMaiero ：
       22	STARTING org.eclipse.equinox.http.jetty_3.4.0.v20170503-2025
Fragments=23
      The bundle "org.eclipse.equinox.http.jetty" status is STARTING,
       My web console can't run,  When I restart it, I can visit normally again.
       I don't know why. Is it related to this?

**Comment by MMaiero** [comment]
It is probably related to the new HTTPS feature. You may need to have a look at the logs to see if there is something wrong there. Is the https keystone available?

**Comment by miricy** [comment]
@MMaiero  Thanks for you reply,I check it first.

**Comment by miricy** [comment]
Hi @MMaiero 
The https keystone not available,  
When i set disable the https, or remove the bundle org.eclipse.kura.http.server.manager,
The web can't access,  the bundle org.eclipse.equinox.http.jetty status is STARTING.
But i restart the bundle org.eclipse.equinox.http.jetty, the web Visit normally.
It is probably not related to the new HTTPS feature.

The restart command is:
osgi> start org.eclipse.equinox.http.jetty

**Comment by MMaiero** [comment]
the server manager bundle is a fragment that is related to the http.jetty bundle. If that doesn't start, then also the http.jetty will not start.
Obviously, if you remove the server manager and restart it will boot with defaults.

**Comment by miricy** [comment]
Whether I have it or not deleted “org.eclipse.kura.http.server.manager” in the plugin， started kura, the web console could not be accessed. I run ‘start org.eclipse.equinox.http.jetty’ command ， But the web Visit normally.  Just the first time can't start it.  Is it related to the plugin start sequence?

**Comment by MMaiero** [comment]
You may want to try to see why the bundle is in starting and what dependency is missing and preventing it to start

**Comment by miricy** [comment]
Hi @MMaiero 
I regenerate the certificate httpskeystore.ks, Problem solved.
Thanks very much。

**Comment by MMaiero** [comment]
Thank you for the feedback.
Glad that it works.

**Comment by LucaMannella** [comment]
Hello,
I have a very similar issue but instead of having
`org.apache.logging.log4j2:type=org.eclipse.kura.linux.net`
I have:
`org.apache.logging.log4j2:type=org.eclipse.kura.linux.usb`
and the stack trace look quite identical.

Do you have any idea of what could be the issue?
I'm running the last version of Kura (4.1) inside a Docker container and I have this issue at start time.

Thank you in advance for you help!

**Comment by MMaiero** [comment]
Hi @Sarcares,
is the error affecting the framework in your case?

Best regards,
Matteo

**Comment by LucaMannella** [comment]
Hi @MMaiero,

it is one of the first times that I try Kura so I'm not completely sure.
Appparently, if I go to the dashboard http://localhost:8080/kura it seems that Kura is correctly running.

The strange fact is that I did not see this error the first time that I started the container, it appeared when I recreated it.

Thanks for your support!
Luca

**Comment by MMaiero** [comment]
It depends on the ways the Kura components are started.
From what we have seen it is just cosmetic, but we will try to solve it in one of the next releases.

**Comment by LucaMannella** [comment]
Ok, in case I'll experiment some particular issue related to him, I'll write again you!

Thank you again for your very fast answer!
