### ISSUE TITLE
Kura is not able to reconnect the mqtt server when connectionLost

### ISSUE THREAD

**Issue by liucunjie** [eclipse/kura#2562]
**Describe the bug**
When the mqtt server is restarted, Kura is not able to reconnect the mqtt server.
Only manually reconnect to solve the issue.

**Kura.log**
2019-10-28T09:20:51,182 [MQTT Rec: B8:27:EB:04:78:18] WARN  o.e.k.c.d.t.m.MqttDataTransport - Connection Lost
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:189)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:136)
	... 1 more
2019-10-28T09:20:51,186 [MQTT Rec: B8:27:EB:04:78:18] INFO  o.e.k.c.d.DataServiceImpl - connectionLost
2019-10-28T09:20:51,187 [pool-23-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED off

**To Reproduce**
1. Go to 'The Cloud Services section of the Kura Administrative Web UI .
2. Click on 'Connection/Disconnect to connect the CloudService instance
3. Restart MQTT Server

**Expected behavior**
Kura reconnect to the MQTT Server periodically based the DataService conf.

**Screenshots**
N/A.

**Target Environment (please complete the following information):**
 - Board [e.g. Raspberry Pi 3B+]
 - OS version: 2018-11-13-raspbian-stretch-lite    
   [Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
]
 - Additional info: 

**Additional context**

**Comment by spnettec** [comment]
Which version of the kura?

**Comment by liucunjie** [comment]
Kura Version: 4.2.0
Maybe it is paho bundle issue, the link:  https://github.com/eclipse/paho.mqtt.java/issues/673
I am not sure

**Comment by MMaiero** [comment]
Hi, what is the configuration of the mqttdatatransport and data service you are using?

**Comment by liucunjie** [comment]
I just change the  broker-url value :  mqtt://mqtt.eclipse.org:1883/  and keep others default 
restart my router, the result is same, but kura.log error msg is:

2019-10-28T18:04:44,517 [MQTT Ping: B8:27:EB:04:78:18] WARN  o.e.k.c.d.t.m.MqttDataTransport - Connection Lost
Timed out waiting for a response from the server (32000)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.checkForActivity(ClientState.java:741)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:816)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:802)
	at org.eclipse.paho.client.mqttv3.TimerPingSender$PingTask.run(TimerPingSender.java:79)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
2019-10-28T18:04:44,519 [MQTT Ping: B8:27:EB:04:78:18] INFO  o.e.k.c.d.DataServiceImpl - connectionLost
2019-10-28T18:04:44,520 [pool-23-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED off

**Comment by MMaiero** [comment]
Did you enable the reconnect feature of data service?
Otherwise the framework will not try to reconnect if it looses the connection.

**Comment by liucunjie** [comment]
Sorry for that , It's my fault, and I will set connect.auto-on-startup to true
I misunderstand this value

**Comment by liucunjie** [comment]
Sorry for all things, thanks for your time, I read the documentation carefully and re-tested,
and I could not reproduce it so I am closing the issue.
