### ISSUE TITLE
Unable to install package if there is a "space" in package name

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2616]
**Describe the bug**
Unable to install package if there is a "space" in package name

**To Reproduce**
1. Use any package and rename it - add "space" somewhere in the name
2. Try to install that package -> System / Packages / Install 

**Expected behavior**
Package should be installed without errors

**Target Environment (please complete the following information):**
 - Raspberry Pi 3
 - Kura 4.1.1
 - Reproduced this on ESF but able to recreate on Kura too

**Additional context**
This is not trivial issue since if WIN user downloads the same package twice - the second one will contain "space" in name and that package will not possible to install 

**kura.log**

```
2020-01-09T08:46:52,201 [DeploymentAgent] ERROR o.e.k.d.a.i.DeploymentAgent - Exception installing package at URL file:/tmp/com.eurotech.ble.sensortag.driver_1.0.300_%20(1).dp
java.nio.file.NoSuchFileException: /tmp/com.eurotech.ble.sensortag.driver_1.0.300_%20(1).dp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.installDeploymentPackageInternal(DeploymentAgent.java:478)
        at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.execInstall(DeploymentAgent.java:323)
        at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.installer(DeploymentAgent.java:307)
        at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.lambda$0(DeploymentAgent.java:172)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-01-09T08:46:52,202 [DeploymentAgent] INFO  o.e.k.d.a.i.DeploymentAgent - Posting INSTALLED event for package at URL file:/tmp/com.eurotech.ble.sensortag.driver_1.0.300_%20(1).dp: unsuccessful
```

**Comment by MMaiero** [comment]
Made PR #2624 to fix this. @mstankovic Can you please check if this works for you?

**Comment by mstankovic** [comment]
@MMaiero 
I checked this PR(#2624). works for me! Thanks.
