### ISSUE TITLE
Cloud Connection is disconnected when I try to connect second connection

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2689]
**Describe the bug**
Configure Cloud connection and connect it to the cloud - mqtt protocol (im using "mqtt://broker-sandbox.everyware-cloud.com:1883"). After that create second connection with ws protocol (ws://broker-sandbox.everyware-cloud.com:8080) and try to connect to the cloud. The first one is automatically disconnected. If you recreate this with reverse order it will not disconnect.

**To Reproduce**
1. Go to Cloud connection service and configure CC to broker mqtt://broker-sandbox.everyware-cloud.com:1883 
2. Connect it - Successfully 
3. Create a new Connection and configure it to use ws://broker-sandbox.everyware-cloud.com:8080 broker
4. Connect it -Successfully (but the first one gets disconnected)

Note: If i change the order for connections (first connect with ws and after that with mqtt) both connections stay connected to the cloud

**Expected behavior**
Connecting second connection should not disconnects the first one

**Target Environment (please complete the following information):**
 - RG-1020
 - ESF 6.2-SNAPSHOT

**Exception log**

```
2020-03-05T12:15:38,266 [MQTT Rec: 00:60:0C:83:BF:40] WARN  o.e.k.c.d.t.m.MqttDataTransport - Connection Lost
Connection lost (32109) - java.io.EOFException
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:189)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:136)
        ... 1 more
2020-03-05T12:15:38,268 [MQTT Rec: 00:60:0C:83:BF:40] INFO  o.e.k.c.d.DataServiceImpl - connectionLost
```

**Comment by MMaiero** [comment]
Are you defining different client ids for the two connections?

**Comment by mstankovic** [comment]
No, I am using the same client id for both connections.

**Comment by MMaiero** [comment]
That is the problem. Have a look at "stealing link"

**Comment by mstankovic** [comment]
I got it! Thank you. Checked and verified - able to connect to the same broker with different client ids. 
Closing this one.
