### ISSUE TITLE
Hostapd Service Suddenly Not Working Any More

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2895]
Today I noticed a weird problem. When I tried to connect to Kura's wifi AP, I got an authentication error. I looked into logs and there was this log:

> enable() :: disabling DHCP client for wlan0
disable() :: killing DHCP client for wlan0
Attempting to send SIGKILL to process with pid 18875
enable() :: Starting DHCP client for wlan0
bringing interface wlan0 up
Attempting to send SIGKILL to process with pid 19224
starting hostapd for the wlan0 interface --> [hostapd, -B, /etc/hostapd-wlan0.conf]
failed to start hostapd for the wlan0 interface for unknown reason - errorCode=1
monitor() :: Error enabling wlan0 interface, will try to reset wifi
org.eclipse.kura.KuraException: An internal error occurred. {0}
        at org.eclipse.kura.net.admin.NetworkAdminServiceImpl.enableInterface(NetworkAdminServiceImpl.java:1024)
        at org.eclipse.kura.net.admin.monitor.WifiMonitorServiceImpl.enableInterface(WifiMonitorServiceImpl.java:706)
        at org.eclipse.kura.net.admin.monitor.WifiMonitorServiceImpl.monitorEnabledInterfaces(WifiMonitorServiceImpl.java:391)
        at org.eclipse.kura.net.admin.monitor.WifiMonitorServiceImpl.monitor(WifiMonitorServiceImpl.java:292)
        at org.eclipse.kura.net.admin.monitor.WifiMonitorServiceImpl.lambda$0(WifiMonitorServiceImpl.java:766)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.eclipse.kura.KuraException: An internal error occurred. 
        at org.eclipse.kura.KuraException.internalError(KuraException.java:120)
        at org.eclipse.kura.linux.net.wifi.HostapdManager.start(HostapdManager.java:68)
        at org.eclipse.kura.net.admin.NetworkAdminServiceImpl.enableWifiInterface(NetworkAdminServiceImpl.java:1339)
        at org.eclipse.kura.net.admin.NetworkAdminServiceImpl.enableInterface(NetworkAdminServiceImpl.java:1005)
        ... 9 more
Caused by: org.eclipse.kura.KuraException: An internal error occurred. failed to start hostapd for unknown reason
        at org.eclipse.kura.KuraException.internalError(KuraException.java:105)
        at org.eclipse.kura.linux.net.wifi.HostapdManager.start(HostapdManager.java:64)
        ... 11 more

I tried rebooting the device, resetting it, disabling and enabling wifi again, but nothing helped. 
Did anyone of you encountered similar problems?
My raspberry was up for about a week. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> Wireless
3. Setup an access point with all valid parameters
4. Try to connect to the AP with external device (e.g. phone)

**Expected behavior**
This should not occour and even if it happens, reboot should help resolve this problem. 

**Screenshots**
See log file above. 

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG If you have time, could you stop Kura, run this command on the terminal and get the output?
`sudo hostapd -dd -B /etc/hostapd-wlan0.conf`

**Comment by LeoNerdoG** [comment]
Hi @pierantoniomerlino,
bellow is the log when I run this command. If you need anything else, please let me know. 

[hostapd-log.txt](https://github.com/eclipse/kura/files/4675704/hostapd-log.txt)

**Comment by MMaiero** [comment]
@pierantoniomerlino anything useful from the logs?

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG Have you ran into the same problem again? I tried with my RPi (Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux) and Kura 4.2.0-SNAPSHOT but I couldn't reproduce that.
BTW, the hostapd logs are ok.

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino I will check again today and let you know!

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
I have retested this and could not replicate the error, so I am closing the issue. 
If I find a way to recreate it in the future, I will update the issue.
