### ISSUE TITLE
Connecting to Hono

### ISSUE THREAD

**Issue by ArashJavan** [eclipse/kura#2982]
I have two related questions:

1) What is the difference between CloudService and CloudConnectionManager. Since from the GUI perspective they offer the same settings?

2) In the documentation is not really clear about connecting kura to hono. How can one connect kura to hono?
For example why should do we need both CloudConnectionManager and CloudService and how should they be configured?

Thanks and best regards
Arash

**Comment by MMaiero** [comment]
Hi,
CloudService is a deprecated api that is still in the codebase for compatibility and legacy reasons.
To connect to Hono you can use the org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider bundle that should be ready to be used out of the box.

Best regards,
Matteo

**Comment by ArashJavan** [comment]
@MMaiero Thanks for your reply :)
I am following the kura official documentation from [here](https://eclipse.github.io/kura/cloud-stacks/kura-hono.html) to connect kura (v4.1.1) running on RP3 with the [hono-sandbox](https://www.eclipse.org/hono/getting-started/).

![Screenshot from 2020-07-13 10-52-16](https://user-images.githubusercontent.com/5918827/87284762-08185500-c4f7-11ea-865d-1621d7a75414.png)

As you can see i could already connect to the eclipse mqtt-sandbox, and want now to connect to the hono-sandbox. REgardign to the kura doc i have to create a ConnectionManager and a CloudService, but how should they be confugred, why both of them at all? 

The documentation is unfortunately really poor in this part, even though with no doubt I appreciate the work done in this project.

I would be very grateful if you could enlighten me how to use the provided kura-gui to connect to hono-sandbox.

Thanks
Arash

**Comment by MMaiero** [comment]
So, the documentation clearly states to create a new instance of org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider like you did. That is the endpoint that will be used to connect to the Hono instance. You just need to click on that line and configure the proper parameters in the tabs that appear in the bottom of the page.
You don't have to create another CloudService.

**Comment by ArashJavan** [comment]
@MMaiero Thanks for clearification. Ok, I have delted the CloudService and now have only one CloudConnectionManager, following hono-sand-box doc I have created a Tenant and added a device with credentials to it.

Settings are:
Broker-Url: mqtt://hono.eclipseprojects.io:1883/
Username: 1fe90395-4ffe-47e8-af50-e7058cfd677d@dbd00315-9be3-48ba-be3e-c0703587f327 (this device@tenant)
password: mypass in plain text
client-id: 1fe90395-4ffe-47e8-af50-e7058cfd677d

but unfortunately i get following error!

![Screenshot from 2020-07-13 11-08-02](https://user-images.githubusercontent.com/5918827/87286668-6c3c1880-c4f9-11ea-9461-f4e130b3cd66.png)

**Comment by MMaiero** [comment]
If you access the kura.log file (usually is /var/log) what it does report?
I believe that Kura is not able to connect to the Hono instance

**Comment by ArashJavan** [comment]
This is the log-file content:

`2020-07-13T10:17:27,907 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - Creating a new client instance
2020-07-13T10:17:27,907 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - Using memory persistence for in-flight messages
2020-07-13T10:17:27,910 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - # ------------------------------------------------------------
2020-07-13T10:17:27,911 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connection Properties
2020-07-13T10:17:27,911 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  broker    = tcp://hono.eclipseprojects.io:1883
2020-07-13T10:17:27,911 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  clientId  = 1fe90395-4ffe-47e8-af50-e7058cfd677d
2020-07-13T10:17:27,912 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  username  = 1fe90395-4ffe-47e8-af50-e7058cfd677d@dbd00315-9be3-48ba-be3e-c0703587f327
2020-07-13T10:17:27,912 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  password  = XXXXXXXXXXXXXX
2020-07-13T10:17:27,912 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  keepAlive = 30
2020-07-13T10:17:27,912 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  timeout   = 10
2020-07-13T10:17:27,913 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  cleanSession    = true
2020-07-13T10:17:27,913 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  MQTT version    = 3.1.1
2020-07-13T10:17:27,913 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willDestination = $EDC//1fe90395-4ffe-47e8-af50-e7058cfd677d/MQTT/LWT
2020-07-13T10:17:27,914 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willMessage     = 
2020-07-13T10:17:27,914 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #
2020-07-13T10:17:27,914 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connecting...
2020-07-13T10:17:27,915 [pool-19-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED fast blinking
2020-07-13T10:17:28,243 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:28,252 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:28,340 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: /mickytopoli/camel/example with QoS: 0
2020-07-13T10:17:28,589 [qtp25490953-140] WARN  o.e.k.c.d.t.m.MqttDataTransport - xxxxx  Connect failed. Forcing disconnect. xxxxx
2020-07-13T10:17:28,589 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - Closing client...
2020-07-13T10:17:28,592 [qtp25490953-140] INFO  o.e.k.c.d.t.m.MqttDataTransport - Closed
2020-07-13T10:17:28,593 [pool-19-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED off
2020-07-13T10:17:28,593 [qtp25490953-140] WARN  o.e.k.w.s.GwtNetworkServiceImpl - Error connecting
org.eclipse.kura.KuraConnectException: "Connection failed. Cannot connect"
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.connect(MqttDataTransport.java:342)
	at org.eclipse.kura.core.data.DataServiceImpl.connect(DataServiceImpl.java:489)
	at org.eclipse.kura.internal.cloudconnection.eclipseiot.mqtt.cloud.CloudConnectionManagerImpl.connect(CloudConnectionManagerImpl.java:705)
	at org.eclipse.kura.web.server.GwtStatusServiceImpl.connectDataService(GwtStatusServiceImpl.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.service(OsgiRemoteServiceServlet.java:41)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1223)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:148)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:131)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:74)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:284)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:876)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Bad user name or password (4)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:1040)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:150)
	... 1 more
2020-07-13T10:17:29,244 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:29,263 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:29,326 [] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic: #account-name/#client-id/APP!/messages, priority: 7
2020-07-13T10:17:29,338 [] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic: #account-name/#client-id/APP!/messages, priority: 7
2020-07-13T10:17:29,339 [] INFO  o.e.k.d.h.Heater - Published message: org.eclipse.kura.message.KuraPayload@15c6a38
2020-07-13T10:17:29,345 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: /mickytopoli/camel/example with QoS: 0
2020-07-13T10:17:30,244 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:30,253 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:30,343 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: /mickytopoli/camel/example with QoS: 0
2020-07-13T10:17:31,245 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:31,254 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:31,326 [] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic: #account-name/#client-id/APP!/messages, priority: 7
2020-07-13T10:17:31,337 [] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic: #account-name/#client-id/APP!/messages, priority: 7
2020-07-13T10:17:31,338 [] INFO  o.e.k.d.h.Heater - Published message: org.eclipse.kura.message.KuraPayload@1a0f7c
2020-07-13T10:17:31,348 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: /mickytopoli/camel/example with QoS: 0
2020-07-13T10:17:32,244 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:32,259 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:32,343 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: /mickytopoli/camel/example with QoS: 0
2020-07-13T10:17:33,245 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:33,258 [Camel (camel-1) thread #1 - timer://heartbeat] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic: #account-name/#client-id/camel/example, priority: 5
2020-07-13T10:17:33,326 [] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic: #account-name/#client-id/APP!/messages, priority: 7
2020-07-13T10:17:33,337 [] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic: #account-name/#client-id/APP!/messages, priority: 7
2020-07-13T10:17:33,338 [] INFO  o.e.k.d.h.Heater - Published message: org.eclipse.kura.message.KuraPayload@4e179c`

**Comment by ArashJavan** [comment]
It says badusername or password. But I am not sure is the username schema device-id@tenant-id" correct? If yes shoudl i provide password in plain-text or hashed? What aboud client ID, is it the same as device-id?

**Comment by MMaiero** [comment]
The password is usually in plain text

**Comment by ArashJavan** [comment]
@MMaiero, It's connected now! Thanks!
What I did for others:
- Created a tenant, device and password using [Device Registry Management API](https://www.eclipse.org/hono/docs/api/management/), with user defined ids rather than those created randomly.

![Screenshot from 2020-07-13 11-47-21](https://user-images.githubusercontent.com/5918827/87290740-a6f47f80-c4fe-11ea-8f89-776b4523ba2b.png)
