### ISSUE TITLE
How can I solve this problem? (about SenseHat Diver)

### ISSUE THREAD

**Issue by 97Albino** [eclipse/kura#3103]
**Is your feature request related to a problem? Please describe.**
hi
I installed sensehat driver and set configurations like this.
https://marketplace.eclipse.org/content/sensehat-example-driver-eclipse-kura-4xy
![image](https://user-images.githubusercontent.com/58206274/96074670-35084980-0ee4-11eb-97a9-74853fbc093e.png)

I referred to the link below.
http://eclipse.github.io/kura/devices/sensehat-driver.html

When I clicked [data], the following error guide occurred.
![image](https://user-images.githubusercontent.com/58206274/96075123-54ec3d00-0ee5-11eb-8b23-bb216e838bcb.png)
Does this error depend on kura wire or something else?
Does this error become a fatal error in connecting Kura and Hono?
Is this error 

**Describe the solution you'd like**
I want to transfer sensor data(pressure, temp, hummidity) to Hono(MQTT adaptor) by using Kura wire.

![image](https://user-images.githubusercontent.com/58206274/96075722-9df0c100-0ee6-11eb-9919-c1c0038d5a45.png)

**Additional context**
Kura 4.1.1
Rasberry Pi 3

**Comment by MMaiero** [comment]
Hi, 
I believe the error is due to the fact that the Kura Driver is not able to communicate with the sensehat.

The connection to Hono is not affected as is a different thing but for sure, since the data cannot be fetched from the sensehat, that it cannot also be published.

Unfortunately I don't have at the moment a SenseHat to perform some tests
@pierantoniomerlino Do you have an idea on why is not working?

**Comment by pierantoniomerlino** [comment]
IMHO, the Kura Driver is not able to communicate with the SenseHat. Have you tried to communicate with the SenseHat from Linux? Maybe there is something that is not properly configured...
@nicolatimeus Any idea?

**Comment by 97Albino** [comment]
Thanks for your replies. :)

Below is the information of [Show Stack Trace].

org.eclipse.kura.example.driver.sensehat.SenseHatInterface.fetch(SenseHatInterface.java:129)
org.eclipse.kura.example.driver.sensehat.SenseHatInterface.runReadRequest(SenseHatInterface.java:206)
org.eclipse.kura.example.driver.sensehat.SenseHatDriver$SenseHatPreparedRead.execute(SenseHatDriver.java:182)
org.eclipse.kura.asset.provider.BaseAsset.lambda$2(BaseAsset.java:313)
org.eclipse.kura.asset.provider.BaseAssetExecutor.lambda$0(BaseAssetExecutor.java:50)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

I enabled I2C and SPI on Raspberry Pi Configuration, since SenseHat uses I2C Interface .

But, I didn't try to communicate with sensehat from linux(raspbian).

--------------------------------------------------------------------------------------------------------------------------------------
I made a demo code, and it works well.

`#!/usr/bin/python`
`from sense_hat import SenseHat`
`sense = SenseHat()`
`sense.show_message(“Hello world!”)`

![KakaoTalk_20201016_040801344](https://user-images.githubusercontent.com/58206274/96175339-b8b64a80-0f65-11eb-93b6-26961a30de25.jpg)


Sadly, I still don't know which is the problem.

--------------------------------------------------------------------------------------------------------------------------------------



I found this comment.

https://github.com/eclipse/kura/issues/2098#issuecomment-387994399

![image](https://user-images.githubusercontent.com/58206274/96216730-fa71e000-0fbb-11eb-8e1c-30c25406bf21.png)


However, I couldn't find the path of `jdk.dio` and `com.oracle.dio.impl.Handle.tryLock(int)`.

**Comment by nicolatimeus** [comment]
Do you have any error logged in `/var/log/kura.log` or `/var/log/kura-console.log`?
I the error is related to #2098 you should see some error there. In that case you can try downgrading the JVM.

**Comment by 97Albino** [comment]
Here is the error logged in `/var/log/kura.log`

> 2020-10-20T06:56:36,722 [Refresh Thread: Equinox Container: edfd425d-438c-4d43-a3bf-97a0c8274bc5] ERROR o.e.k.r.s.s.LSM9DS1 - Unable to write to I2C device
jdk.dio.UnavailableDeviceException: Locked by other application
        at com.oracle.dio.impl.AbstractPeripheral.conditionalLock(AbstractPeripheral.java:96)
        at com.oracle.dio.i2cbus.impl.I2CSlaveImpl.transfer(I2CSlaveImpl.java:257)
        at com.oracle.dio.i2cbus.impl.I2CSlaveImpl.write(I2CSlaveImpl.java:195)
        at com.oracle.dio.i2cbus.impl.I2CSlaveImpl.write(I2CSlaveImpl.java:226)
        at org.eclipse.kura.raspberrypi.sensehat.sensors.KuraI2CDevice.write(KuraI2CDevice.java:45)
        at org.eclipse.kura.raspberrypi.sensehat.sensors.LSM9DS1.write(LSM9DS1.java:282)
        at org.eclipse.kura.raspberrypi.sensehat.sensors.LSM9DS1.disableMagnetometer(LSM9DS1.java:538)
        at org.eclipse.kura.raspberrypi.sensehat.sensors.LSM9DS1.closeDevice(LSM9DS1.java:240)
        at org.eclipse.kura.example.driver.sensehat.SenseHatInterface.<init>(SenseHatInterface.java:63)
        at org.eclipse.kura.example.driver.sensehat.SenseHatDriver.getSensehatInterface(SenseHatDriver.java:68)
        at org.eclipse.kura.example.driver.sensehat.SenseHatDriver.activate(SenseHatDriver.java:84)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.felix.scr.impl.inject.BaseMethod.invokeMethod(BaseMethod.java:229)
        at org.apache.felix.scr.impl.inject.BaseMethod.access$500(BaseMethod.java:39)
        at org.apache.felix.scr.impl.inject.BaseMethod$Resolved.invoke(BaseMethod.java:650)
        at org.apache.felix.scr.impl.inject.BaseMethod.invoke(BaseMethod.java:506)
        at org.apache.felix.scr.impl.inject.ActivateMethod.invoke(ActivateMethod.java:307)
        at org.apache.felix.scr.impl.inject.ActivateMethod.invoke(ActivateMethod.java:299)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:298)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:109)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:906)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:879)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:508)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:624)
        at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:920)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:887)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:874)
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:941)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:675)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:430)
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:657)
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:341)
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:390)
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:54)
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:265)
        at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:254)
        at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:227)
        at org.apache.felix.utils.extender.AbstractExtender.addingBundle(AbstractExtender.java:187)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:469)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168)
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
        at org.eclipse.osgi.container.Module.start(Module.java:467)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
        at org.eclipse.osgi.container.ModuleContainer.start(ModuleContainer.java:750)
        at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:741)
        at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:511)
        at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:457)
        at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1001)
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1382)
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

I found I2C problem on kura.

And I tried to install `oracle-java8-jdk` instead of `openjdk-8-jre-headless`, but I could'nt install it.

Maybe the licence is matter.

Can you recommand the other version of java?

**Comment by nicolatimeus** [comment]
Basing on the log it looks like you actually came across #2098.
That issue has been opened a few years ago and it is possible that in the meantime the Raspberry PI distribution changed and the `oracle-java8-jdk` package is no longer available by default. Maybe you can find it in external repositories.

Switching JVMs is not a reliable solution for fixing the problem, we should try to fix the inconsistency reported in comment https://github.com/eclipse/kura/issues/2098#issuecomment-387994399.
The root cause of this is likely the fact that the native implementation of `com.oracle.dio.impl.Handle.tryLock(int)` is incomplete and inconsistent with the Java method signature. This can lead to undefined behavior, because the Java method signature has boolean as return type while while the native implementation does not return anything. 
It is possible for example that the method returns `true` on some JVMs and `false` on other ones as we are observing.

If you have some time you can try changing the native implementation of `com.oracle.dio.impl.Handle.tryLock(int)` by changing the return type from `void` to `jboolean`, make it always return `true` and see if this removes the exception you are seeing.
If you are willing to try you must:

* Clone kura repo
* Apply the change to `target-platform/jdk.dio-parent/src/dev/src/se/native/com/oracle/dio/dio_common.cpp`
* Build the code using Raspberry PI toolchain 
* Replace `target-platform/jdk.dio-parent/jdk.dio.armv6hf/src/main/resources/lib/native/libdio.so` with the result of your build
* Rebuild jdk.dio.armv6hf with maven
* Replace the jdk.dio.armv6hf jar on the raspberry with the result of the maven build

Of course that change is not a proper fix, the proper way for fixing this would be providing a meaningful implementation to the `tryLock()` and `unlock()` methods, this would require more time. The "quick" change above is an experiment that could confirm that `com.oracle.dio.impl.Handle.tryLock(int)` is the root cause of the issue and probably provide you a working setup with your current JVM.

**Comment by 97Albino** [comment]
Thanks for your replies.

But I am not proceeding smoothly with the above process.

I changed `target-platform/jdk.dio-parent/src/dev/src/se/native/com/oracle/dio/dio_common.cpp`  `void -> jboolean`


![image](https://user-images.githubusercontent.com/58206274/96969840-c82d2900-154d-11eb-955e-f0767970d4a2.png)

Then, I followed belowing process.


`$ cd kura/target-platform/jdk.dio-parent/src/dev`

edit `Makefile`
![image](https://user-images.githubusercontent.com/58206274/97112807-aee0d400-1729-11eb-9db5-6a215b25bf2e.png)


`$ export PI_TOOLS=/usr/bin `
`$ export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-armhf`
`$ sudo make`

But, it couldn't work.

![image](https://user-images.githubusercontent.com/58206274/97112916-578f3380-172a-11eb-9da6-f7498c4f4547.png)


Is there any errors in my process?

**Comment by 97Albino** [comment]
Some updates are here.

I think I had some mistakes and edited them.


`$ cd kura/target-platform/jdk.dio-parent/src/dev`

edit `Makefile`

![image](https://user-images.githubusercontent.com/58206274/97132418-39f1b680-178a-11eb-9ea9-ce60f61bf1d7.png)

`$ export PI_TOOLS=/usr`
`$ export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-armhf`
`$ make`

`$ cd ~/kura/target-platform/jdk.dio-parent/src/dev/build/so`

`libdio.so` is in this directory.

`$ sudo cp libdio.so ~/kura/target-platform/jdk.dio-parent/jdk.dio.armv6hf/src/main/resources/lib/native/`
`$ cd ~/kura/target-platform/jdk.dio-parent/jdk.dio.armv6hf`
`$ mvn package`

`target` has been created.

`$ cd target`
![image](https://user-images.githubusercontent.com/58206274/97134328-4b3dc180-1790-11eb-88c6-f11e1b79ce70.png)

`$ sudo cp jdk.dio.armv6hf-1.0.600-SNAPSHOT.jar /opt/eclipse/kura_4.1.0_raspberry-pi-2/plugins`
`$ cd /opt/eclipse/kura_4.1.0_raspberry-pi-2/plugins`
Rename `jdk.dio.armv6hf-1.0.600-SNAPSHOT.jar` to `jdk.dio.armv6hf_1.0.500.jar`

The original files are backed up.


I followed these steps, but nothing is happened.

![image](https://user-images.githubusercontent.com/58206274/97134639-46c5d880-1791-11eb-8cf8-36a526741825.png)

Any opinions about it?

**Comment by nicolatimeus** [comment]
Good work, I think you understood how to build the library on the raspberry and made the necessary modification to the makefiles.

In your comments you said that you changed the return type of `com.oracle.dio.impl.Handle.tryLock(int)` from `void` to `jboolean` but you didn't mention any change to the function body.

You should also modify the function to always return true, in this way:

from:

```c
JNIEXPORT void JNICALL Java_com_oracle_dio_impl_Handle_tryLock
  (JNIEnv* env, jobject obj, jint timeout) {
    device_reference device = getDeviceReferenceFromHandleObject(env, obj);
    if (device != INVALID_DEVICE_REFERENCE) {
        //  add an implementation
    }
}
```
to
```c
JNIEXPORT jboolean JNICALL Java_com_oracle_dio_impl_Handle_tryLock
  (JNIEnv* env, jobject obj, jint timeout) {
    return true;
}
```

without the change in the function return value, its result will continue to be undefined even if you change the return type declaration.

You can try applying the change above and rebuild and redeploy the jar as you did.
In case it still doesn't work, have a look at possible errors in `/var/log/kura.log` and `/var/log/kura-console.log`, errors there are more informative than the one reported by the web ui.

**Comment by 97Albino** [comment]
Thanks to your help, I solved the problem.

![image](https://user-images.githubusercontent.com/58206274/97153399-c6659e80-17b5-11eb-9a87-72fdf7efdab4.png)

Now I2C connection is enabled and sensors are work very well.

**Comment by MMaiero** [comment]
Great job @97Albino and @nicolatimeus!
