### ISSUE TITLE
Error While trying install eclipse

### ISSUE THREAD

**Issue by felipecapelli** [eclipse/kura#3122]
ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 Unable to read repository at http://eclipse.sonarlint.org/content.xml.
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
  at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
  at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
  at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
  at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
  at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
  at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
  at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
  at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
  at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
  at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
  at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:248)
  at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by MMaiero** [comment]
Hi, 
could you please detail your environment?
I believe you are trying to setup eclipse to build/work on Kura. Could you please point out what guide you are using?

Best regards, 
Matteo

**Comment by felipecapelli** [comment]
Hello, Matteo.

I just started to studdy Eclipe Kura and I was following the instructions
in the Eclipse IDE section in the readme.md of this page:
https://github.com/eclipse/kura
I was in my personal computer, so I believe it maybe wasn't a problem
caused by a proxy rule... I was wondering if I could learn how to use Java
Camel inside the kura Wires...
Sorry, I'm starting to study all this stuff, but that's all I know about my
enviroiment...

I would be thankful if you could help me.
Thank you!

Best regards,
Felipe

Em dom., 25 de out. de 2020 às 16:40, Matteo Maiero <
notifications@github.com> escreveu:

**Comment by pierantoniomerlino** [comment]
Hi @felipecapelli, which OS are you using? 
You can find some more details on the installation in the official [Kura documentation](https://eclipse.github.io/kura/dev/kura-setup.html). 
If you want to develop some code for Kura, I strongly suggest to start with the Kura User Workspace as explained in the link above.
