### ISSUE TITLE
Error in logs after stoping Kura service

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#3216]
**Describe the bug**
There are a few error types in kura.log file which appear right after Kura service has been stopped.

**To Reproduce**
1. Add example publisher
2. Configure publisher
3. Stop Kura service with systemctl stop kura.service
4. See errors bellow

**ERROR**
```
2020-12-04T14:37:28,748 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: Comtrade/B8:27:EB:61:19:18/EXAMPLE_PUBLISHER/data/metrics with QoS: 1
2020-12-04T14:37:28,876 [MQTT Call: B8:27:EB:61:19:18] INFO  o.e.k.c.d.DataServiceImpl - Confirmed message ID: 66 to store
2020-12-04T14:37:28,880 [MQTT Call: B8:27:EB:61:19:18] ERROR o.e.k.c.d.H2DbServiceImpl - Error getting connection
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1557)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:561)
	at org.h2.jdbcx.JdbcXAConnection.getConnection(JdbcXAConnection.java:106)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:236)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at org.eclipse.kura.core.db.H2DbServiceImpl.getConnectionInternal(H2DbServiceImpl.java:320)
	at org.eclipse.kura.core.db.H2DbServiceImpl.withConnection(H2DbServiceImpl.java:161)
	at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:607)
	at org.eclipse.kura.core.data.store.DbDataStore.updateTimestamp(DbDataStore.java:501)
	at org.eclipse.kura.core.data.store.DbDataStore.confirmed(DbDataStore.java:400)
	at org.eclipse.kura.core.data.DataServiceImpl.onMessageConfirmed(DataServiceImpl.java:459)
	at org.eclipse.kura.core.data.transport.mqtt.DataTransportListenerS.onMessageConfirmed(DataTransportListenerS.java:257)
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.deliveryComplete(MqttDataTransport.java:634)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleActionComplete(CommsCallback.java:268)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:197)
	at java.lang.Thread.run(Thread.java:748)
2020-12-04T14:37:28,883 [MQTT Call: B8:27:EB:61:19:18] WARN  o.e.k.c.d.H2DbServiceImpl - Db operation failed
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1557)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:561)
	at org.h2.jdbcx.JdbcXAConnection.getConnection(JdbcXAConnection.java:106)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:236)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at org.eclipse.kura.core.db.H2DbServiceImpl.getConnectionInternal(H2DbServiceImpl.java:320)
	at org.eclipse.kura.core.db.H2DbServiceImpl.withConnection(H2DbServiceImpl.java:161)
	at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:607)
	at org.eclipse.kura.core.data.store.DbDataStore.updateTimestamp(DbDataStore.java:501)
	at org.eclipse.kura.core.data.store.DbDataStore.confirmed(DbDataStore.java:400)
	at org.eclipse.kura.core.data.DataServiceImpl.onMessageConfirmed(DataServiceImpl.java:459)
	at org.eclipse.kura.core.data.transport.mqtt.DataTransportListenerS.onMessageConfirmed(DataTransportListenerS.java:257)
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.deliveryComplete(MqttDataTransport.java:634)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleActionComplete(CommsCallback.java:268)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:197)
	at java.lang.Thread.run(Thread.java:748)
2020-12-04T14:37:28,886 [MQTT Call: B8:27:EB:61:19:18] ERROR o.e.k.c.d.DataServiceImpl - Cannot confirm message to store
org.eclipse.kura.KuraStoreException: "Error performing operation on store. Cannot update timestamp"
	at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:609)
	at org.eclipse.kura.core.data.store.DbDataStore.updateTimestamp(DbDataStore.java:501)
	at org.eclipse.kura.core.data.store.DbDataStore.confirmed(DbDataStore.java:400)
	at org.eclipse.kura.core.data.DataServiceImpl.onMessageConfirmed(DataServiceImpl.java:459)
	at org.eclipse.kura.core.data.transport.mqtt.DataTransportListenerS.onMessageConfirmed(DataTransportListenerS.java:257)
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.deliveryComplete(MqttDataTransport.java:634)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleActionComplete(CommsCallback.java:268)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:197)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1557)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:561)
	at org.h2.jdbcx.JdbcXAConnection.getConnection(JdbcXAConnection.java:106)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:236)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at org.eclipse.kura.core.db.H2DbServiceImpl.getConnectionInternal(H2DbServiceImpl.java:320)
	at org.eclipse.kura.core.db.H2DbServiceImpl.withConnection(H2DbServiceImpl.java:161)
	at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:607)
	... 8 more
2020-12-04T14:37:28,889 [MQTT Call: B8:27:EB:61:19:18] ERROR o.e.k.c.d.DataServiceImpl - Confirmed Message with ID 66 could not be loaded from the DataStore.
2020-12-04T14:37:28,909 [DataServiceImpl:Submit] WARN  o.e.k.c.d.H2DbServiceImpl - Db operation failed
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "org.eclipse.kura.data.DataService" not found; SQL statement:
SELECT a.id, a.topic, a.qos, a.retain, a.createdOn, a.publishedOn, a.publishedMessageId, a.confirmedOn, a.payload, a.priority, a.sessionId, a.droppedOn FROM "org.eclipse.kura.data.DataService" AS a JOIN (SELECT id, publishedOn FROM "org.eclipse.kura.data.DataService" ORDER BY publishedOn ASC NULLS FIRST, priority ASC, createdOn ASC LIMIT 1) AS b WHERE a.id = b.id AND b.publishedOn IS NULL; [42102-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.readTableOrView(Parser.java:7146)
	at org.h2.command.Parser.readTableFilter(Parser.java:1895)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2641)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2788)
	at org.h2.command.Parser.parseSelectSub(Parser.java:2636)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:2469)
	at org.h2.command.Parser.parseSelect(Parser.java:2440)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at org.eclipse.kura.core.data.store.DbDataStore.lambda$3(DbDataStore.java:363)
	at org.eclipse.kura.core.db.H2DbServiceImpl.withConnection(H2DbServiceImpl.java:162)
	at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:607)
	at org.eclipse.kura.core.data.store.DbDataStore.getNextMessage(DbDataStore.java:362)
	at org.eclipse.kura.core.data.DataServiceImpl$PublishManager.run(DataServiceImpl.java:773)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-12-04T14:37:28,913 [DataServiceImpl:Submit] ERROR o.e.k.c.d.DataServiceImpl - Probably an unrecoverable exception
org.eclipse.kura.KuraStoreException: "Error performing operation on store. Cannot get message next message"
	at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:609)
	at org.eclipse.kura.core.data.store.DbDataStore.getNextMessage(DbDataStore.java:362)
	at org.eclipse.kura.core.data.DataServiceImpl$PublishManager.run(DataServiceImpl.java:773)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "org.eclipse.kura.data.DataService" not found; SQL statement:
SELECT a.id, a.topic, a.qos, a.retain, a.createdOn, a.publishedOn, a.publishedMessageId, a.confirmedOn, a.payload, a.priority, a.sessionId, a.droppedOn FROM "org.eclipse.kura.data.DataService" AS a JOIN (SELECT id, publishedOn FROM "org.eclipse.kura.data.DataService" ORDER BY publishedOn ASC NULLS FIRST, priority ASC, createdOn ASC LIMIT 1) AS b WHERE a.id = b.id AND b.publishedOn IS NULL; [42102-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.readTableOrView(Parser.java:7146)
	at org.h2.command.Parser.readTableFilter(Parser.java:1895)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2641)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2788)
	at org.h2.command.Parser.parseSelectSub(Parser.java:2636)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:2469)
	at org.h2.command.Parser.parseSelect(Parser.java:2440)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at org.eclipse.kura.core.data.store.DbDataStore.lambda$3(DbDataStore.java:363)
	at org.eclipse.kura.core.db.H2DbServiceImpl.withConnection(H2DbServiceImpl.java:162)
	at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:607)
	... 5 more
```

**Additional Info:**
- after those errors in getting new errors when starting Kura service:
```
2020-12-04T14:11:56,312 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: Comtrade/B8:27:EB:61:19:18/EXAMPLE_PUBLISHER/data/metrics with QoS: 0
2020-12-04T14:11:57,297 [pool-33-thread-1] ERROR o.e.k.e.p.ExamplePublisher - Cannot publish: 
org.eclipse.kura.KuraStoreException: "Error performing operation on store. Cannot get message count"
	at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:609)
	at org.eclipse.kura.core.data.store.DbDataStore.getMessageCount(DbDataStore.java:234)
	at org.eclipse.kura.core.data.store.DbDataStore.store(DbDataStore.java:265)
	at org.eclipse.kura.core.data.DataServiceImpl.publish(DataServiceImpl.java:529)
	at org.eclipse.kura.core.cloud.CloudServiceImpl.publish(CloudServiceImpl.java:994)
	at org.eclipse.kura.core.cloud.publisher.CloudPublisherImpl.publish(CloudPublisherImpl.java:171)
	at org.eclipse.kura.example.publisher.ExamplePublisher.doPublish(ExamplePublisher.java:207)
	at org.eclipse.kura.example.publisher.ExamplePublisher.access$0(ExamplePublisher.java:170)
	at org.eclipse.kura.example.publisher.ExamplePublisher$1.run(ExamplePublisher.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1557)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:561)
	at org.h2.jdbcx.JdbcXAConnection.getConnection(JdbcXAConnection.java:106)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:236)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at org.eclipse.kura.core.db.H2DbServiceImpl.getConnectionInternal(H2DbServiceImpl.java:320)
	at org.eclipse.kura.core.db.H2DbServiceImpl.withConnection(H2DbServiceImpl.java:161)
	at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:607)
	... 15 more
```

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3
 - OS version: latest (updated) raspbian pi os

**Comment by MMaiero** [comment]
Is this still an issue? In any case, I believe that this can happen during the shutdown phase.
