### ISSUE TITLE
Unable to connect to the Cloud 

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#3247]
**Describe the bug**
After I configure org.eclipse.kura.cloud.CloudService cloud service (url, topic, username, password and clientID) and do connect. I got connected but immediately disconnected from the cloud. 

**To Reproduce**
1. Go to Cloud Connection item
2. Click on MqttDataTransport tab
3. Set url, topic, username, password and clientID
4. Click on Connect button

**Expected behavior**
I should not be disconnected immediately.

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3
 - OS version: latest raspbian pi os
 - Latest kura from develop (1902) 

**ERROR from kura.log**
```
2020-12-14T09:39:36,981 [qtp23633960-769] INFO  o.e.k.c.c.ConfigurationServiceImpl - Loading init configurations from: 1607938658991...
2020-12-14T09:39:37,326 [qtp23633960-769] INFO  o.e.k.c.c.ConfigurationServiceImpl - Merging configuration for pid: org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport
2020-12-14T09:39:37,356 [qtp23633960-769] INFO  o.e.k.c.c.ConfigurationServiceImpl - Updating Configuration of ConfigurableComponent org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport ... Done.
2020-12-14T09:39:37,367 [ConfigurationListener Event Queue] INFO  o.e.k.c.d.t.m.MqttDataTransport - Updating org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport...
2020-12-14T09:39:37,369 [ConfigurationListener Event Queue] INFO  o.e.k.c.d.DataServiceImpl - Notified DataTransportService configuration updating...
2020-12-14T09:39:37,370 [ConfigurationListener Event Queue] WARN  o.e.k.c.d.t.m.MqttDataTransport - MQTT client already disconnected
2020-12-14T09:39:37,370 [ConfigurationListener Event Queue] INFO  o.e.k.c.d.t.m.MqttDataTransport - Building new configuration...
2020-12-14T09:39:37,372 [ConfigurationListener Event Queue] INFO  o.e.k.c.d.DataServiceImpl - Notified DataTransportService configuration updated.
2020-12-14T09:39:37,461 [qtp23633960-769] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/user/snapshots/snapshot_1607938777357.xml...
2020-12-14T09:39:37,504 [qtp23633960-769] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/user/snapshots/snapshot_1607938777357.xml... Done.
2020-12-14T09:39:41,138 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - Creating a new client instance
2020-12-14T09:39:41,139 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - Using memory persistence for in-flight messages
2020-12-14T09:39:41,240 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - # ------------------------------------------------------------
2020-12-14T09:39:41,240 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connection Properties
2020-12-14T09:39:41,240 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  broker    = tcp://broker-sandbox.everyware-cloud.com:1883
2020-12-14T09:39:41,241 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  clientId  = B8:27:EB:61:19:18
2020-12-14T09:39:41,241 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  username  = dut_broker
2020-12-14T09:39:41,242 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  password  = XXXXXXXXXXXXXX
2020-12-14T09:39:41,242 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  keepAlive = 30
2020-12-14T09:39:41,242 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  timeout   = 20
2020-12-14T09:39:41,243 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  cleanSession    = true
2020-12-14T09:39:41,243 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  MQTT version    = 3.1.1
2020-12-14T09:39:41,243 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willDestination = $EDC/Comtrade/B8:27:EB:61:19:18/MQTT/LWT
2020-12-14T09:39:41,244 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willMessage     =
2020-12-14T09:39:41,244 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #
2020-12-14T09:39:41,244 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connecting...
2020-12-14T09:39:41,246 [pool-21-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED fast blinking
2020-12-14T09:39:42,465 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connected!
2020-12-14T09:39:42,465 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - # ------------------------------------------------------------
2020-12-14T09:39:42,466 [pool-21-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED on
2020-12-14T09:39:42,466 [qtp23633960-769] INFO  o.e.k.c.d.DataServiceImpl - Notified connected
2020-12-14T09:39:42,466 [pool-21-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED off
2020-12-14T09:39:42,467 [pool-21-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED on
2020-12-14T09:39:42,467 [qtp23633960-769] INFO  o.e.k.c.d.DataServiceImpl - New session established. Unpublishing all in-flight messages. Disregarding the QoS level, this may cause duplicate messages.
2020-12-14T09:39:42,981 [qtp23633960-769] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic: $EDC/#account-name/#client-id/MQTT/BIRTH, priority: 0
2020-12-14T09:39:43,069 [qtp23633960-769] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic: $EDC/#account-name/#client-id/MQTT/BIRTH, priority: 0
2020-12-14T09:39:43,101 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: $EDC/Comtrade/B8:27:EB:61:19:18/MQTT/BIRTH with QoS: 0
2020-12-14T09:39:43,123 [qtp23633960-769] INFO  o.e.k.c.d.t.m.MqttDataTransport - Subscribing to topic: $EDC/Comtrade/B8:27:EB:61:19:18/# with QoS: 1
2020-12-14T09:39:43,469 [MQTT Call: B8:27:EB:61:19:18] INFO  o.e.k.c.c.CloudServiceImpl - Message arrived on topic: $EDC/Comtrade/B8:27:EB:61:19:18/BA/BIRTH
2020-12-14T09:39:43,471 [MQTT Call: B8:27:EB:61:19:18] INFO  o.e.k.c.c.CloudServiceImpl - Ignoring feedback message from $EDC/Comtrade/B8:27:EB:61:19:18/BA/BIRTH
2020-12-14T09:39:47,131 [MQTT Call: B8:27:EB:61:19:18] INFO  o.e.k.c.c.CloudServiceImpl - Message arrived on topic: $EDC/Comtrade/B8:27:EB:61:19:18/MQTT/CONNECT
2020-12-14T09:39:47,135 [MQTT Call: B8:27:EB:61:19:18] INFO  o.e.k.c.c.CloudServiceImpl - Ignoring feedback message from $EDC/Comtrade/B8:27:EB:61:19:18/MQTT/CONNECT
2020-12-14T09:39:47,139 [DataServiceImpl:Submit] INFO  o.e.k.c.d.DataServiceImpl - DataPublisherService not connected
2020-12-14T09:39:47,140 [MQTT Rec: B8:27:EB:61:19:18] WARN  o.e.k.c.d.t.m.MqttDataTransport - Connection Lost
Connection lost (32109) - java.io.EOFException
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:189)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:136)
        ... 1 more
2020-12-14T09:39:47,152 [MQTT Rec: B8:27:EB:61:19:18] INFO  o.e.k.c.d.DataServiceImpl - connectionLost
2020-12-14T09:39:47,153 [pool-21-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED off
```

**Comment by mstankovic** [comment]
problem was since two devices use same clientID to connect on the cloud. Closing.
