### ISSUE TITLE
Camel: java.lang.OutOfMemoryError after a long time of execution

### ISSUE THREAD

**Issue by mariosanroman** [eclipse/kura#3308]
Hello everyone.

I don't know if this is a bug or if it is that I'm doing something wrong. I hope someone could help me.

I'm basically following the example in https://dentrassi.de/2018/09/14/the-power-of-apache-camel-in-eclipse-kura/

I have kura installed in a raspberry pi 3 with this O.S.:
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

I set up a wire with a timer with 1 second interval linked to a Camel Producer with this configuration:

![Captura de pantalla 2021-03-03 a las 13 04 49](https://user-images.githubusercontent.com/5113316/109803200-0c79b580-7c21-11eb-8a94-eac62c5d8589.png)

The ID of the Camel Context: camel1
Endpoint URI: seda:input1

![Captura de pantalla 2021-03-03 a las 13 07 23](https://user-images.githubusercontent.com/5113316/109803502-6a0e0200-7c21-11eb-93c3-60d78fd3c434.png)

camel1 is a Configurable Camel-based XML router with this configuration:

Router XML:
```xml
<routes xmlns="http://camel.apache.org/schema/spring">
    <route>
        <from uri="seda:input1"/>
        <to uri="stream:out"/>
    </route>
</routes>
```
Required Camel Components:
stream

![Captura de pantalla 2021-03-03 a las 13 08 06](https://user-images.githubusercontent.com/5113316/109803580-80b45900-7c21-11eb-8cb2-602f2906576e.png)

Everything seems to work fine. I see the expected outputs in the kura console just as the previous post says I should.

The problem is that I get this in the kura-console.log if I leave it executing for a long time (maybe an hour or more)

```shell
Mar 03, 2021 12:23:02 PM org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache scheduleDrainBuffers
WARNING: Exception thrown when submitting maintenance task
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)
	at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)
	at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1634)
	at java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:2367)
	at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2419)
	at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleDrainBuffers(BoundedLocalCache.java:1080)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleAfterWrite(BoundedLocalCache.java:1047)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.afterWrite(BoundedLocalCache.java:1017)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1664)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1612)
	at org.apache.camel.util.LRUCache.put(LRUCache.java:163)
	at org.apache.camel.impl.ProducerCache.doGetProducer(ProducerCache.java:593)
	at org.apache.camel.impl.ProducerCache.doInAsyncProducer(ProducerCache.java:410)
	at org.apache.camel.impl.ProducerCache.asyncSendExchange(ProducerCache.java:309)
	at org.apache.camel.impl.DefaultProducerTemplate.lambda$asyncSendExchange$3(DefaultProducerTemplate.java:667)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

org.eclipse.kura.wire.WireEnvelope@b1d13f
Mar 03, 2021 12:23:12 PM org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache scheduleDrainBuffers
WARNING: Exception thrown when submitting maintenance task
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)
	at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)
	at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1634)
	at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2414)
	at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleDrainBuffers(BoundedLocalCache.java:1080)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:846)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.getIfPresent(BoundedLocalCache.java:1559)
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.get(BoundedLocalCache.java:1530)
	at org.apache.camel.util.LRUCache.get(LRUCache.java:132)
	at org.apache.camel.impl.DefaultEndpointRegistry.get(DefaultEndpointRegistry.java:65)
	at org.apache.camel.impl.DefaultEndpointRegistry.get(DefaultEndpointRegistry.java:37)
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:693)
	at org.apache.camel.builder.DefaultFluentProducerTemplate.to(DefaultFluentProducerTemplate.java:207)
	at org.eclipse.kura.wire.camel.CamelProduce.processReceive(CamelProduce.java:26)
	at org.eclipse.kura.wire.camel.AbstractReceiverWireComponent.processReceive(AbstractReceiverWireComponent.java:46)
	at org.eclipse.kura.wire.camel.AbstractReceiverWireComponent.lambda$0(AbstractReceiverWireComponent.java:30)
	at org.eclipse.kura.wire.camel.AbstractCamelWireComponent.withContext(AbstractCamelWireComponent.java:96)
	at org.eclipse.kura.wire.camel.AbstractReceiverWireComponent.onWireReceive(AbstractReceiverWireComponent.java:28)
	at org.eclipse.kura.internal.wire.helper.WireSupportImpl.updated(WireSupportImpl.java:164)
	at org.eclipse.kura.wire.camel.AbstractWireComponent.updated(AbstractWireComponent.java:67)
	at org.eclipse.equinox.internal.wireadmin.WireImpl.update(WireImpl.java:193)
	at org.eclipse.kura.internal.wire.helper.WireSupportImpl$EmitterPortImpl.emit(WireSupportImpl.java:196)
	at org.eclipse.kura.internal.wire.helper.WireSupportImpl.emit(WireSupportImpl.java:126)
	at org.eclipse.kura.internal.wire.timer.EmitJob.execute(EmitJob.java:63)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

and I can't browse to kura webpage anymore.
I get this in kura.log

```shell
2021-03-03T12:23:56,500 [qtp14760581-96] WARN  o.e.j.u.t.QueuedThreadPool -
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:543)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:49)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:728)
	at java.lang.Thread.run(Thread.java:748)
2021-03-03T12:23:56,505 [qtp14760581-96] WARN  o.e.j.u.t.QueuedThreadPool - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@1ca45fa in QueuedThreadPool[qtp14760581]@e13a85{STARTED,8<=8<=200,i=0,q=1}[ReservedThreadExecutor@30be0c{s=0/4,p=1}]
```

I check the memory with free -m and It seems that there is memory available:

![Captura de pantalla 2021-03-03 a las 13 26 44](https://user-images.githubusercontent.com/5113316/109805737-1bae3280-7c24-11eb-8c3a-fce82739e13f.png)

I also notice that there are a lot of processes for java.

I check the number of threads for kura:

![Captura de pantalla 2021-03-03 a las 13 28 50](https://user-images.githubusercontent.com/5113316/109805973-65971880-7c24-11eb-8641-426c590d01fe.png)

I think 2200 is a very high number.

If I stop kura and try to start it again I get an error, and I have to terminate kura with kill -9 in order to be able to start it again.

If I check the number of threads just after stating kura:

![Captura de pantalla 2021-03-03 a las 13 36 12](https://user-images.githubusercontent.com/5113316/109806857-78f6b380-7c25-11eb-9fa1-975473b146a4.png)

The number is considerably lower (165 in this case). If I watch the number of threads I can confirm that it is always going up.

I have discovered a way for camel to "release" the number of threads, all you have todo is make a change in the camel context and click in apply. It doesn't have to be a meaningful change, just and space at the beginning will do. After clicking apply button the number of threads for kura will go down.

Am I doing something wrong or is there a problem somewhere else with the threads?

**Comment by MMaiero** [comment]
Hi @ctron, any clue on this issue?

Thanks.
Matteo

**Comment by ctron** [comment]
Good question. It would be helpful to know which threads are running. Attaching to the running instance using JMX (e.g. jconsole) and dump the threads.

**Comment by MMaiero** [comment]
> Good question. It would be helpful to know which threads are running. Attaching to the running instance using JMX (e.g. jconsole) and dump the threads.

@mariosanroman can you please provide the details requested by @ctron? Thanks

**Comment by mariosanroman** [comment]
> > Good question. It would be helpful to know which threads are running. Attaching to the running instance using JMX (e.g. jconsole) and dump the threads.
> 
> @mariosanroman can you please provide the details requested by @ctron? Thanks

I'm glad to do that, but I'm afraid I'm going to need some instructions.

How do I enable JMX for Kura in my raspberry?
or I should use this container (https://github.com/ctron/kura-container) with JMX enabled?

**Comment by mariosanroman** [comment]
> > > Good question. It would be helpful to know which threads are running. Attaching to the running instance using JMX (e.g. jconsole) and dump the threads.
> > 
> > 
> > @mariosanroman can you please provide the details requested by @ctron? Thanks
> 
> I'm glad to do that, but I'm afraid I'm going to need some instructions.
> 
> How do I enable JMX for Kura in my raspberry?
> or I should use this container (https://github.com/ctron/kura-container) with JMX enabled?

Hi. I tried to use the container (https://github.com/ctron/kura-container) with JMX enabled in my PC (not in api), but I couldn't connect with jconsole. I don't know if I was doing something wrong.

Could someone give me some information about how to get what @ctron is asking for, please?

**Comment by spnettec** [comment]
CamelProduce should use send not asyncSend. 

or use singleton FluentProducerTemplate. DefaultFluentProducerTemplate.on will ganarate a new DefaultProducerTemplate instance and asyncSend will ganarate a new DefaultThreadPool called "ProducerTemplate" and never shut down 

```

public class CamelProduce extends AbstractReceiverWireComponent {

    private FluentProducerTemplate template = null;

    @Override
    protected void processReceive(final CamelContext context, final String endpointUri, final WireEnvelope envelope)
            throws Exception {
        if (template == null) {
            template = on(context);
        } else {
            if (template.getCamelContext() != context) {
                template.close();
                template = on(context);
            }
        }
        template //
                .withBody(envelope) //
                .to(endpointUri) //
                .asyncSend();
    }

    @Override
    protected void deactivate() {
        super.deactivate();
        if (template != null) {
            try {
                template.close();
            } catch (Exception e) {
            } finally {
                template = null;
            }
        }
    }

}



```

**Comment by MMaiero** [comment]
Hello,
thanks for letting us know that.
Is it possible for you @spnettec to create a PR with the fix?

Thanks.
Matteo
