### ISSUE TITLE
Getting properties fails with BLE

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#3624]
**Describe the bug**

~~~
java.lang.IllegalArgumentException: No enum constant org.eclipse.kura.bluetooth.le.BluetoothLeGattCharacteristicProperties.WRITE-WITHOUT-RESPONSE
        at java.base/java.lang.Enum.valueOf(Enum.java:240)
        at org.eclipse.kura.bluetooth.le.BluetoothLeGattCharacteristicProperties.valueOf(BluetoothLeGattCharacteristicProperties.java:1)
        at org.eclipse.kura.internal.ble.BluetoothLeGattCharacteristicImpl.getProperties(BluetoothLeGattCharacteristicImpl.java:171)
        at de.dentrassi.kura.examples.ble.microbit.MicrobitComponent.refreshDevice(MicrobitComponent.java:249)
        at de.dentrassi.kura.examples.ble.microbit.MicrobitComponent.refreshData(MicrobitComponent.java:193)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
~~~

**To Reproduce**

~~~java
        var services = device.findServices();
        for (var service : services) {
            logger.info("\tService - {}", service.getUUID());
            var chars = service.findCharacteristics();
            for (var c : chars) {
                logger.info("\t\tCharacteristic: {} - {}", c.getUUID(), c.getValue());
                for (var p : c.getProperties()) {
                    logger.info("\t\t\t{}", p.getCode());
                }
            }
        }
~~~

**Expected behavior**

Not fail.

**Target Environment (please complete the following information):**
 - Raspberry Pi 3 / Container

**Comment by pierantoniomerlino** [comment]
It seems that the property in Kura is WRITE_WITHOUT_RESPONSE, not WRITE-WITHOUT-RESPONSE...
