### ISSUE TITLE
JAXB crashes on JAVA 8

### ISSUE THREAD

**Issue by robertodamiani** [eclipse/kura#3663]
**Describe the bug**
JAXB crashes with a `NullPointerException` after the introduction of jakarta bundles in commit 90794b1b.

**To Reproduce**
1. use this snippet:
```java
JAXBContext jaxbContext = JAXBContext.newInstance(MyPojo.class);
```
2. JAXB crashes with the following stack:
```java
java.lang.NullPointerException
        at javax.xml.bind.ContextFinder.handleClassCastException(ContextFinder.java:114)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:254)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:240)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:375)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
        ...

```

**Expected behavior**
In the previous commit, no crash happens.

**Target Environment (please complete the following information):**
Tested with OpenJDK 1.8.0_302
```
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Zulu 8.56.0.21-CA-linux64) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.21-CA-linux64) (build 25.302-b08, mixed mode)

```

**Comment by nicolatimeus** [comment]
Hi, we noticed that the following bundle is referenced in the target platform and in the test runtime but not in kura distribution:

https://github.com/eclipse/kura/blob/ca623dcfc9304522ebf724a483e9f8a66deb00e0/target-platform/config/kura.target-platform.build.properties#L76

Can you please verify if including the bundle above in the distribution has any effect regarding your issue?
Thanks

**Comment by robertodamiani** [comment]
Hi @nicolatimeus,

we added the above line in `kura/distrib/config/kura.build.properties` and we compiled again, with no difference.

In a different test we also tried adding all jakarta related lines, but this too made no difference.

**Comment by nicolatimeus** [comment]
Hi,
Have you also modified [1] to add jaxb-osgi jar to the distribution and the corresponding reference in config.ini as done for the other jakarta bundles?

[1] https://github.com/eclipse/kura/blob/develop/kura/distrib/src/main/ant/build_equinox_distrib.xml

**Comment by robertodamiani** [comment]
Hi @nicolatimeus,

we also added this entry in the `config.ini` block of the `build_equinox_distrib.xml` file:

```
<entry key="osgi.bundles" operation="+"
    value=", reference:file:${kura.install.dir}/${kura.symlink}/${plugins.folder}/com.sun.xml.bind.jaxb-osgi_${jaxb-osgi.version}.jar@2" />
```

This made no difference too.

**Comment by MMaiero** [comment]
Hello,
what is the target used?
What profile are you using?
I am testing that with a raspberry pi freshly installed with java 8 212 and I have modified the heater demo to match what you put In the initial comment. But I was not able to recreate it.

Can you give me more pointers?

Matteo

**Comment by robertodamiani** [comment]
Hi @MMaiero,
we tested in a vanilla environment with these specs:
```
[OS]
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish

[JAVA]
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-8u302-b08-0ubuntu2-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)

[KURA]
profile: intel-up2-ubuntu-20
version: kura_5.1.0-SNAPSHOT compiled from develop with last commit f18c0c94a289d6e6aa61746d0d11d320ef478790
```

To test the problem we created a bundle with a single class doing a JAXB context initialization in the activate method:
```java
package org.eclipse.kura.jaxbtest;

import org.osgi.service.component.ComponentContext;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Deactivate;
import org.slf4j.Logger;

import javax.xml.bind.JAXBContext;

@Component(immediate = true, service = JAXBTestService.class)
public class JAXBTestService {

    private static final Logger log = org.slf4j.LoggerFactory.getLogger(JAXBTestService.class);

    @Activate
    private void activate(final ComponentContext componentContext) {
        log.info("Activating JAXBTestService");
        try {
            JAXBContext.newInstance(JAXBTestService.class);
        } catch (Exception e) {
            log.error("Error while getting JAXBContext instance", e);
        }
    }

    @Deactivate
    private void deactivate(final ComponentContext componentContext) {
        log.info("Deactivating JAXBTestService");
    }

}
```

The JAXB initialization in the activate method immediately crashes with a `NullPointerException`.
Here is the stacktrace:
```
2021-11-18T18:33:20,912 [Refresh Thread: Equinox Container: b39ff705-f631-4a15-b61b-f3b3d15f300b] INFO  e.w.k.p.JAXBTestService - Activating JAXBTestService
2021-11-18T18:33:20,913 [Refresh Thread: Equinox Container: b39ff705-f631-4a15-b61b-f3b3d15f300b] ERROR e.w.k.p.JAXBTestService - Error while getting JAXBContext instance
java.lang.NullPointerException
        at javax.xml.bind.ContextFinder.handleClassCastException(ContextFinder.java:114)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:254)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:240)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:375)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
        at org.eclipse.kura.jaxbtest.JAXBTestService.activate(JAXBTestService.java:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510)
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317)
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:340)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:982)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:900)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:216)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:213)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:547)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:533)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:656)
        at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:120)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:957)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:936)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:873)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:141)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:261)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:496)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:906)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:892)
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:959)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:732)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432)
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665)
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:338)
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:382)
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49)
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:264)
        at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:945)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:232)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:499)
        at org.eclipse.osgi.container.Module.start(Module.java:486)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:506)
        at org.eclipse.osgi.container.ModuleContainer.start(ModuleContainer.java:886)
        at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:877)
        at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:559)
        at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:502)
        at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1137)
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1518)
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

Hope this is more helpful.

Thank you.

**Comment by MMaiero** [comment]
Hi @robertodamiani 
I have created PR #3692. Could you please check if this solves your issue?

Thanks.

**Comment by robertodamiani** [comment]
hi @MMaiero,

I confirm that this solved the problem.

Thank you.
