### ISSUE TITLE
Jetty errors while working with Wire Graph

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#3733]
**Describe the bug**
From time to time Im getting jetty errors while Im working with Wire Graphs. Find them bellow. P.S. I dont have exact steps to reproduce those errors.

error1:

```
2021-12-27T10:21:38,165 [qtp30344791-139] INFO  o.e.k.w.s.s.WiresBlinkServlet - Session ended: 1640600197877
2021-12-27T10:22:12,172 [qtp30344791-325967] INFO  o.e.k.w.s.s.WiresBlinkServlet - Session ended: 1640599929279
2021-12-27T10:22:15,197 [qtp30344791-323670] INFO  o.e.k.w.s.s.WiresBlinkServlet - Session started: 1640599929279
2021-12-27T10:22:30,175 [qtp30344791-325923] INFO  o.e.k.w.s.s.WiresBlinkServlet - Session ended: 1640600249916
2021-12-27T10:22:30,181 [qtp30344791-325923] WARN  o.e.k.w.s.s.WiresBlinkServlet - failed to close stream
org.eclipse.jetty.io.EofException
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:279)
        at org.eclipse.jetty.io.ssl.SslConnection.networkFlush(SslConnection.java:474)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1080)
        at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381)
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:829)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:550)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:915)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:987)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.write(GzipHttpOutputInterceptor.java:113)
        at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:285)
        at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:638)
        at org.eclipse.equinox.http.servlet.internal.servlet.HttpServletResponseWrapperImpl$InternalOutputStream.close(HttpServletResponseWrapperImpl.java:122)
        at org.eclipse.kura.web.server.servlet.WiresBlinkServlet$RequestContext.run(WiresBlinkServlet.java:276)
        at org.eclipse.kura.web.server.servlet.WiresBlinkServlet.doGet(WiresBlinkServlet.java:181)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1459)
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:159)
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:67)
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:117)
        at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.dispatch(ProxyServlet.java:147)
        at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.preprocess(ProxyServlet.java:115)
        at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:104)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:305)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.IOException: Broken pipe
        at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:148)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:506)
        at java.base/java.nio.channels.SocketChannel.write(SocketChannel.java:507)
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:273)
        ... 64 more
```

error2:

```
2021-12-27T10:49:26,810 [qtp30344791-334587] WARN  o.e.k.w.s.s.WiresBlinkServlet - failed to close stream
java.io.IOException: Close SendCallback@18b0a0c[PROCESSING][i=null,cb=org.eclipse.jetty.server.HttpChannel$SendCallback@8634fb] in state PROCESSING
        at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:428)
        at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:519)
        at org.eclipse.jetty.io.ssl.SslConnection.onClose(SslConnection.java:363)
        at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:345)
        at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:1104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by MMaiero** [comment]
Hi @mstankovic 
can you please detail the environment that is causing the issue?
Is it from develop?

**Comment by spnettec** [comment]
public void confirmIfUiDirty(final Runnable action) {
        this.wiresBinder.unload();     //  When switch tab should unload blink whtever blink is active. Add this line. 
        if (isUiDirty()) {
            this.alertDialog.show(MSGS.deviceConfigDirty(), () -> {
                forceTabsCleaning();
                action.run();
            });
        } else {
            action.run();
        }
    }

**Comment by spnettec** [comment]
This bug has existed for several years. Frequent  switch from Wire Panel will cause the browser very slow. This will generate a lot of wiresBinder eventSource instance

**Comment by spnettec** [comment]
To ensure that there is only one instance. I change the wires_blink.js to this:
```


BlinkEffect.prototype.closeEventSource = function() {
	if (this.eventSource) {
		this.eventSource.close();
		this.eventSource = null;
		var xmlHttp = new XMLHttpRequest();
		xmlHttp.open("GET", "/admin/sse?session=" + this.eventSourceSessionId
				+ "&logout=" + this.eventSourceSessionId, true);
		xmlHttp.send(null);
	}
}

BlinkEffect.prototype.setEnabled = function (enabled) {
	if (typeof EventSource == "undefined") {
		return;
	}
	this.closeEventSource();
	if (enabled) {
		this.eventSourceSessionId = new Date().getTime();
		this.eventSource = new EventSource("/admin/sse?session="
				+ this.eventSourceSessionId);
		var self = this
		this.eventSource.onmessage = function(event) {
			var splitted = event.data.split(' ', 2)
			if (splitted.length !== 2) {
				return
			}
			_.each(self.composer.graph.getElements(), function(c) {
				var wireComponent = c.attributes.wireComponent
				if (wireComponent && wireComponent.pid === splitted[0]) {
					self.fireTransition(c, wireComponent.getPortName(splitted[1], 'out'));
				}
			});
		};
	} 
}

```

**Comment by MMaiero** [comment]
Hi @spnettec 
Do you believe you can contribute your findings with a PR?

Thanks
Matteo
