### ISSUE TITLE
Deployment Package issue in Docker 

### ISSUE THREAD

**Issue by pshashipreetham** [eclipse/kura#3759]
From Kura sending the Kafka Messages to a Kafka Consumer, when the Kura is running through the Linux Emulator(Eclipse Neon IDE) the messages are sent fine and consumer is receiving to 

But when the the DP(Deployment Package) is made and deployed on Kura(running on the docker), shows the below error:

```shell
Exception in thread "Thread-16" java.lang.NoClassDefFoundError: org/apache/kafka/common/serialization/Serializer
    at org.eclipse.kura.example.configurable.ConfigurableExample$1.run(ConfigurableExample.java:52)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.serialization.Serializer cannot be found by org.eclipse.kura.example.configurable_1.0.0.202201251713
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 2 more
```

how can this issue be solved ?

**Comment by MMaiero** [comment]
Hello,
is the org.apache.kafka.common.serialization package defined in your bundle manifest file?
