### ISSUE TITLE
Firewall interface is broken

### ISSUE THREAD

**Issue by robertodamiani** [eclipse/kura#3761]
**Describe the bug**
The firewall interface is broken in some installations.  
A popup shows saying "_GwtNetworkService_Proxy: A generic unrecoverable error happened. Please refer to the device log._"

The bug seems to be related to commit [2ffabeb45c](https://github.com/eclipse/kura/commit/2ffabeb45c0056f199e8867423f8b33264c38b71).
The constructor of the `LinuxDnsSystemD` class searches the system for two files (`/lib/systemd/system/bind9.service` and `/lib/systemd/system/named.service`) and, if none is found, throws an exception.

This breaks the service construction, and I suppose that this results in breaking interfaces requiring that dependency provided by service locator.

Also I can confirm that, if at least one of the two files is present in the system, the Firewall interface does not crash.

**To Reproduce**
1. Be sure that both `/lib/systemd/system/bind9.service` and `/lib/systemd/system/named.service` are not in the system
2. Start and Login to Kura
3. Go to Firewall
4. The popup shows

**Expected behavior**
The interface should not crash.

**Target Environment:**
X64 Laptop
OS version: Ubuntu 20.04 LTS
Kura compiled from develop

**Stacktrace**
```
kura-develop    | 2022-01-27T14:36:51,985 [qtp1826445546-945] WARN  o.e.k.w.s.GwtNetworkServiceImpl - Exception
kura-develop    | org.eclipse.kura.web.shared.GwtKuraException: INTERNAL_ERROR
kura-develop    |       at org.eclipse.kura.web.shared.GwtKuraException.internalError(GwtKuraException.java:112)
kura-develop    |       at org.eclipse.kura.web.server.util.ServiceLocator.getService(ServiceLocator.java:244)
kura-develop    |       at org.eclipse.kura.web.server.util.ServiceLocator.getService(ServiceLocator.java:73)
kura-develop    |       at org.eclipse.kura.web.server.GwtNetworkServiceImpl.privateFindNetInterfaceConfigurations(GwtNetworkServiceImpl.java:151)
kura-develop    |       at org.eclipse.kura.web.server.GwtNetworkServiceImpl.findNetInterfaceConfigurations(GwtNetworkServiceImpl.java:122)
kura-develop    |       at org.eclipse.kura.web.server.GwtStatusServiceImpl.getNetworkStatus(GwtStatusServiceImpl.java:264)
kura-develop    |       at org.eclipse.kura.web.server.GwtStatusServiceImpl.getDeviceConfig(GwtStatusServiceImpl.java:86)
kura-develop    |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
kura-develop    |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
kura-develop    |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kura-develop    |       at java.lang.reflect.Method.invoke(Method.java:498)
kura-develop    |       at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
kura-develop    |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
kura-develop    |       at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.processCall(OsgiRemoteServiceServlet.java:208)
kura-develop    |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
kura-develop    |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
kura-develop    |       at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
kura-develop    |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
kura-develop    |       at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.service(OsgiRemoteServiceServlet.java:95)
kura-develop    |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
kura-develop    |       at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1459)
kura-develop    |       at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:159)
kura-develop    |       at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:67)
kura-develop    |       at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:117)
kura-develop    |       at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.dispatch(ProxyServlet.java:147)
kura-develop    |       at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.preprocess(ProxyServlet.java:115)
kura-develop    |       at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:104)
kura-develop    |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
kura-develop    |       at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:305)
kura-develop    |       at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
kura-develop    |       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
kura-develop    |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
kura-develop    |       at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:713)
kura-develop    |       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
kura-develop    |       at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
kura-develop    |       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
kura-develop    |       at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
kura-develop    |       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
kura-develop    |       at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
kura-develop    |       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
kura-develop    |       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
kura-develop    |       at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
kura-develop    |       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
kura-develop    |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
kura-develop    |       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
kura-develop    |       at org.eclipse.jetty.server.Server.handle(Server.java:516)
kura-develop    |       at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
kura-develop    |       at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
kura-develop    |       at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
kura-develop    |       at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
kura-develop    |       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
kura-develop    |       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
kura-develop    |       at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
kura-develop    |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
kura-develop    |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
kura-develop    |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
kura-develop    |       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
kura-develop    |       at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
kura-develop    |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
kura-develop    |       at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
kura-develop    |       at java.lang.Thread.run(Thread.java:748)
```

**Comment by MMaiero** [comment]
Hello,
bind9 and named are Kura dependencies. That is the reason why the code, expected to manage the system dns server, shows an exception at boot.
I agree with you that the UI should not fail for the dns, while inspecting the firewall. That should be checked.

Matteo
