### ISSUE TITLE
Sometimes DataService stops working after installing a .dp package on Java 11

### ISSUE THREAD

**Issue by kandrej** [eclipse/kura#4141]
**Describe the bug**
Sometimes DataService stops working after installing a .dp package. 

**To Reproduce**
1. Install/reinstall a .dp package

**Target Environment (please complete the following information):**
 - Any board or OS
 - Java 11

**Additional context**
2022-09-01T08:01:17,480 [DataServiceImpl:Submit] ERROR o.e.k.c.d.DataServiceImpl - Probably an unrecoverable exception
org.eclipse.kura.KuraStoreException: "Error performing operation on store. Cannot get message next message"
        at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:650) ~[org.eclipse.kura.core_1.1.1.jar:?]
        at org.eclipse.kura.core.data.store.DbDataStore.getNextMessage(DbDataStore.java:391) ~[org.eclipse.kura.core_1.1.1.jar:?]
        at org.eclipse.kura.core.data.DataServiceImpl$PublishManager.run(DataServiceImpl.java:770) [org.eclipse.kura.core_1.1.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.LinkageError: loader constraint violation in interface itable initialization for class org.h2.jdbcx.JdbcXAConnection: when selecting method 'javax.transaction.xa.XAResource javax.sql.XAConnection.getXAResource()' the class loader 'platform' for super interface javax.sql.XAConnection, and the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5c45582b of the selected method's class, org.h2.jdbcx.JdbcXAConnection have different Class objects for the type javax.transaction.xa.XAResource used in the signature (javax.sql.XAConnection is in module java.sql of loader 'platform'; org.h2.jdbcx.JdbcXAConnection is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5c45582b, parent loader 'platform')
        at org.eclipse.kura.core.db.H2DbServiceImpl.withConnection(H2DbServiceImpl.java:224) ~[org.eclipse.kura.core_1.1.1.jar:?]
        at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:648) ~[org.eclipse.kura.core_1.1.1.jar:?]
        ... 5 more
Caused by: java.util.concurrent.ExecutionException: java.lang.LinkageError: loader constraint violation in interface itable initialization for class org.h2.jdbcx.JdbcXAConnection: when selecting method 'javax.transaction.xa.XAResource javax.sql.XAConnection.getXAResource()' the class loader 'platform' for super interface javax.sql.XAConnection, and the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5c45582b of the selected method's class, org.h2.jdbcx.JdbcXAConnection have different Class objects for the type javax.transaction.xa.XAResource used in the signature (javax.sql.XAConnection is in module java.sql of loader 'platform'; org.h2.jdbcx.JdbcXAConnection is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5c45582b, parent loader 'platform')
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at org.eclipse.kura.core.db.H2DbServiceImpl.withConnection(H2DbServiceImpl.java:214) ~[org.eclipse.kura.core_1.1.1.jar:?]
        at org.eclipse.kura.core.data.store.DbDataStore.withConnection(DbDataStore.java:648) ~[org.eclipse.kura.core_1.1.1.jar:?]
        ... 5 more
Caused by: java.lang.LinkageError: loader constraint violation in interface itable initialization for class org.h2.jdbcx.JdbcXAConnection: when selecting method 'javax.transaction.xa.XAResource javax.sql.XAConnection.getXAResource()' the class loader 'platform' for super interface javax.sql.XAConnection, and the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5c45582b of the selected method's class, org.h2.jdbcx.JdbcXAConnection have different Class objects for the type javax.transaction.xa.XAResource used in the signature (javax.sql.XAConnection is in module java.sql of loader 'platform'; org.h2.jdbcx.JdbcXAConnection is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5c45582b, parent loader 'platform')
        at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:321) ~[com.h2database_2.1.214.jar:2.1.214]
        at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:352) ~[com.h2database_2.1.214.jar:2.1.214]
        at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:233) ~[com.h2database_2.1.214.jar:2.1.214]
        at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:198) ~[com.h2database_2.1.214.jar:2.1.214]
        at org.eclipse.kura.core.db.H2DbServiceImpl.getConnectionInternal(H2DbServiceImpl.java:390) ~[org.eclipse.kura.core_1.1.1.jar:?]
        at org.eclipse.kura.core.db.H2DbServiceImpl.withConnectionInternal(H2DbServiceImpl.java:189) ~[org.eclipse.kura.core_1.1.1.jar:?]
        at org.eclipse.kura.core.db.H2DbServiceImpl.lambda$3(H2DbServiceImpl.java:211) ~[org.eclipse.kura.core_1.1.1.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at org.eclipse.kura.core.db.H2DbServiceImpl.lambda$1(H2DbServiceImpl.java:126) ~[org.eclipse.kura.core_1.1.1.jar:?]
        ... 1 more

**Comment by marcellorinaldo** [comment]
Hi @kandrej! Thanks for the report.

Does it happen on every DP or is it a particular one?

**Comment by MMaiero** [comment]
Any update on this? Is it solved?
