### ISSUE TITLE
Fix Oomph installation, failure of install of SonarLint

### ISSUE THREAD

**Issue by apmcgregor** [eclipse/kura#4171]
**Describe the bug**
Trying to install the Kura development environment via Oomph.
It looks like one of the SonarLint packages has changed

**To Reproduce**
1. Download Oomph install](https://eclipse.github.io/kura/dev/kura-setup.html#oomph-installer)
2. Follow the instructions
3. See error

**Expected behavior**
A clean install of the Kura development environment.
I think it's a name that's changed since the install was last checked.

**Screenshots**
Output from the Oomph console...
ERROR: org.eclipse.equinox.p2.metadata.repository code=1002 Unable to read repository at http://eclipse.sonarlint.org/.
java.io.IOException: http://eclipse.sonarlint.org/ is not a valid repository location.
  at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:103)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:63)
  at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:787)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:119)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:446)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:229)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:518)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$RepositoryLoader$Worker.perform(ProfileTransactionImpl.java:1615)
  at org.eclipse.oomph.util.WorkerPool$Worker.run(WorkerPool.java:437)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Target Environment (please complete the following information):**]
 - OS version: Ubuntu 20.04
 - Additional info: Just a clean install

**Comment by mattdibi** [comment]
Hi there @apmcgregor,

thank you for reaching out and reporting the issue. Looks like I can reproduce it:
![Screenshot 2022-09-20 at 16 00 30](https://user-images.githubusercontent.com/22748355/191282968-401960cd-eba6-45d4-926c-d88b82c70dc6.png)

The new url for the [Sonarlint plugin](https://marketplace.eclipse.org/content/sonarlint) is in fact: `https://eclipse-uc.sonarlint.org`.

While you wait for the fix upstream you should be able to complete the installation by modifying [this line](https://github.com/eclipse/kura/blob/cc3ea18a5c441d80ff802842ddaef24a832b072b/kura/setups/kura.setup#L93) with the updated url and adding the installer file manually during the installation. Does this fix your issue?

**Comment by mattdibi** [comment]
@apmcgregor As noted in the PR please use Eclipse 2022-06 for the installation.

**Comment by apmcgregor** [comment]
Hello,
I made the change you suggested to the file and Kura installed correctly on 2022-06.
Thank you for your help and very quick response,
Andy

**Comment by mattdibi** [comment]
Great! Thanks for the feedback :)
