### ISSUE TITLE
[Web] NPE in GwtNetworkServiceImpl

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#468]
```
2016-08-18 09:11:47,689 [qtp26132825-41] WARN  o.e.k.w.s.GwtNetworkServiceImpl - Exception: org.eclipse.kura.web.shared.GwtKuraException: INTERNAL_ERROR   
2016-08-18 09:11:47,697 [qtp26132825-41] WARN  / - Exception while dispatching incoming RPC call   
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.ArrayList org.eclipse.kura.web.shared.service.GwtStatusService.getDeviceConfig(org.eclipse.kura.web.shared.model.GwtXSRFToken,boolean) throws org.eclipse.kura.web.shared.GwtKuraException' threw an unexpected exception: java.lang.NullPointerException   
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)   
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)   
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)   
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)   
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)   
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)   
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)   
	at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.service(OsgiRemoteServiceServlet.java:44)   
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)   
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)   
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)   
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)   
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)   
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:384)   
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598)   
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)   
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)   
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)   
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)   
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)   
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)   
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)   
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)   
	at org.eclipse.jetty.server.Server.handle(Server.java:350)   
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)   
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:900)   
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:954)   
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:851)   
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)   
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)   
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)   
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)   
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)   
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)   
	at java.lang.Thread.run(Unknown Source)   
Caused by: java.lang.NullPointerException   
	at org.eclipse.kura.web.server.GwtNetworkServiceImpl.findNetInterfaceConfigurations(GwtNetworkServiceImpl.java:109)   
	at org.eclipse.kura.web.server.GwtStatusServiceImpl.getNetworkStatus(GwtStatusServiceImpl.java:171)   
	at org.eclipse.kura.web.server.GwtStatusServiceImpl.getDeviceConfig(GwtStatusServiceImpl.java:56)   
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)   
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)   
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)   
	at java.lang.reflect.Method.invoke(Unknown Source)   
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)   
	... 33 more   
```

**Comment by ibinshtok** [comment]
@cdealti I believe this is the same as kura_eth issue #143 I created last week.

**Comment by cdealti** [comment]
@ibinshtok are you sure it's #143?

**Comment by ibinshtok** [comment]
@cdealti Based on this:
Caused by: java.lang.NullPointerException   
    at org.eclipse.kura.web.server.GwtNetworkServiceImpl.findNetInterfaceConfigurations(GwtNetworkServiceImpl.java:109) 

exception on the same line ...
