### ISSUE TITLE
install modbus package from eclipse market failed

### ISSUE THREAD

**Issue by langlichong** [eclipse/kura#4823]
**Describe the bug**
use docker deployed the kura 5.2.2 , then open admin web ui to install a modbus driver from the menu 'Packages' , when drag the "install" link button to kura ui get an error dialog said : org.eclipse.kura.web.client.ui.EntryClassUi: A generic unrecoverable error happened. Please refer to the device log.

**To Reproduce**
1. login kura web ui  (kura version is 5.2.2)
2. Click on 'Packages' menu button
3. open modbus page  'https://marketplace.eclipse.org/content/modbus-protocol-implementation-eclipse-kura-45' 
4. drag the button 'install' to kura packages page 

**Expected behavior**
can successfully install the suitable modbus package 

**Screenshots**
![5118337F-EA9A-4730-B568-DC24760A9EB4](https://github.com/eclipse/kura/assets/11713419/053ac372-0fef-42fa-8f09-97b7c3d1e13d)

**Target Environment (please complete the following information):**
 - OS version: ubuntu20.04 
 - Additional info: 
     Docker Engine - Community  23.0.6
**Additional context**
kura device log( filesystem-kura-log):
```
2023-08-29T04:05:23	[priority: WARN]
Message: o.e.k.w.s.GwtPackageServiceImpl - failed to get deployment package descriptior from Eclipse Marketplace
Stacktrace: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".

	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)

	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:338)

	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)

	at org.eclipse.kura.web.server.GwtPackageServiceImpl.getMarketplacePackageDescriptor(GwtPackageServiceImpl.java:158)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)

	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)

	at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.processCall(OsgiRemoteServiceServlet.java:208)

	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)

	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)

	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)

	at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.service(OsgiRemoteServiceServlet.java:95)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1459)

	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:159)

	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:67)

	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:117)

	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.dispatch(ProxyServlet.java:147)

	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.preprocess(ProxyServlet.java:115)

	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:104)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:305)

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)

	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:713)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

	at org.eclipse.jetty.server.Server.handle(Server.java:516)

	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)

	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)

	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)

	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)

	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)

	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)

	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)

	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)

	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)

	at java.lang.Thread.run(Thread.java:750)
```

**Comment by salvatore-coppola** [comment]
Theese kind of issues were solved with #4533
