### ISSUE TITLE
[Web UI] Empty Integer field in a configuration (not required) is causing a NumberFormatException

### ISSUE THREAD

**Issue by pierrepitiot** [eclipse/kura#540]
During the development of a modbus application I have to configure several slave addresses that can be left empty. When a field is modified and the configuration applied the following exception is thrown
(this was not the case with kura 1.3 release) :

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.eclipse.kura.web.server.GwtComponentServiceImpl.getObjectValue(GwtComponentServiceImpl.java:325)
	at org.eclipse.kura.web.server.GwtComponentServiceImpl.updateComponentConfiguration(GwtComponentServiceImpl.java:276)

**Comment by MMaiero** [comment]
@pierrepitiot Probably this is solved in #516.
Could you check with the develop build?

**Comment by pierrepitiot** [comment]
Right the issue has been solved. Unfortunately another issue occurs when configuring the RS485 service on a RG10-20:

java.lang.NumberFormatException: For input string: "Half Duplex"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.eclipse.kura.web.server.GwtComponentServiceImpl.getObjectValue(GwtComponentServiceImpl.java:354)
	at org.eclipse.kura.web.server.GwtComponentServiceImpl.updateComponentConfiguration(GwtComponentServiceImpl.java:305)

**Comment by pierrepitiot** [comment]
The bug is occuring on a configuration field using Options:
        <AD id="rs485.port.1"
            name="rs485.port.1"
            type="Integer"
            cardinality="0"
            required="true"
            default="0"
            description="Enable RS485 communication on port /dev/ttymxc1 (Serial1 DB9)">
			<Option label="Disabled" value="0"/>
			<Option label="Half Duplex" value="1"/>          
			<Option label="Full Duplex" value="2"/>
            </AD>
The configuration service is parsing the label rather than the value.

**Comment by MMaiero** [comment]
I think that this issue is now solved by #566: it was caused by commit a3837922a27499f3216f7de2f7def757b30e7f77
Is it ok for you, @pierrepitiot?

**Comment by pierrepitiot** [comment]
Yes the issue is solved for me
