### ISSUE TITLE
Web UI fails with INTERNAL_ERROR when WireHelperService is not registered

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#771]
Currently the Web UI fails with an "INTERNAL_ERROR" when the WireHelperService is not registered with OSGi.

I would suggest to provide a helpful error message and maybe declare a dependency on that service, as it seems that absolutely necessary.

```
org.eclipse.kura.web.shared.GwtKuraException: INTERNAL_ERROR13:45:07,077 [qtp1138879237-29] WARN  KuraExceptionHandler:26  - RPC service non-application error
org.eclipse.kura.web.shared.GwtKuraException: INTERNAL_ERROR
	at org.eclipse.kura.web.shared.GwtKuraException.internalError(GwtKuraException.java:111)
	at org.eclipse.kura.web.server.util.ServiceLocator.getServiceReference(ServiceLocator.java:44)
	at org.eclipse.kura.web.server.util.ServiceLocator.getService(ServiceLocator.java:69)
	at org.eclipse.kura.web.server.GwtComponentServiceImpl.convertComponentConfigurationByOcd(GwtComponentServiceImpl.java:55)
	at org.eclipse.kura.web.server.GwtComponentServiceImpl.findServicesConfigurations(GwtComponentServiceImpl.java:433)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by cdealti** [comment]
@MMaiero @nicolatimeus has this been fixed?

**Comment by MMaiero** [comment]
No. It's a won't fix for now
