### ISSUE TITLE
[Kura 2.1.0 enh] Position of tabs in Kura web UI - configuration 

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#871]
NET-ETH0-003 test case from #788 instructs to
Modify eth0 status...
Configure MqttDataTransport to connect to mqtt://iot.eclipse.org:1883 broker.
Configure DataService to enable connect.auto-on-startup

MqttDataTransport and DataServce are tabs under System->Cloud Services. MqttDataTransport configuration tab's position is right of DataService configuration tab, but DataService seems to depend on MQTT config. In default setup, the configuration of MQTT will not work and if it is enabled in DataService tab. In case last two configuration steps are switched and DataService configuration is applied before MQTT is updated, it will generate errors in kura's log.

**Comment by cdealti** [comment]
In whatever order, the connection should be eventually established.
I usually configure the MqttDataTransport first but it should work in the reverse order.

Can you post the relevant logs?

**Comment by markoer** [comment]
If data service is enabled/connected before the broker is properly configured, the (perfectly expected) exception will occur due to the broker's URL being `tcp://broker-url:1883`. If broker is configured first, this log can be avoided.

```
2016-12-06 15:42:20,406 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.DataServiceImpl - Connecting...
2016-12-06 15:42:20,419 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - # ------------------------------------------------------------
2016-12-06 15:42:20,422 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connection Properties
2016-12-06 15:42:20,425 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  broker    = tcp://broker-url:1883
2016-12-06 15:42:20,438 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  clientId  = B8:27:EB:58:67:20
2016-12-06 15:42:20,441 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  username  = username
...
2016-12-06 15:42:20,810 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask ended.
2016-12-06 15:42:20,827 [DataServiceImpl:ReconnectTask] WARN  o.e.k.c.d.t.m.MqttDataTransport - xxxxx  Connect failed. Forcing disconnect. xxxxx {}
MqttException (0) - java.net.UnknownHostException: broker-url
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:604)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: broker-url
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:590)
        ... 1 more
2016-12-06 15:42:20,864 [pool-9-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED off
2016-12-06 15:42:20,869 [pool-9-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED slow blinking
2016-12-06 15:42:20,872 [DataServiceImpl:ReconnectTask] WARN  o.e.k.c.d.DataServiceImpl - Connect failed
```

**Comment by cdealti** [comment]
This is well known. However if you then set the broker URL in the MqttDataTransport it should connect.
If it doesn't happen, this is a bug. Otherwise I think this could be closed or postponed if you have a suggestion.

**Comment by markoer** [comment]
When the right broker is set, Kura connects to it without further issues. That's why I marked it as an enhancement proposing to maybe switch the 2 tabs (DataService and MqttDataTransport) so that the proper order of configuration is more intuitive.
You may freely close it if you like the order of the tabs as is.

**Comment by cdealti** [comment]
There has already been a long debate on the order of tabs.
The order is the hierarchical order of the Cloud connection stack from the top to the bottom layer.
I believe it's OK to close this.
