### ISSUE TITLE
[Kura 2.1.0 QA] Almost default SSL configuration of MQTT

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#873]
Test case NET-ETH0-004 from #788 specifies use of mqtts://iot.eclipse.org:8883 broker-url (and no other changes). In this case, when the changes are applied the following is logged:

```
2016-11-29 12:26:58,312 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.s.SslManagerServiceImpl - Creating a new SSLSocketFactory instance
2016-11-29 12:26:58,312 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.s.SslManagerServiceImpl - Could not find trust store at /opt/eclipse/kura/security/cacerts.ks. Using Java default.
2016-11-29 12:26:58,507 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.s.SslManagerServiceImpl - Could not find key store at /opt/eclipse/kura/security/cacerts.ks. Using Java default.
2016-11-29 12:26:58,541 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.DataServiceImpl - Notified DataTransportService configuration updated.
2016-11-29 12:26:58,541 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.DataServiceImpl - Starting reconnect task with initial delay 1
2016-11-29 12:26:58,542 [pool-9-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED slow blinking
2016-11-29 12:26:59,541 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.DataServiceImpl - Connecting...
2016-11-29 12:26:59,542 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - Closing client...
2016-11-29 12:26:59,542 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - Closed
2016-11-29 12:26:59,543 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - Creating a new client instance
2016-11-29 12:26:59,543 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - Using memory persistence for in-flight messages
2016-11-29 12:26:59,543 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - # ------------------------------------------------------------
2016-11-29 12:26:59,543 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connection Properties
2016-11-29 12:26:59,544 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  broker    = ssl://iot.eclipse.org:8883
2016-11-29 12:26:59,544 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  clientId  = B8:27:EB:B3:53:03
2016-11-29 12:26:59,544 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  username  = username
2016-11-29 12:26:59,544 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  password  = XXXXXXXXXXXXXX
2016-11-29 12:26:59,544 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  keepAlive = 30
2016-11-29 12:26:59,545 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  timeout   = 20
2016-11-29 12:26:59,545 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  cleanSession    = true
2016-11-29 12:26:59,545 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  MQTT version    = 3.1.1
2016-11-29 12:26:59,545 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willDestination = $EDC/account-name/B8:27:EB:B3:53:03/MQTT/LWT
2016-11-29 12:26:59,545 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willMessage     = 
2016-11-29 12:26:59,545 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #
2016-11-29 12:26:59,546 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connecting...
2016-11-29 12:26:59,546 [pool-9-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED fast blinking
2016-11-29 12:27:04,711 [MQTT Con: B8:27:EB:B3:53:03] INFO  o.e.k.c.s.SSLSocketFactoryWrapper - SSL Endpoint Identification enabled.
2016-11-29 12:27:05,101 [DataServiceImpl:ReconnectTask] WARN  o.e.k.c.d.t.m.MqttDataTransport - xxxxx  Connect failed. Forcing disconnect. xxxxx {}
MqttException (0) - javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:604)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:87)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:590)
        ... 1 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
        ... 10 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
        ... 16 more
2016-11-29 12:27:05,107 [pool-9-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED off
2016-11-29 12:27:05,108 [DataServiceImpl:ReconnectTask] WARN  o.e.k.c.d.DataServiceImpl - Connect failed
```

Kura 2.1.0 build 12, Raspberry Pi 3, Raspbian GNU/Linux 8, `Linux raspberrypi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux`
Java is Oracle's JDK 8:
```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
```

**Comment by MMaiero** [comment]
Which JVM are you using?

**Comment by MMaiero** [comment]
http://stackoverflow.com/questions/34110426/does-java-support-lets-encrypt-certificates

**Comment by cdealti** [comment]
@markoer The workaround is to manually install the CA certificate to the default Java keystore.

BTW, are you using the latest Debian with all the updates?

**Comment by markoer** [comment]
System is as specified in the first comment with Monday's updates.

**Comment by cdealti** [comment]
@markoer can you please to manually install the Let's encrypt certificate and add a note to the validation with the steps needed?

**Comment by markoer** [comment]
I installed on RPI1 and RPi3 and verified that it works with Let's encrypt certificate. I also updated my version of the validation spreadsheet.
Can be closed.
