### ISSUE TITLE
[Kura 2.1.0 QA] exception when enabling DataService

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#904]
Setting the DataService to "autoconnect = true" triggers the following exception in the UI:

```
Wed Dec 07 13:30:34 GMT+100 2016 ErrorLogger INFO: : The operation succeeded only partially.org.eclipse.kura.web.shared.GwtKuraException: The operation succeeded only partially.
   at Unknown.gd(http://puddlejumper/kura)
   at Unknown.pd(http://puddlejumper/kura)
   at Unknown.dZb(http://puddlejumper/kura)
   at Unknown.iZb(http://puddlejumper/kura)
   at Unknown.n3(http://puddlejumper/kura)
   at Unknown.j3(http://puddlejumper/kura)
   at Unknown.I1(http://puddlejumper/kura)
   at Unknown.p2(http://puddlejumper/kura)
   at Unknown.eo(http://puddlejumper/kura)
   at Unknown.so(http://puddlejumper/kura)
   at Unknown.onreadystatechange<(http://puddlejumper/kura)
   at Unknown.je(http://puddlejumper/kura)
   at Unknown.me(http://puddlejumper/kura)
   at Unknown.le/<(http://puddlejumper/kura)
   at Unknown.anonymous(Unknown)
Wed Dec 07 13:30:34 GMT+100 2016 ErrorLogger SEVERE: The operation succeeded only partially.org.eclipse.kura.web.shared.GwtKuraException: The operation succeeded only partially.
   at Unknown.gd(http://puddlejumper/kura)
   at Unknown.pd(http://puddlejumper/kura)
   at Unknown.dZb(http://puddlejumper/kura)
   at Unknown.iZb(http://puddlejumper/kura)
   at Unknown.n3(http://puddlejumper/kura)
   at Unknown.j3(http://puddlejumper/kura)
   at Unknown.I1(http://puddlejumper/kura)
   at Unknown.p2(http://puddlejumper/kura)
   at Unknown.eo(http://puddlejumper/kura)
   at Unknown.so(http://puddlejumper/kura)
   at Unknown.onreadystatechange<(http://puddlejumper/kura)
   at Unknown.je(http://puddlejumper/kura)
   at Unknown.me(http://puddlejumper/kura)
   at Unknown.le/<(http://puddlejumper/kura)
   at Unknown.anonymous(Unknown)
```

In the console I do get:

```
2016-12-07 13:30:33,197 [qtp23600506-27] WARN  o.e.k.c.c.ConfigurationServiceImpl - Error during updateConfigurations for component org.eclipse.kura.data.DataService
org.eclipse.kura.KuraException: Error updating Configuration of ConfigurableComponent org.eclipse.kura.data.DataService
	at org.eclipse.kura.core.configuration.ConfigurationServiceImpl.updateConfigurationInternal(ConfigurationServiceImpl.java:1254)
	at org.eclipse.kura.core.configuration.ConfigurationServiceImpl.updateConfigurationsInternal(ConfigurationServiceImpl.java:618)
	at org.eclipse.kura.core.configuration.ConfigurationServiceImpl.updateConfigurations(ConfigurationServiceImpl.java:266)
	at org.eclipse.kura.core.configuration.ConfigurationServiceImpl.updateConfiguration(ConfigurationServiceImpl.java:247)
	at org.eclipse.kura.core.configuration.ConfigurationServiceImpl.updateConfiguration(ConfigurationServiceImpl.java:238)
	at org.eclipse.kura.web.server.GwtComponentServiceImpl.updateComponentConfiguration(GwtComponentServiceImpl.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.service(OsgiRemoteServiceServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:384)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:350)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:900)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:954)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:851)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.eclipse.equinox.internal.cm.ConfigurationStore.writeConfigurationFile(ConfigurationStore.java:112)
	at org.eclipse.equinox.internal.cm.ConfigurationStore$1.run(ConfigurationStore.java:99)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.equinox.internal.cm.ConfigurationStore.saveConfiguration(ConfigurationStore.java:97)
	at org.eclipse.equinox.internal.cm.ConfigurationImpl.update(ConfigurationImpl.java:255)
	at org.eclipse.kura.core.configuration.ConfigurationServiceImpl.updateComponentConfiguration(ConfigurationServiceImpl.java:1310)
	at org.eclipse.kura.core.configuration.ConfigurationServiceImpl.updateConfigurationInternal(ConfigurationServiceImpl.java:1250)
	... 43 more

```

**Comment by ctron** [comment]
The same error appeared when entering the broker URI. After a reboot it worked again.

**Comment by cdealti** [comment]
@ctron Before starting the QA, have you rebooted at least once after the Kura install?

**Comment by ctron** [comment]
More than once.

This also happened a second time during the testing.

Rebooting seems to fix this though.

**Comment by ctron** [comment]
This did not appear during today's test run. So I guess this is fixed and can be closed.
