### ISSUE TITLE
[Kura 2.1.0 QA] Exceptions while deploying example service

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#912]
While testing DEN-DEPLOY-001 the following exception hit the log file:

```
2016-12-07 15:51:23,529 [qtp23600506-28] INFO  o.e.k.w.s.s.FileServlet - Installing package...
2016-12-07 15:51:23,534 [DeploymentAgent] INFO  o.e.k.d.a.i.DeploymentAgent - About to install package at URL file:/tmp/org.eclipse.kura.example.publisher.dp
2016-12-07 15:51:24,768 [DeploymentAgent] INFO  o.e.k.c.c.ConfigurationServiceImpl - Registering metatype pid: org.eclipse.kura.example.publisher.ExamplePublisher with ocd: org.eclipse.kura.core.configuration.metatype.Tocd@78772c ...
2016-12-07 15:51:24,779 [DeploymentAgent] INFO  o.e.k.c.c.ConfigurationServiceImpl - Merging configuration for pid: org.eclipse.kura.example.publisher.ExamplePublisher
2016-12-07 15:51:24,800 [DeploymentAgent] ERROR o.e.k.c.c.ComponentMetaTypeBundleTracker - Error seeding configuration for pid: org.eclipse.kura.example.publisher.ExamplePublisher
org.eclipse.kura.KuraException: An internal error occurred. {0}
	at org.eclipse.kura.core.configuration.ConfigurationServiceImpl.registerComponentOCD(ConfigurationServiceImpl.java:506)
	at org.eclipse.kura.core.configuration.ComponentMetaTypeBundleTracker.processBundleMetaType(ComponentMetaTypeBundleTracker.java:96)
	at org.eclipse.kura.core.configuration.ComponentMetaTypeBundleTracker.addingBundle(ComponentMetaTypeBundleTracker.java:58)
	at org.eclipse.kura.core.configuration.ComponentMetaTypeBundleTracker.addingBundle(ComponentMetaTypeBundleTracker.java:1)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:467)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:443)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:847)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEventPrivileged(Framework.java:1568)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEvent(Framework.java:1504)
	at org.eclipse.osgi.framework.internal.core.Framework.publishBundleEvent(Framework.java:1499)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:391)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:300)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:292)
	at org.apache.felix.deploymentadmin.spi.StartBundleCommand.execute(StartBundleCommand.java:58)
	at org.apache.felix.deploymentadmin.spi.DeploymentSessionImpl.call(DeploymentSessionImpl.java:73)
	at org.apache.felix.deploymentadmin.DeploymentAdminImpl.installDeploymentPackage(DeploymentAdminImpl.java:214)
	at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.installDeploymentPackageInternal(DeploymentAgent.java:469)
	at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.installer(DeploymentAgent.java:309)
	at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.access$0(DeploymentAgent.java:293)
	at org.eclipse.kura.deployment.agent.impl.DeploymentAgent$1.run(DeploymentAgent.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.eclipse.equinox.internal.cm.ConfigurationStore.writeConfigurationFile(ConfigurationStore.java:112)
	at org.eclipse.equinox.internal.cm.ConfigurationStore$1.run(ConfigurationStore.java:99)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.equinox.internal.cm.ConfigurationStore.saveConfiguration(ConfigurationStore.java:97)
	at org.eclipse.equinox.internal.cm.ConfigurationImpl.update(ConfigurationImpl.java:255)
	at org.eclipse.kura.core.configuration.ConfigurationServiceImpl.updateWithDefaultConfiguration(ConfigurationServiceImpl.java:691)
	at org.eclipse.kura.core.configuration.ConfigurationServiceImpl.registerComponentOCD(ConfigurationServiceImpl.java:504)
	... 29 more
2016-12-07 15:51:24,882 [DeploymentAgent] INFO  o.e.k.d.a.i.DeploymentAgent - Posting INSTALLED event for package at URL file:/tmp/org.eclipse.kura.example.publisher.dp: successful

```

**Comment by ctron** [comment]
The package shows as installed, however the service does not show up.

**Comment by ctron** [comment]
After a reboot (DEN-DEPLOY-003) the service is active.

**Comment by cdealti** [comment]
The log has similarities with #904. SeLinux configuration?

**Comment by ctron** [comment]
I don't know, how can I test it?

**Comment by cdealti** [comment]
@MMaiero any ideas?

**Comment by MMaiero** [comment]
@ctron did you use the dp referenced in the test description? (https://s3.amazonaws.com/esf-resources/securityQA/org.eclipse.kura.example.publisher.dp)
Or did you provide a custom one?

I've tested few times using both the file selection to grab the file from the filesystem or specifying the url directly and it always worked for me. 
Could you pass me the dp you used? So I can try to test in the same conditions.

Could you also send me the result of this linux command? `cat /var/log/audit/audit.log | grep denied`

Thanks

**Comment by ctron** [comment]
Yes, this is the one. Should I have used a different one?

Well I had to re-try. The first time I ran into this issue. After that I didn't. So I could go on with testing.

```
[root@localhost ~]# cat /var/log/audit/audit.log | grep denied
type=AVC msg=audit(1455208163.898:69): avc:  denied  { fowner } for  pid=808 comm="dhcpd" capability=3  scontext=system_u:system_r:dhcpd_t:s0 tcontext=system_u:system_r:dhcpd_t:s0 tclass=capability permissive=0
```

**Comment by MMaiero** [comment]
>  Should I have used a different one?

No, no, this is the correct one.

There seem to be no seLinux related issues.
If you try to redeploy the same dp, does the same error happen?

**Comment by ctron** [comment]
As I tried to explain. I did install it and the error occurred. Then I re-installed it and it was ok. It was the same DP.

**Comment by ctron** [comment]
This did not appear during today's test run. So I guess this is fixed and can be closed.
