### ISSUE TITLE
[Kura 2.1.0 QA] NET-ETH0-005 Failed to connect to MQTT over SSL after reboot

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#947]
While test NET-ETH0-004 did work, rebooting in NET-ETH0-005 did not.

Diagnostic information will be in file `kura-logs-20161215-111226.tar.gz` sent by e-mail.

**Comment by ctron** [comment]
I just continued the test with NET-WIFI-005 and NET-WIFI-006. And I do have the same pattern here.

The first attempt after connecting succeeds. After the reboot it runs into the same re-connect loop.

**Comment by cdealti** [comment]
From your log, it looks like you have reconfigured the eth0 interface:
```
2016-12-15 11:47:28,965 [EthernetMonitor_eth0] INFO  o.e.k.n.a.m.EthernetMonitorServiceImpl - Found a new Ethernet network configuration for eth0
```
And it appears to be configured as "Enabled for LAN" and acting as a DHCP server:

```
2016-12-15 11:47:32,605 [EthernetMonitor_eth0] INFO  o.e.k.n.a.NetworkAdminServiceImpl - bringing interface eth0 up
2016-12-15 11:47:32,607 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: ifconfig eth0 up

2016-12-15 11:47:32,616 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - ifconfig eth0 up
 returned with exit value:0
2016-12-15 11:47:32,618 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: ifup eth0

2016-12-15 11:47:32,631 [qtp23600506-28] WARN  o.e.k.n.a.v.l.WpaSupplicantConfigReader - WPA in client mode is not configured
2016-12-15 11:47:41,249 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - ifup eth0
 returned with exit value:0
2016-12-15 11:47:41,400 [qtp23600506-28] INFO  o.e.k.c.c.ConfigurationServiceImpl - Loading init configurations from: 1481797463408...
2016-12-15 11:47:41,526 [EthernetMonitor_eth0] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: dhcpd -cf /etc/dhcpd-eth0.conf -pf /var/run/dhcpd-eth0.pid
2016-12-15 11:47:41,774 [EventAdmin Async Event Dispatcher Thread] WARN  o.e.k.n.a.m.DnsMonitorServiceImpl - Not Setting DNS servers to empty
2016-12-15 11:47:41,778 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: /bin/systemctl stop named
2016-12-15 11:47:41,973 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - /bin/systemctl stop named returned with exit value:0
2016-12-15 11:47:42,584 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: /bin/systemctl start named
2016-12-15 11:47:43,069 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - /bin/systemctl start named returned with exit value:0
```

This is not the configuration described in the prerequisite NET-ETH0-003 which requires the interface "Enabled for WAN".

In this situation you should not have neither a default gateway nor DNS servers so it's unlikely you will be able to connect:

```
MqttException (0) - java.net.UnknownHostException: iot.eclipse.org
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:604)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: iot.eclipse.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:82)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:590)
	... 1 more
```

Can you please recheck your network configuration

**Comment by ctron** [comment]
This is the full kura log file. Are you sure you read it starting from the end? I am pretty sure I configured it correctly both times. But I will re-try.

**Comment by cdealti** [comment]
Yes, from the end

**Comment by ctron** [comment]
So at some point during testing it started to work again. Even with reboots. Maybe it was a hickup at the Eclipse MQTT server. I don't really know.

**Comment by cdealti** [comment]
This is different. If you read the log from the beginning, some disconnections can be due to the Eclipse MQTT server:

```
2016-12-15 11:46:44,805 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.DataServiceImpl - Connecting...
2016-12-15 11:46:44,808 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - Creating a new client instance
2016-12-15 11:46:44,811 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - Using memory persistence for in-flight messages
2016-12-15 11:46:44,817 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - # ------------------------------------------------------------
2016-12-15 11:46:44,819 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connection Properties
2016-12-15 11:46:44,822 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  broker    = ssl://iot.eclipse.org:8883
2016-12-15 11:46:44,825 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  clientId  = B8:27:EB:97:D8:D5
2016-12-15 11:46:44,827 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  username  = username
2016-12-15 11:46:44,830 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  password  = XXXXXXXXXXXXXX
2016-12-15 11:46:44,832 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  keepAlive = 30
2016-12-15 11:46:44,835 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  timeout   = 20
2016-12-15 11:46:44,838 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  cleanSession    = true
2016-12-15 11:46:44,840 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  MQTT version    = 3.1.1
2016-12-15 11:46:44,843 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willDestination = $EDC/account-name/B8:27:EB:97:D8:D5/MQTT/LWT
2016-12-15 11:46:44,846 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willMessage     = 
2016-12-15 11:46:44,848 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #
2016-12-15 11:46:44,851 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connecting...
2016-12-15 11:46:44,854 [pool-9-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED fast blinking
2016-12-15 11:46:45,106 [MQTT Con: B8:27:EB:97:D8:D5] INFO  o.e.k.c.s.SSLSocketFactoryWrapper - SSL Endpoint Identification enabled.
2016-12-15 11:46:45,988 [DataServiceImpl:ReconnectTask] WARN  o.e.k.c.d.t.m.MqttDataTransport - xxxxx  Connect failed. Forcing disconnect. xxxxx {}
Connection lost (32109) - java.net.SocketException: Connection reset
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:154)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:71)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:89)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:112)
	... 1 more
```

However those at the end of the log are different and related to a wrong network configuration.
Have you changed network configuration again before it started working again?

**Comment by ctron** [comment]
I can't really tell. I did quite a number of tests and for quit some time it just didn't work and I left it that way, performing other tests. At some point is recognized that is was working again.

Close it for now. Reopen it if re-appears. Maybe that is the best approach.
