### ISSUE TITLE
[Kura 2.1.0 QA] BLE warnings when disabling scan

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#950]
Warnings are logged every once in a while when BT scan is disabled (at least once every 3-4 tries).

How to reproduce:
* install org.eclipse.kura.example.ble.tisensortag as stated in PTC-BLE-002
* enable scan and wait for readings to be logged
* disable scan
* enable, wait for values and disable again

Repeat until the following warnings are logged:
```
2016-12-15 12:39:37,657 [qtp831678-27] INFO  o.e.k.c.c.ConfigurationServiceImpl - Updating Configuration of ConfigurableComponent org.eclipse.kura.example.ble.tisensortag.BluetoothLe ... Done.
2016-12-15 12:39:37,660 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.l.b.u.BluetoothProcess - Closing streams and killing...
2016-12-15 12:39:37,663 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.l.b.l.BluetoothGattImpl - Disconnected
2016-12-15 12:39:37,663 [BluetoothProcess Input Stream Gobbler] WARN  o.e.k.l.b.u.BluetoothProcess - Error in processing the input stream : 
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:283)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.read(BufferedReader.java:182)
        at org.eclipse.kura.linux.bluetooth.util.BluetoothProcess.readInputStreamFully(BluetoothProcess.java:148)
        at org.eclipse.kura.linux.bluetooth.util.BluetoothProcess.access$1(BluetoothProcess.java:141)
        at org.eclipse.kura.linux.bluetooth.util.BluetoothProcess$1.run(BluetoothProcess.java:61)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-12-15 12:39:37,663 [BluetoothProcess ErrorStream Gobbler] WARN  o.e.k.l.b.u.BluetoothProcess - Error in processing the error stream : 
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:283)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.read(BufferedReader.java:182)
        at org.eclipse.kura.linux.bluetooth.util.BluetoothProcess.readErrorStreamFully(BluetoothProcess.java:187)
        at org.eclipse.kura.linux.bluetooth.util.BluetoothProcess.access$3(BluetoothProcess.java:180)
        at org.eclipse.kura.linux.bluetooth.util.BluetoothProcess$2.run(BluetoothProcess.java:76)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-12-15 12:39:37,700 [qtp831678-27] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/data/snapshots/snapshot_1481805577657.xml...
```

Sometimes only one of the warnings gets logged.

Probably the issue is not critical, but the log doesn't look that nice.

Encountered on Kura 2.1.0 build 12 and no-net 16, probably other flavors as well. Raspberry Pi 3, as part of #788.

**Comment by cdealti** [comment]
It's more of an aesthetics issue unless, by disabling/enabling the scan the functionality is compromised.
If not let's postpone it.

**Comment by markoer** [comment]
The service remains functional across stops and starts i.e. works when started, so the fix can be postponed.
