### ISSUE TITLE
[Kura 2.1.0 QA] BLE example beacon scanner issue

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#952]
Install and make sure beacon works as in PTC-BLE-004 - PTC-BLE-007.
Install org.eclipse.kura.example.beacon.scanner as specified in PTC-BLE-009 of #788. The package installs, but when enabled, the following is logged. No beacon is detected/logged afterward.
```
2016-12-15 13:20:49,604 [qtp831678-28] INFO  o.e.k.c.c.ConfigurationServiceImpl - Updating Configuration of ConfigurableComponent org.eclipse.kura.example.beacon.scanner.BeaconScannerExample ... Done.
2016-12-15 13:20:49,615 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.l.b.l.BluetoothLeScanner - Starting bluetooth le beacon scan...
2016-12-15 13:20:49,635 [BluetoothProcess BTSnoop Gobbler] WARN  o.e.k.l.b.u.BluetoothProcess - Error in processing the error stream : 
java.io.EOFException: Length to read: 16 actual: 0
        at org.apache.commons.io.IOUtils.readFully(IOUtils.java:2539)
        at org.apache.commons.io.IOUtils.readFully(IOUtils.java:2558)
        at org.eclipse.kura.linux.bluetooth.le.beacon.BTSnoopParser.readRecord(BTSnoopParser.java:26)
        at org.eclipse.kura.linux.bluetooth.util.BluetoothProcess.readBTSnoopStreamFully(BluetoothProcess.java:172)
        at org.eclipse.kura.linux.bluetooth.util.BluetoothProcess.access$4(BluetoothProcess.java:166)
        at org.eclipse.kura.linux.bluetooth.util.BluetoothProcess$3.run(BluetoothProcess.java:101)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Kura 2.1.0 build 16 no-net on RPi3.

**Comment by cdealti** [comment]
Can you send me a tgz of the whole /var/log/ directory?

**Comment by cdealti** [comment]
@markoer the intent of the test is that the beacon and beacon scanner examples run on two different devices.

**Comment by pierantoniomerlino** [comment]
@markoer Could you please check if `hcidump` command is installed on your system?

**Comment by markoer** [comment]
It's not. Should I install it?

**Comment by pierantoniomerlino** [comment]
Yes, you should. The scanner uses hcidump to get raw data from bluetooth. Probably we should document this...

**Comment by markoer** [comment]
Great, after installing `bluez-hcidump` package on a different device, the scanner actually worked. I updated the spreadsheet(s) with this precondition. Maybe it could be added to some other documentation, too.

If you want, the issue can be closed.

**Comment by cdealti** [comment]
@ctron @djurod FYI in case you notice this too.
